#!/bin/bash
#
set -u
source misc/lib_build_local
pdfs=""
dcs=$(ls -1 DC-SAP* DC-SLES4SAP-* DC-SLES-SAP*)
arch="All_SAP_HA_Docs"

doc_make $dcs # sets Gpdfs and GtimeStamp
tar -cvzf build/${arch}-${GtimeStamp}.tgz ${Gpdfs}
echo "Archive: build/${arch}-${GtimeStamp}.tgz"
