#!/bin/bash
#
set -u
source misc/lib_build_local
pdfs=""
dcs="DC-SAP_S4HA10_SetupGuide_SimpleMount-SLE15"
arch="SAP_HA_Docs_SimpleMount"

doc_make $dcs # sets Gpdfs and GtimeStamp
tar -cvzf build/${arch}-${GtimeStamp}.tgz ${Gpdfs}
echo "Archive: build/${arch}-${GtimeStamp}.tgz"
