#!/bin/bash
#
set -u
source misc/lib_build_local
pdfs=""
dcs="DC-SLES4SAP-hana-scaleOut-PerfOpt-15"
arch="SAP_HA_Docs_hana-scaleOut-PerfOpt-15"

doc_make $dcs # sets Gpdfs and GtimeStamp
tar -cvzf build/${arch}-${GtimeStamp}.tgz ${Gpdfs}
echo "Archive: build/${arch}-${GtimeStamp}.tgz"
