#!/bin/bash
#
set -u
source misc/lib_build_local
pdfs=""
dcs="DC-SLES4SAP-hana-angi-scaleup-perfopt-16"
arch="SAP_HA_Docs_hana-angi-scaleup-perfopt-16"

doc_make $dcs # sets Gpdfs and GtimeStamp
tar -cvzf build/${arch}-${GtimeStamp}.tgz ${Gpdfs}
echo "Archive: build/${arch}-${GtimeStamp}.tgz"
