#!/bin/bash
#
source misc/lib_build_local
pdfs=""
dcs="DC-SAP_S4HA10_SetupGuide_SimpleMount-SLE15"
arch="BuiltDocs"
dcNr=$(echo "$dcs" | wc -l)
i=0

for dc in $dcs; do
    (( i++ ))
    stdDc="$dc"
    echo "building $stdDc ($i / $dcNr)"
    init
    build
    fetch
    pdfs="$pdfs build/${pdf}"
    echo "pdf: build/${pdf}"
done
tar -cvzf build/${arch}-${timeStamp}.tgz ${pdfs}
echo "Archive: build/${arch}-${timeStamp}.tgz"
