#!/bin/bash
#
source misc/lib_build_local
pdfs=""
dcs=$(ls -1 DC-SAP* DC-SLES4SAP-* DC-SLES-SAP*)
arch="All_SAP_HA_Docs"
dcNr=$(echo "$dcs" | wc -l)
i=0

for dc in $dcs; do
    (( i++ ))
    stdDc="$dc"
    echo "building $stdDc ($i / $dcNr)"
    init
    build
    fetch
    pdfs="$pdfs build/${pdf}"
done
tar -cvzf build/${arch}-${timeStamp}.tgz ${pdfs}
echo "Archive: build/${arch}-${timeStamp}.tgz"
