== About this guide

The following sections focus on background information and the purpose of the
document at hand.

=== Introduction

{sles4sapReg} is the optimal platform to run {sapReg} applications with high
availability. Together with a redundant layout of the technical infrastructure,
single points of failure can be eliminated.

{sapBSReg} is a sophisticated application platform for large enterprises
and mid-size companies. Many critical business environments require the highest
possible {sapReg} application availability.

The described cluster solution can be used for {sapS4pl}.

{sapS4pl} is a common stack of middleware functionalities used to support SAP
business applications. The {sapERS} constitutes application
level redundancy for one of the most crucial components of the {sapS4pl} stack,
the enqueue service. An optimal effect of the enqueue replication mechanism can
be achieved when combining the application level redundancy with a high
availability cluster solution, as provided for example by {sles4sap}.

In contrast to the traditional setups, this setup uses an additional NFS mount
for the {sap} application layer without the need to have dedicated block devices
and cluster-controlled file systems. That greatly simplifies the overall
architecture, implementation and maintenance of a {sleHA} cluster for
{sapS4pl} with {sapERS}.
// TODO PRIO1: certification?
//.Certified by SAP
//image::SAP_Certi_Integration_SAPS4HANA_R.svg[SVG]

For additional information on the simple mount architecture, read:

- {SUSE} blog article "Simple Mount Structure for SAP Application Platform"
(https://www.suse.com/c/simple-mount-structure-for-sap-application-platform/).

- {SUSE} knowledge base TID (Technical Information Document) 00019944 "Use of Filesystem resource for ASCS/ERS HA setup not possible" (https://www.suse.com/support/kb/doc/?id=000019944).

- Manual page ocf_suse_SAPStartSrv(7).

[id="sec.resource"]
=== Additional documentation and resources

Chapters in this manual contain links to additional documentation resources that
are either available on the system or on the Internet. Among them are:

- {SUSE} product documentation at https://documentation.suse.com/

- {SUSE} best practices Web page at https://documentation.suse.com/sbp/sap-16/

- Supported high availability solutions by {sles4sap} overview at
https://documentation.suse.com/sles-sap/sap-ha-support/

Lastly, there are manual pages shipped with the product.

// Standard SUSE includes
=== Feedback
include::../common_intro_feedback.adoc[]

//=== Documentation Conventions
//TODO PRIO3: work on SUSE doc standard conventions file
//include::common_intro_typografie.adoc[]

