:leveloffset: 0
== Appendix

=== CRM configuration of a two-node cluster

Find below the complete `crm` configuration for {sap} system {mySid}. This example
is for the two-node cluster, but without priority fencing.
In a multi-node cluster, you will find additional node entries like *node 3: {my3nd3}*.
// TODO PRIO1: adapt the below example
[subs="attributes"]
----
node 1: {my2nd1}
node 2: {my2nd2}
primitive rsc_ip_{mySid}_{myInstAscs} IPaddr2 \
    params ip={myVipAAscs} \
    op monitor interval=10 timeout=20
primitive rsc_ip_{mySid}_{myInstErs} IPaddr2 \
    params ip={myVipAErs} \
    op monitor interval=10 timeout=20
primitive rsc_SAPStartSrv_{mySID}_{myInstAscs} ocf:suse:SAPStartSrv \
    params InstanceName={mySID}_{myInstAscs}_{myVipNAscs}
primitive rsc_SAPStartSrv_{mySID}_{myInstErs} ocf:suse:SAPStartSrv \
    params InstanceName={mySID}_{myInstErs}_{myVipNErs}
primitive rsc_sap_{mySID}_{myInstAscs} SAPInstance \
    op monitor interval=21 timeout=60 on-fail=restart \
    params InstanceName={mySID}_{myInstAscs}_{myVipNAscs} \
        START_PROFILE="/usr/sap/{mySid}/SYS/profile/{mySid}_{myInstAscs}_{myVipNAscs}" \
        AUTOMATIC_RECOVER=false MINIMAL_PROBE=true \
        meta resource-stickiness=5000
primitive rsc_sap_{mySID}_{myInstErs} SAPInstance \
    op monitor interval=22 timeout=60 on-fail=restart \
    params InstanceName={mySID}_{myInstErs}_{myVipNErs} \
         START_PROFILE="/usr/sap/{mySid}/SYS/profile/{mySid}_{myInstErs}_{myVipNErs}" \
         AUTOMATIC_RECOVER=false IS_ERS=true MINIMAL_PROBE=true
primitive fencing-sbd stonith:fence_sbd \
    params pcmk_delay_max=30
group grp_{mySid}_{myInstAscs} rsc_ip_{mySid}_{myInstAscs} \
    rsc_SAPStartSrv_{mySID}_{myInstAscs} rsc_sap_{mySid}_{myInstAscs} \
    meta resource-stickiness=3000
group grp_{mySid}_{myInstErs} rsc_ip_{mySid}_{myInstErs} \
    rsc_SAPStartSrv_{mySID}_{myInstErs} rsc_sap_{mySid}_{myInstErs}
colocation col_sap_{mySid}_separate -5000: \
    grp_{mySid}_{myInstErs} grp_{mySid}_{myInstAscs}
order ord_sap_{mySid}_ascs_first Optional: rsc_sap_{mySID}_{myInstAscs}:start \
    rsc_sap_{mySID}_{myInstErs}:stop symmetrical=false
property cib-bootstrap-options: \
    have-watchdog=true \
    cluster-infrastructure=corosync \
    cluster-name=2nodes \
    fencing-enabled=true \
    fencing-timeout=150 \
    placement-strategy=balanced
rsc_defaults rsc-options: \
    resource-stickiness=1 \
    migration-threshold=3 \
    failure-timeout=86400
op_defaults op-options: \
    timeout=600 \
    record-pending=true
----

=== CRM configuration fragments of the two-node cluster with priority fencing

Find below `crm` configuration fragments for {sap} system {mySid}. This example
shows the specific items for the two-node cluster with priority fencing.
This configuration matches the previous one, except for the following items:
// TODO PRIO1: check the below example
[subs="attributes"]
----
...
primitive rsc_sap_{mySID}_{myInstAscs} SAPInstance \
    op monitor interval=21 timeout=60 on-fail=restart \
    params InstanceName={mySID}_{myInstAscs}_{myVipNAscs} \
        START_PROFILE="/usr/sap/{mySid}/SYS/profile/{mySid}_{myInstAscs}_{myVipNAscs}" \
        AUTOMATIC_RECOVER=false MINIMAL_PROBE=true \
        meta resource-stickiness=5000 priority=100
...
primitive fencing-sbd stonith:fence_sbd \
    params pcmk_delay_max=15
...
property cib-bootstrap-options: \
    have-watchdog=true \
    cluster-infrastructure=corosync \
    cluster-name=2nodes \
    fencing-enabled=true \
    fencing-timeout=150 \
    placement-strategy=balanced \
    priority-fencing-delay=30
...
----

=== Corosync configuration of the two-node cluster

Find below the Corosync configuration for one corosync ring. Ideally, two rings are used.
// TODO PRIO1: check the below example
[subs="specialchars,attributes"]
----
{my2nd1}:~ # cat /etc/corosync/corosync.conf
totem {
        version: 2
        cluster_name: 2nodes
        transport: knet
        token: 5000
        join: 60
        max_messages: 20
        token_retransmits_before_loss_const: 10
        crypto_hash: sha256
        crypto_cipher: aes256
}

quorum {
        provider: corosync_votequorum
        two_node: 1
}

logging {
        to_logfile: yes
        logfile: /var/log/cluster/corosync.log
        to_syslog: yes
        timestamp: hires
}

nodelist {
        node {
                ring0_addr: {myIP2nd1}
                name: {my2nd1
                nodeid: 1
        }

        node {
                ring0_addr: {myIP2nd2}
                name: {my2nd2}
                nodeid: 2
        }

}
----

=== Corosync configuration of the multi-node cluster

Find below the Corosync configuration for one corosync ring. Ideally, two rings aree used.
// TODO PRIO1: check the below example
[subs="specialchars,attributes,quotes"]
----
{my3nd1}:~ # cat /etc/corosync/corosync.conf
totem {
        version: 2
        cluster_name: 3nodes
        transport: knet
        token: 5000
        join: 60
        max_messages: 20
        token_retransmits_before_loss_const: 10
        crypto_hash: sha256
        crypto_cipher: aes256
}

quorum {
        provider: corosync_votequorum
        two_node: 0
        expected_votes: 3
}

logging {
        to_logfile: yes
        logfile: /var/log/cluster/corosync.log
        to_syslog: yes
        timestamp: hires
}

nodelist {
		node {
			ring0_addr: {myIP3nd1}
            name: {my3nd1}
			nodeid: 1
		}

		node {
			ring0_addr: {myIP3nd2}
            name: {my3nd2}
			nodeid: 2
		}

		node {
			ring0_addr: {myIP3nd3}
            name: {my3nd3}
			nodeid: 3
		}
}
----

++++
<?pdfpagebreak?>
++++

