== Implementing the cluster

The main procedure to implement the cluster is as follows:

.Tasks

. Prepare the operating system and install the cluster software.
. Configure the cluster base including corosync and resource manager.
. Configure the cluster resources.
. Tuning the cluster timing in special for the SBD.

///////////////////////////////
TODO PRIO3: Do we really need to stop, unconfigure and unmount?
Maybe we find a way to configure the resources that the cluster just
accepts the already started resource groups - lets see ;-)
///////////////////////////////

NOTE: Before you continue to set up the cluster, perform the following actions:
First, stop all SAP instances. Then, remove the (manually added) IP addresses on
the cluster nodes. Finally, unmount the file systems which will be controlled by
the cluster later.

NOTE: Create the SBD device/partition before starting. Verify which
device/partition to use. In this setup guide, the disk _{myDevA}_
is reserved for SBD usage.

=== Preparing the operating system and installing the cluster software

- Set up and enable `chrony`.

// TODO PRIO3: pattern sap-nw?
// - Install the RPM pattern *ha_sles* and package `sapstartsrv-resource-agents` on both cluster nodes.
- Install the RPM pattern sles_sap_HAAPP on both cluster nodes.
+
[subs="attributes"]
----
# zypper in -t pattern sles_sap_HAAPP
----

=== Configuring the cluster base

.Tasks

- To configure the cluster base, use the interactive command line tool
`crm` (crm cluster init).

- Install and configure the watchdog device on the first machine.

Instead of deploying the software-based solution, rather use a hardware-based watchdog device.
The following example uses the software device but can be easily adapted to the hardware device.

[subs="attributes"]
----
# modprobe softdog
# echo softdog > /etc/modules-load.d/watchdog.conf
# systemctl restart systemd-modules-load
# lsmod | egrep "(wd|dog|i6|iT|ibm)"
----

- Install and configure the cluster stack on the first machine

[subs="attributes"]
----
# crm cluster init -s  {myDevA}
----

- Join the second node.

On the second node, perform some preparation steps.

[subs="attributes"]
----
# modprobe softdog
# echo softdog > /etc/modules-load.d/watchdog.conf
# systemctl restart systemd-modules-load
# lsmod | egrep "(wd|dog|i6|iT|ibm)"
----

To configure the cluster base, use the interactive command line tool
 `crm`.

[subs="attributes"]
----
# crm cluster join -c {my2nd1}
----

- The _crm_mon -1r_ output should look as follows:

[subs="attributes"]
----
Stack: corosync
Current DC: {my2nd1} (version 1.1.18+20180430.b12c320f5-1.14-b12c320f5) - partition with quorum
Last updated: Mon Jan 28 13:10:37 2019
Last change: Wed Jan 23 09:52:57 2019 by root via cibadmin on {my2nd1}

2 nodes configured
1 resource configured

Online: [ {my2nd1} {my2nd2} ]

fencing-sbd	(stonith:fence_sbd):	Started {my2nd1}
----

=== Configuring cluster resources

The SAPInstance resource configuration is needed to
start and stop the ASCS and the ERS instances themselves.
See manual page ocf_heartbeat_SAPInstance(7) for details.

The SAPStartSrv resource starts and stops the `sapstartsrv` service and
guarantees that only one instance is running per cluster at the same time.
See manual page ocf_suse_SAPStartSrv(7) for details.

In the latest version of ENSA2, the ASCS instance receives the enqueue lock
table over the network from the ERS instance. Usually, both instances
run on different nodes. However, if only node is available, the ASCS instance
starts on the same host as the the ERS instance.

.Resources and constraints
image::sles4sap_s4hana2021_resources_simple_mount.svg[SVG]

////
The implementation is done using a new flag "runs_ers_$SID" within
the resource agent (RA), enabled using the resource parameter "IS_ERS=TRUE".
////

// TODO PRIO1: what does below mean?
// Another benefit of this concept is that you can work with native (mountable)
// file systems instead of a shared (NFS) file system for the {sap} instance
// directories.

==== Preparing the cluster for adding the resources

To prevent the cluster from starting partially defined resources, set the cluster
to maintenance mode. This deactivates all monitor actions.

As user _root_, type the following command:

[subs="attributes"]
----
# crm configure property maintenance-mode=true
----
////
TODO PRIO2: for 2+ node cluster different SBD settings
==== Configure the SBD Resource
Verify the SBD cluster configuration and if needed, modify them as described.

.SBD fencing
================================================
[subs="attributes"]
----
# crm resource param fecing-sbd set pcmk_action_limit -1
----
================================================
////

==== Preparing the new SAPStartSrv resource agent implementation

As a prerequisite for having a single NFS mount for ASCS and ERS, the
`sapstartsrv` instance agents of ASCS and ERS must not be started by the
`sapinit` service during system start-up, as these services are started and
stopped by dedicated cluster resources.

With the `sapstartsrv-resource-agents` RPM package, two systemd
services called `sapping` and `sappong` are included.  `sapping` runs before `sapinit` and
moves _/usr/sap/sapservices_ out of the way. Consequently, the `sapstartsrv`
instance agents are not started automatically by `sapinit`. `sappong` runs after
`sapinit` and moves _/usr/sap/sapservices_ back to its original location.

On {my2nd1} and {my2nd2}, enable the `sapping` and `sappong` services.

================================================
[subs="attributes"]
----
# systemctl enable sapping
# systemctl enable sappong
----
================================================
See manual pages ocf_suse_SAPStartSrv(7), sapping(8) and SAPStartSrv_basic_cluster(7)
for details.

==== Configuring resources for the ASCS Instance

First, configure the resources for the IP address, the {sap} instance agent and
the {sap} instance. You need to adapt the parameters for your specific environment.

Ensure the parameter *MINIMAL_PROBE* is set to *true* in the {sap} instance definition .

.ASCS primitive
================================================
[subs="attributes"]
----
primitive rsc_ip_{mySID}_{myInstAscs} IPaddr2 \
  params ip={myVipAAscs} \
  op monitor interval=21 timeout=20
primitive rsc_SAPStartSrv_{mySID}_{myInstAscs} ocf:suse:SAPStartSrv \
  params InstanceName={mySID}_{myInstAscs}_{myVipNAscs}
primitive rsc_sap_{mySID}_{myInstAscs} SAPInstance \
  op monitor interval=22 timeout=60 on-fail=restart \
  params InstanceName={mySID}_{myInstAscs}_{myVipNAscs} \
     START_PROFILE="/usr/sap/{mySid}/SYS/profile/{mySid}_{myInstAscs}_{myVipNAscs}" \
     AUTOMATIC_RECOVER=false MINIMAL_PROBE=true \
  meta resource-stickiness=5000
----
================================================
The shown SAPInstance monitor timeout is a trade-off between fast recovery of
the ASCS vs. resilience against sporadic temporary NFS issues. You may slightly
increase it to fit your infrastructure. Consult the storage or NFS server
documentation for appropriate timeout values. Make sure the *SAPStartSrv* resource
has *NO* monitor operation configured.
See also manual pages ocf_heartbeat_SAPInstance(7), ocf_heartbeat_IPaddr2(7),
ocf_suse_SAPStartSrv(7) and nfs(5).

.ASCS group
================================================
[subs="attributes"]
----
group grp_{mySID}_{myInstAscs} \
  rsc_ip_{mySID}_{myInstAscs} rsc_SAPStartSrv_{mySID}_{myInstAscs} rsc_sap_{mySID}_{myInstAscs} \
  meta resource-stickiness=3000
----
================================================

Create a _txt_ file (like _crm_ascs.txt_) with your preferred text editor. Add
both examples (primitives and group) to that file and load the configuration to
the cluster manager configuration.

As user _root_, type the following command:

[subs="attributes"]
----
# crm configure load update crm_ascs.txt
----

==== Configuring resources for the ERS Instance

Next, configure the resources for the IP address, the {sap} instance agent
and the {sap} instance. You need to adapt the parameters for your specific
environment.

Ensure the parameter *MINIMAL_PROBE* is set to *true* in the {sap} instance definition .

The specific parameter *IS_ERS=true* must only be set for the ERS instance.

.ERS primitive
================================================
[subs="attributes"]
----
primitive rsc_ip_{mySID}_{myInstErs} IPaddr2 \
  params ip={myVipAErs} \
  op monitor interval=10 timeout=20
primitive rsc_SAPStartSrv_{mySID}_{myInstErs} ocf:suse:SAPStartSrv \
  params InstanceName={mySID}_{myInstErs}_{myVipNErs}
primitive rsc_sap_{mySID}_{myInstErs} SAPInstance \
  op monitor interval=22 timeout=60 on-fail=restart \
  params InstanceName={mySID}_{myInstErs}_{myVipNErs} \
     START_PROFILE="/usr/sap/{mySid}/SYS/profile/{mySid}_{myInstErs}_{myVipNErs}" \
     AUTOMATIC_RECOVER=false IS_ERS=true MINIMAL_PROBE=true
----
================================================
The shown SAPInstance monitor timeout is a trade-off between fast recovery of
the ERS vs. resilience against sporadic temporary NFS issues. You may slightly
increase it to fit your infrastructure. Consult the storage or NFS server
documentation for appropriate timeout values. Essure the *SAPStartSrv* resource
has *NO* monitor operation configured.
See also manual pages ocf_heartbeat_SAPInstance(7), ocf_heartbeat_IPaddr2(7) ocf_suse_SAPStartSrv(7)
and nfs(5).

.ERS group
================================================
[subs="attributes"]
----
group grp_{mySID}_{myInstErs} \
  rsc_ip_{mySID}_{myInstErs} rsc_SAPStartSrv_{mySID}_{myInstErs} rsc_sap_{mySID}_{myInstErs}
----
================================================

Create a _txt_ file (like _crm_ers.txt_) with your preferred text editor. Add
both examples (primitives and group) to that file and load the configuration to
the cluster manager configuration.

As user _root_, type the following command:

[subs="attributes"]
----
# crm configure load update crm_ers.txt
----

==== Configuring the colocation constraints between ASCS and ERS

An ASCS instance should avoid starting up on the cluster node running the ERS
instance if any other node is available. The ENSA2 setup can resynchronize
the lock table over the network.

If the ASCS instance has been started by the cluster on the ERS node, the ERS
instance should be moved to another cluster node (col_sap_{mysid}_no_both). This
constraint is needed to ensure that the ERS instance will synchronize the locks
again and the cluster is ready for an additional takeover.

.Location constraint
================================================
[subs="attributes"]
----
colocation col_sap_{mysid}_separate -5000: grp_{mySID}_{myInstErs} grp_{mySID}_{myInstAscs}
order ord_sap_{mysid}_ascs_first Optional: rsc_sap_{mySID}_{myInstAscs}:start \
      rsc_sap_{mySID}_{myInstErs}:stop symmetrical=false
----
================================================

Create a _txt_ file (like _crm_col.txt_) with a text editor. Add both constraints
to that file and load the configuration to the cluster manager configuration.

As user _root_, type the following command:

[subs="attributes"]
----
# crm configure load update crm_col.txt
----

==== Activating the cluster

The last step is to end the cluster maintenance mode and allow the
cluster to detect already running resources.

As user _root_, type the following command:

[subs="attributes"]
----
# crm configure property maintenance-mode="false"
----

////
 TODO PRIO3: Subsection "tune cluster timeouts and sbd"
////


////
############################
#
# ADMINISTRATION
#TODO PRIO3: renaming Do and Don't to Operational Tasks
############################
////

