== SUSE OpenStack products

SUSE is a very active member in the OpenStack Community and has a long
track record of participating in OpenStack development. We also have a
proven history of helping customers in creating cloud setups, covering
smaller local installations and large public scale out setups. We have
developers and consultants in-house who can support customers even in
most complex matters and with difficult issues. And of course, we have a
number of boxed products that customers can use to bootstrap their cloud
project quickly and yet in a reliable manner.

=== SUSE Linux Enterprise Server

SUSE Linux Enterprise Server (_SLES_) is our Linux distribution tailored
specifically to the requirements of enterprise workloads. It receives
regular updates and new features and is also getting security patches as
they become public.

Last but not least, SUSE Linux Enterprise Server is the fundament for
all other boxed SUSE products, allowing these to receive all important
updates as well.

=== SUSE OpenStack Cloud

SUSE OpenStack Cloud (_SOC_) is the OpenStack distribution maintained by
SUSE. It contains all standard OpenStack components and additional tools
to allow for an easy installation and seamless maintenance of clouds of
any size. Using _SOC_, you can get your own cloud environment started in
a very short time.

Thanks to our lengthy experience, it also comes with a configuration as
generic as possible and yet prepared for most use-caes the best way
possible.

=== SUSE Enterprise Storage

SUSE Enterprise Storage (_SES_) is our Software Defined Storage product
based on the Ceph object store solution. It allows for the creation of
large scale storage environments that are an ideal fit when looking for
storage in the cloud. In addition to Ceph itself, _SES_ also contains
several tools and helpers to allow for a seamless installation as well
as effective maintenance.

=== SUSE OpenStack Cloud Monitoring

SUSE OpenStack Cloud Monitoring is an OpenStack based monitoring tool
that leverages the advantages of OpenStack Monasca. It's a stand-alone
product that can be used to monitor generic environments according to
modern-days best practices. When combined wth _SOC_, it is the ideal way
to monitor OpenStack clouds of any size.

=== SUSE Support

Just as important as having a stable and resilient environment is it to
have efficient help in case things go wrong. At SUSE, we know our tools
and products as well as the underlying Open Source technology by our
heart -- and we will be happy to help you out when in trouble. Support
from SUSE is available for all existing boxed SUSE products.

=== SUSE Training & Consultancy

Knowledge is the key to building and running large scale environments as
good as possible. From SUSE, you can get help by our excellent experts
on all matters related to massively scalable environments. And to make
sure that you can run and maintain the platform that you have set up
together with our experts, you can also get training on all SUSE products
and the underlaying technology from us.

=== Get in touch!

If you are interested in our products or our solutions, please do not a
second hesitate to get in touch with our pre-sales engineers. Together
with you, we will find out how we can help you the best possible way --
and we will make sure together with you that your project turns into a
ringing success.

// vim:set syntax=asciidoc:
