== SUSE OpenStack products

SUSE is a very active member in the OpenStack Community and has a long
track record of participating in OpenStack development. SUSE has a
proven history of helping customers in creating cloud setups, covering
smaller local installations and large public scale-out setups. SUSE
consultants, support engineers and developers can support customers even in
most complex scenarios and with difficult issues. What's more, SUSE provides
a number of Linux-based products that customers can use to bootstrap their cloud
project quickly, efficiently and reliably.

=== SUSE Linux Enterprise Server

SUSE Linux Enterprise Server is the Linux distribution tailored
specifically to the requirements of enterprise workloads. It receives
regular updates and new features and is also getting security patches as
they become public.

SUSE Linux Enterprise Server is the fundament for all other SUSE Linux Enterprise-based
products, allowing these to receive all important updates as well.

=== SUSE OpenStack Cloud

SUSE OpenStack Cloud is the OpenStack distribution maintained by
SUSE. It contains all standard OpenStack components and additional tools
to allow for an easy installation and seamless maintenance of clouds of
any size. Using SUSE OpenStack Cloud, you can get your own cloud environment 
started in a very short time.

Thanks SUSE's long-term experience with OpenStack technologies, it also comes 
with a configuration which is as generic as possible but yet prepared for 
most use-cases the best way possible.

=== SUSE Enterprise Storage

SUSE Enterprise Storage is the Software Defined Storage offering
based on the Ceph object store solution. It allows for the creation of
large-scale storage environments that are an ideal fit when looking for
storage in the cloud. In addition to Ceph itself, SUSE Enterprise Storage
contains several tools and helpers to allow for a seamless installation 
and effective maintenance.

=== SUSE OpenStack Cloud Monitoring

SUSE OpenStack Cloud Monitoring is an OpenStack based monitoring tool
that leverages the advantages of OpenStack Monasca. It is a stand-alone
product that can be used to monitor generic environments according to
modern-days best practices. When combined with SUSE OpenStack Cloud, 
it is the ideal way to monitor OpenStack clouds of any size.

=== SUSE Support

Just as important as having a stable and resilient environment is to
get quick and efficient help in case something goes wrong. At SUSE, we know our tools
and products as well as the underlying Open Source technology by our
heart -- and we will be happy to help you out when in trouble. Support
from SUSE is available for all existing boxed SUSE products.

=== SUSE Training & Consulting

Knowledge is the key to building and running large-scale environments as
good as possible. From SUSE, you can get help by excellent experts
on all matters related to massively scalable environments. And to make
sure that you can run and maintain the platform that you have set up
together with our experts, you can also get training on all SUSE products
and the underlaying technology from us.

=== Get in touch!

If you are interested in SUSE products and solutions, get in touch with 
the SUSE pre-sales engineers. Together with you, they will find out how 
to help you the best possible way -- to ensure your project turns into a
ringing success.

// vim:set syntax=asciidoc:
