== SUSE and the Cloud

SUSE is a very active member of the OpenStack Community and has a long
track record of participating in the OpenStack development. 

The company also has a proven history of implementing cloud setups in 
customer organizations. From small local installations to large public 
scale-out environments and complex scenarios, SUSE consultants, support 
engineers and developers are prepared to help customers.  

In addition, SUSE provides several Linux-based products that customers 
can use to bootstrap their cloud project quickly, efficiently and reliably.

=== SUSE Linux Enterprise Server

SUSE Linux Enterprise Server is the Linux distribution tailored
specifically to the requirements of enterprise workloads. It is a 
multi-modal operating system that paves the way for IT transformation in the 
software-defined era. This modern operating system makes traditional IT 
infrastructure efficient and provides an engaging platform for developers. 
As a result, you can easily deploy and transition business-critical workloads 
across on-premise and public cloud environments.

SUSE Linux Enterprise Server shares a _common code base_ with all other products 
that are based on the SUSE Linux Enterprise platform. This means the versions, 
and thereby the source code, of all core packages of the SUSE Linux Enterprise 
product family are the same — from the desktop to the mainframe. The toolchain 
is the same across the supported hardware architectures. The common 
code base guarantees that the product and its look-and-feel is consistent. 
The latest software enhancements, bug fixes and security patches are delivered 
as regular updates via the SUSE Customer Center, so you have the newest 
functionality and the best hardware support.

=== SUSE OpenStack Cloud

SUSE OpenStack Cloud is the open source cloud solution of choice maintained 
by SUSE and designed for enterprises. It contains all standard OpenStack services 
and tools to allow for an easy installation and seamless maintenance of clouds of
any size. Thanks to SUSE's long-term experience with OpenStack technologies, it 
also comes with a generic configuration yet prepared for most use cases.

SUSE OpenStack Cloud provides a Software-Defined Infrastructure-as-a-Service 
(IaaS) for your data center. It lets you set up your own cloud environment 
in a very short time, with access to pools of IT resources to quickly deploy 
and run applications. This gives you the flexibility to respond quickly 
and easily to new demands, providing the ideal platform for increased 
innovation, while helping you to control and reduce costs.

=== SUSE OpenStack Cloud Monitoring

SUSE OpenStack Cloud Monitoring is a fully-scalable enterprise-grade solution 
that makes it simple to monitor and manage the health and performance of 
OpenStack cloud environments and workloads. It is based on the OpenStack 
project Monasca and provided as a stand-alone product. When combined with 
SUSE OpenStack Cloud, it is the ideal way to monitor OpenStack clouds of any 
size.

=== SUSE Enterprise Storage

SUSE Enterprise Storage is the Software Defined Storage offering from SUSE
based on the Ceph object store solution. It allows for the creation of
large-scale storage environments that are an ideal fit when looking for
storage in the cloud. In addition to Ceph itself, SUSE Enterprise Storage
contains several tools and helpers to allow for a seamless installation 
and effective maintenance.

=== SUSE Support

Just as important as having a stable and extensible environment is to
get quick and efficient help in case something goes wrong. At SUSE, we 
know our products, solutions and the underlying open source technology 
inside out. 

Whether you are implementing open source solutions for the first time or 
expanding your IT infrastructure to meet the needs of the digital economy,
SUSE Support is your key to success. Our holistic approach to support 
ensures that you get the most from your software solutions. Backed by 
SUSE Support means your solutions are tested, secured, and validated.
Support from SUSE is available for all SUSE products with a valid 
subscription.

=== SUSE Training & Consulting

Knowledge is the key to successfully building and running large-scale 
environments. SUSE has excellent experts on all matters related to highly 
scalable environments. And to make sure that you can smoothly run and 
maintain the platform that you have set up together with our experts, 
SUSE offers training courses for all SUSE products and their underlying 
technologies.

=== SUSE Select Services

A special, fixed-priced service offering for SUSE OpenStack Cloud and 
SUSE Enterprise Storage are the SUSE Select Services. This offering is 
designed provide SUSE customers with cost -effective and flexible 
implementation, consulting, premium support and knowledge transfer to 
jump-start the implementation of these key components of a software-defined 
infrastructure. SUSE Select Services are available in three tiers, 
giving you the flexibility to choose the level of service that best meets 
your business needs. They provide extraordinary value, built-in flexibility 
and are designed to develop a true trusted relationship with an expert 
who is dedicated to the success of your business.

=== Get in touch!

If you are interested in SUSE products and solutions, get in touch with 
the SUSE pre-sales engineers. Together with you, they will find out how 
to help you the best possible way -- to ensure your project turns into a
ringing success.

// vim:set syntax=asciidoc:
