:imagesdir: ../images/src/png/
:docinfo:
:experimental:

// Replacement entities
:kube: Kubernetes
:spr: SUSE Private Registry
:sprpbh: {spr} Powered by Harbor 2.1
:caasp: SUSE CaaS Platform
:tick: &#x2705;
:cross: &#x274C;

:toc:
:toclevels: 5

= SUSE Private Registry Powered by Harbor 2.1

== Introduction

Cloud Native Application Development and Delivery methods require a registry and a CI/CD (Continuous Integration/Delivery) instance for the development and production of container images.
In many cases, using a public container registry and CI/CD does not allow for enough control. A link:https://kubernetes.io/docs/concepts/containers/images/#using-a-private-registry[private registry] can provide that level of control.

{sprpbh} is a fully OCI compliant container image registry solution that gives the development team a place to manage, deploy and sign container images (using link:https://docs.docker.com/notary/getting_started/[Notary]), fully control the access to OCI container images and helm charts via RBAC (role-based access control), and do vulnerability scanning with link:https://github.com/aquasecurity/trivy[Trivy].
It is based on link:https://goharbor.io/docs/2.1.0/[Harbor] on top of SUSE Linux Enterprise Server.
For extensive documentation, please refer to the upstream documentation: link:https://goharbor.io/docs/2.1.0/[https://goharbor.io/docs/2.1.0/]

// // TODO TBD: list key features here
// === Key Features

See <<supported-features>> for a complete list of supported features.

== Limitations

* Once an authentication method is chosen and a user other than admin is added, the authentication method can not be changed without deploying a completely fresh registry.
* High availability and scalability are not available for the internal redis and database components. Use external database and redis services to compensate this limitation.
* Internal TLS can be enabled to secure internal connections between the {spr} components.
This doesn't currently cover the internal database and internal redis components.
* Securing connections to the external Redis with TLS/SSL is currently not supported.
* Accuracy of the Image scanning using `Trivy` might be limited.
* GPG signing for OCI artifacts is currently not supported. The only method for signing OCI artifacts is TUF (The Update Framework), provided by the `Notary` component.

// Main document body includes

include::Harbor-Private-Registry-Scenarios.adoc[Supported Deployment Scenarios]

include::Harbor-Private-Registry-Features.adoc[Supported Features]

include::Harbor-Private-Registry-Requirements.adoc[Requirements]

include::Harbor-Private-Registry-Installation.adoc[Installation]

include::Harbor-Private-Registry-Troubleshooting.adoc[Troubleshooting,leveloffset=+1]

include::Harbor-Private-Registry-Administration.adoc[Administration]

include::Harbor-Private-Registry-Userguide.adoc[User Guide]

include::Harbor-Private-Registry-Glossary.adoc[Glossary]

// Standard SUSE Best Practices includes
== Legal Notice
include::common_sbp_legal_notice.adoc[]

// Standard SUSE Best Practices includes
include::common_gfdl1.2_i.adoc[]
