:imagesdir: ../images/src/png/

:kube: Kubernetes
:spr: SUSE Private Registry
:sprpbh: {spr} Powered by Harbor 2.1
:caasp: SUSE CaaS Platform
:tick: &#x2705;
:cross: &#x274C;

:toc:
:toclevels: 5

= SUSE Private Registry Powered by Harbor 2.1

== Highlights

Cloud Native Application Development and Delivery methods require a registry and a CI/CD (Continuous Integration/Delivery) instance for the development and production of container images.
In many cases, using a public container registry and CI/CD does not allow for enough control.
The {sprpbh} solution gives the development team a place to manage and deploy container images and build artifacts, fully control the access, and do vulnerability scanning.

{sprpbh} is a fully OCI compliant container image registry solution.
It is based on Harbor on top of SUSE Linux Enterprise Server. It includes a Harbor based UI that allows users to configure storage and replication and provides fine grained access control with RBAC (role-based access control) on both OCI container images and Helm charts, container signing and vulnerability scanning.
For extensive documentation, please refer to the upstream documentation: link:https://goharbor.io/docs/2.1.0/[https://goharbor.io/docs/2.1.0/]

=== Key Features

// TODO
TBD: list key features here

See <<supported-features>> for a complete list of supported features.

include::Harbor-Private-Registry-Requirements.adoc[Requirements]

include::Harbor-Private-Registry-Installation.adoc[Installation]

include::Harbor-Private-Registry-Troubleshooting.adoc[Troubleshooting,leveloffset=+1]

include::Harbor-Private-Registry-Administration.adoc[Administration]

include::Harbor-Private-Registry-Deployments.adoc[Supported Deployments]

include::Harbor-Private-Registry-Features.adoc[Supported Features]

include::Harbor-Private-Registry-Userguide.adoc[User Guide]
