== Supported Deployment Scenarios

For an exhaustive list of Helm chart deployment options, please consult the documentation included in the helm chart, by running e.g.:

[source,bash]
----
export HELM_EXPERIMENTAL_OCI=1
# download the chart from public registry
helm chart pull registry.suse.com/harbor/harbor:1.5
# export the chart to local directory
helm chart export registry.suse.com/harbor/harbor:1.5
# show the chart information
helm show readme harbor
----

The following table lists the Helm chart deployment options officially supported by the SUSE Private Registry 2.1 release.

[#supported-deployment]
.Supported deployment options
[options="header,autowidth"]
|===
^|Deployment Option ^|Values Supported by Harbor ^|Supported by SUSE Private Registry ? ^|Description

|Deployment tool
|Helm chart (helm v3)
^|{tick}
|

.4+|K8s distribution
|SUSE CaaS Platform v4.2
^|{cross}
.4+|Supported Kubernetes distributions on top of which the registry can be deployed as a helm chart.

|SUSE CaaS Platform v4.5
^|{tick}

|AKS (Azure K8s Services)
^|{tick}

|EKS (Amazon)
^|{tick}

.3+|Registry Image / Chart Storage Backend
|Filesystem
^|{tick}
.3+|Back-ends supported for storing registry objects such as container images and helm charts.

|Azure Blob Storage
^|{tick}

|AWS/S3
^|{tick}

.4+|Frontend
|Ingress
^|{tick}
.4+|Options available for exposing the Harbor public APIs (UI, harbor core API and notary API).

|LoadBalancer
^|{tick}

|NodePort
^|{cross}

|ClusterIP
^|{cross}

.3+|Ingress controllers
|SUSE NGINX Ingress Controller (SUSE CaaS Platform v4.5)
^|{tick}
.3+|Ingress controllers for providing ingresses to expose services.

|link:https://github.com/kubernetes/ingress-nginx[Kubernetes ingress nginx] (AKS, EKS)
^|{tick}

|link:https://docs.aws.amazon.com/eks/latest/userguide/alb-ingress.html[EKS ALB]
^|{tick}

.2+|TLS
|External TLS
^|{tick}
.2+|TLS can be enabled for securing the connection between the harbor services (internal) as well as between its consumers (external). The certificates can be generated by the helm chart or provided in advance.

|Internal TLS
^|{tick}

.2+|Database service
|Builtin
^|{tick}
.2+|Database used by Harbor. Can be deployed internally by the Harbor helm chart or can be configured to consume an external database.

|External
^|{tick}

.2+|External database service
|Amazon RDS/PostgreSQL
^|{tick}
.2+|Managed postgresql database services that can be configured as an external database service for Harbor.

|Azure Database for PostgreSQL
^|{tick}

.2+|Redis service
|Builtin
^|{tick}
.2+|In-memory cache used by Harbor. Can be deployed internally by the Harbor helm chart or can be configured to consume an external redis service.

|External
^|{tick}

.3+|External redis service
|Amazon ElastiCache for Redis
^|{tick}
.3+|Managed redis cache services that can be configured as an external redis service for Harbor.

|Azure Cache for Redis
^|{tick}

|SUSE redis-ha operator
^|{tick}

.2+|Persistent Block Storage
|Enabled
^|{tick}
.2+a|
Persistent storage can be enabled/disabled for the harbor stateful services:

* Database (internal)
* Redis (internal)
* Registry (when using the filesystem backend)
* Jobservice
* Trivy

The registry can be deployed without persistent storage, e.g. for evaluation purposes, but this deployment option is not supported.

|Disabled
^|{cross}

.5+|Persistent Block Storage Backends
|Azure Managed Disks (RWO)
^|{tick}
.5+a|
Kubernetes storage backend used to provide persistent storage support.

[NOTE]
====
A Kubernetes storage class with RWM (`ReadWriteMany`) capabilities is required to deploy SUSE Private Registry in full HA mode.
Alternatively, a storage class with RWO (`ReadWriteOnce`) capabilities can be used to deploy the SUSE Private Registry with partial HA.
Refer to <<high-availability>> for more details.
====

&#x2020; for Kubernetes storage classes supported for SUSE CaaS Platform v4.5, consult the relevant documentation at: https://documentation.suse.com/suse-caasp/4.5/html/caasp-admin/_storage.html

|Azure Files (RWM)
^|{tick}
|Amazon EBS (RWO)
^|{tick}
|Amazon EFS (RWM)
^|{tick}
|SUSE CaaS Platform v4.5 supported storage backends &#x2020;
^|{tick}


.2+|Update Strategy
|RollingUpdate
^|{tick}
.2+a|
Registry configuration update and upgrade strategy, delivered via Helm:

* `RollingUpdate`: Ensures overall minimal service downtime during a `helm upgrade` operation by activating the rolling update feature for all registry components that support it.
This requires a {kube} storage class with RWM (`ReadWriteMany`) support to be used for registry services that need shared persistent storage (jobservice and docker-registry).
* `Recreate`: Use this strategy when a {kube} storage class with RWM (`ReadWriteMany`) support isn't available.
It selectively disables the rolling update feature for registry components that need shared persistent storage (jobservice and docker-registry), resulting in increased service downtime during configuration update and upgrade operations.

IMPORTANT: The possibility to use `RollingUpdate` strategy depends on the Persistent Volume configuration.
If the persistent volumes do not support ReadWriteMany access, using the `RollingUpdate` strategy will result in failure.

|Recreate
^|{tick}

.2+|Proxy
|Disabled
^|{tick}
.2+|A proxy can be configured for replicating artifacts from/to the registries that cannot be reached directly

|Enabled
^|{cross}

.4+|High Availability for Stateless components
|portal
^|{tick}
.9+a|
To achieve true HA, the number of replicas for each component needs to be set to 2 or more.
This can easily be done for stateless components, however for some stateful components (jobservice and docker-registry), a persistent block storage backend that supports the `ReadWriteMany` access mode is needed to provide shared persistent storage.

[NOTE]
====
HA for the internal database and internal redis is not supported by Harbor.
External database and redis services with HA support should be use to complement the HA features supported for the other components.
====

|core
^|{tick}

|nginx
^|{tick}

|notary
^|{tick}

.5+|High Availability for Stateful components
|docker-registry
^|{tick}

|jobservice
^|{tick}

|trivy
^|{tick}

|internal database
^|{cross}

|internal redis
^|{cross}
|===
