:pg: PostgreSQL
:cnpg: CloudNativePG
:cnpg_ns: cnpg-system
:pg_db_name: edgedb
:cnpg_app_name: cloudnative-pg
:cnpg_url: https://apps.rancher.io/applications/cloudnative-pg
:rac: Rancher Application Collection



IMPORTANT::
SUSE does *not* offer 3rd level database support for {pg} or {cnpg} on Kubernetes.
Find information about support options at link:https://www.postgresql.org/support/[The PostgreSQL Global Development Group].


IMPORTANT::
The instructions below describe only one variant of installing a {pg} database with the {cnpg} operator.
There are other possible ways to set up {pg} which aren't covered in this guide, but It is also possible to install {pg} as a single instance on the operating system.
We will focus on installing {pg} via the {cnpg} operator in a Kubernetes cluster. If you want to use the {cnpg} operator you need the Rancher Prime for SAP applications subscription or Rancher Prime Suite. For more information please visit link:https://docs.apps.rancher.io/get-started/subscriptions

== Deploying {pg} via {cnpg}
Even though is available for deployment using the {rancher} Apps, we recommend using the {rac}.
The {cnpg} chart can be found at {cnpg_url}.

== Creating secret for {cnpg}
First, create a namespace and the *imagePullSecret* for installing the {cnpg} operator into the cluster.
[source, bash, subs="attributes"]
----
kubectl create namespace {cnpg_ns}
----

[#pgIPS]
How to create the *imagePullSecret* is described in <<imagePullSecret>>.

=== Installing the {cnpg} operator
After creating the secret, we can install the operator via Helm.

[source, bash, subs="attributes"]
----
helm install {cnpg_app_name} oci://dp.apps.rancher.io/charts/{cnpg_app_name} --namespace={cnpg_ns} --set global.imagePullSecrets=\{application-collection\}
----

=== Create PostgreSQL database

First, we need to create the namespace into which the database will be deployed.
[source, bash, subs="attributes"]
----
kubectl create namespace {pg_db_name}
----

==== Creating secret for database user
When creating the database, we need two secrets that contain the username and password for both the application user and the superuser, postgres.
Create the yaml file create_user_secret.yaml

[source, yaml]
----
apiVersion: v1
kind: Secret
metadata:
  name: cluster-pg-superuser
  namespace: {pg_db_name}
type: kubernetes.io/basic-auth
stringData:
  username: postgres
  password: <<password>>
---
apiVersion: v1
kind: Secret
metadata:
  name: cluster-pg-appuser
  namespace: {pg_db_name}
  annotations:
  labels:
type: kubernetes.io/basic-auth
stringData:
  username: appuser
  password: <<password>>
----

Apply the secrets to your cluster.
[source, bash, subs="attributes"]
----
kubectl apply -f create_user_secret.yaml
----


==== Creating secret with certificates
Create the Kubernetes secret with the certificates. Find an example how to do this in <<selfSignedCertificates>>. In our example we use cert-manager to handle the certificates.
you need to add the DNS names of the cluster into the certificates. 
Create the *edgedb-certificate.yaml* file.
[source, yaml]
----
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: my-edgedb-server-cert
  namespace: edgedb
spec:
  # This is the Secret that cert-manager will create and CNPG will read
  secretName: my-edgedb-server-cert
  secretTemplate:
    labels:
      # CRITICAL: This label tells the CloudNativePG operator to 
      # automatically reload the database when this cert renews.
      cnpg.io/reload: "" 
  usages:
    - server auth
    - digital signature
  dnsNames:
    - edgedb.local
    - edgedb-rw
    - edgedb.default
    - edgedb-rw.default.svc
    - edgedb-ro
    - edgedb-ro.default
    - edgedb-ro.default.svc
    - edgedb-r
    - edgedb-r.default
    - edgedb-r.default.svc
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: my-ca-issuer
----

Put that content into your file it and add it to your cluster.

[source, bash, subs="attributes"]
----
kubectl apply -f edgedb-certificate.yaml
----


=== Creating the database
[#pgLIR]
Before you can create the application, you need to log in to the registry. Find the instructions in <<LoginApplicationCollection>>.

Create a file *postgres-values.yaml* which holds the configuration for the postgres cluster database.
The configuration might look like:

[source, yaml]
----
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres
  namespace: db
spec:
  instances: 3

  superuserSecret:
    name: cluster-pg-superuser

  bootstrap:
    initdb:
      database: {pg_db_name} # The name of the application database to create
      owner: appuser     # The username (must match the 'username' key in the secret)
      secret:
        name: cluster-pg-appuser

  # Configure CNPG to use the cert-manager secrets (from previous steps)
  certificates:
    serverTLSSecret: my-edgedb-server-cert
    serverCASecret: my-edgedb-server-cert
    replicationTLSSecret: my-edgedb-client-cert
    clientCASecret: my-edgedb-client-cert

  storage:
    size: 50Gi
----

Let the operator start to create the database.
[source, bash, subs="attributes"]
----
kubectl apply -f postgres-values.yaml
----

You can check the status via Rancher Prime or with kubectl.

[source, bash, subs="attributes"]
----
kubectl get clusters.postgresql.cnpg.io -A
NAMESPACE   NAME       AGE   INSTANCES   READY   STATUS                     PRIMARY
edgedb      edgedb     10d   3           3       Cluster in healthy state   edgedb-1
----
