=== Installation and Configuration of {metallb}

There are multiple ways to install the {metallb} software. In this guide we'll cover how to install {metallb} using kubectl or Helm.
A complete overview and more details about {metallb} can be found on their 
link:https://metallb.universe.tf/[official website]

==== Pre-requisites

Before starting the installation, make sure you meet all the requirements. In particular, you should pay attention to network addon compatibility.
If you are trying to run {metallb} on a cloud platform, you should also look at the cloud compatibility page and make sure your cloud platform can work with {metallb} (most cannot).
There are three supported ways to install {metallb}:

* using plain Kubernetes manifests
* using Kustomize
* using Helm

The preferred method should be by using Helm.
Please make sure to have a range of IP addresses available for configuring {metallb}.


++++
<?pdfpagebreak?>
++++

==== Preparations


On your RKE2 cluster edit the kube-proxy configmap:
----
# kubectl edit configmap -n kube-system kube-proxy
----

set ipvs strictarp to true:
----
apiVersion: kubeproxy.config.k8s.io/v1alpha1
kind: KubeProxyConfiguration
mode: "ipvs"
ipvs:
  strictARP: true
----

==== Installation of {metallb}

===== Install {metallb} by manifest

----
# kubectl apply -f https://raw.githubusercontent.com/metallb/metallb/v0.14.4/config/manifests/metallb-native.yaml
----

===== Or install {metallb} via Helm chart

----
helm repo add metallb https://metallb.github.io/metallb
helm repo update
helm install metallb metallb/metallb
----

++++
<?pdfpagebreak?>
++++

=== Configuration

{metallb} needs two configurations to function properly:

- IP address pool
- L2 advertisement configuration

Create the configuration files for the {metallb} IP address pool:

----
# cat <EOF>>iprange.yaml
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: first-example-pool
  namespace: metallb-system
spec:
  addresses:
  - 192.168.1.240-192.168.1.250
EOF
----

and the layer 2 network advertisement:

----
# cat <EOF>> l2advertisement.yaml
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: example
  namespace: metallb-system
EOF
----

Apply the configuration:

----
# kubectl apply -f iprange.yaml
# kubectl apply -f l2advertisement.yaml
----
