[#Redis]

:redis: Redis


IMPORTANT::
SUSE does not offer database support for {redis}.
For support requests contact link:https://redis.com/[Redis Ltd.].


IMPORTANT::
The following instructions describe only one variant of installing {redis} which is called Redis Cluster.
There are other possible ways to set up {redis} that are not covered in this guide.
Check if you require link:https://redis.io/docs/management/sentinel/[{redis} Sentinel]
instead of link:https://redis.io/docs/management/scaling/[{redis} Cluster].


== Deploying Redis

Although {redis} is available for deployment using the {rancher} Apps, we recommend using the {rac}.
The {redis} chart can be found at https://apps.rancher.io/applications/redis .

++++
<?pdfpagebreak?>
++++


=== Deploying the chart

To deploy the chart, create the related namespace and *imagePullSecret* first.
To create the namespace, run:

[source, bash]
----
$ kubectl create namespace redis
----

[#redisIPS]
Instructions how to create the *imagePullSecret* can be found in xref:SAP-EIC-ImagePullSecrets.adoc#imagePullSecret[]


If you want to use self-signed certificates, you can find instructions how to create such in xref:SAP-EIC-Main.adoc#selfSignedCertificates[]

[#redisLIR]
Before you can install the application, you need to log in to the registry. You can find the instruction in xref:SAP-EIC-LoginRegistryApplicationCollection.adoc#LoginApplicationCollection[]


Create a file *values.yaml* which holds some configurations for the {redis} Helm chart.
The configuration may look like:

[source, yaml]
----
images:
  redis:
    # -- Image name to use for the Redis container
    repository: dp.apps.rancher.io/containers/redis
    # -- Image tag to use for the Redis container
    tag: 7.2.5
storageClassName: "longhorn"
global:
  imagePullSecrets: ["application-collection"]
architecture: cluster
nodeCount: 3
auth:
  password: <redisPW>
tls:
  # -- Enable TLS
  enabled: true
  # -- Whether to require Redis clients to authenticate with a valid certificate (authenticated against the trusted root CA certificate)
  authClients: false
  # -- Name of the secret containing the Redis certificates
  existingSecret: "redisCert"
  # -- Certificate filename in the secret
  certFilename: "server.pem"
  # -- Certificate key filename in the secret
  keyFilename: "server.key"
  #  CA certificate filename in the secret - needs to hold the CA.crt and the server.pem
  caCertFilename: "root.pem"
----

To install the application, run:
[source, bash]
----
$ helm install redis oci://dp.apps.rancher.io/charts/redis \
-f values.yaml \
--namespace=redis
--version  
----
