[#SLEMicro]

=== Installation

On each server in your environment for {eic} and {rancher}, install {slem} {slem_version} as the operating system.
The manual installation is described in the {slem} {slem_version} Deployment Guide in our Documentation https://documentation.suse.com/sle-micro/{slem_version}/single-html/SLE-Micro-deployment/#cha-install[SLE Micro Deployment Guide]. 

At the end of the installation process in the summary windows you need to check if these Security Settings are configured:

   ** The firewall will be disabled.
   ** The SSH service will be enabled.
   ** SELinux will be set in permissive mode.

We need to set SELinux into permissive mode, because some components of the Edge Integration Cell violated SELinux rules and the application will not work. 


TIP: If you have already set up all machines and the operating system, 
skip this chapter.

=== Register your system
To bring your system up to date you need to register your system against a SUSE Manager, RMT server or direct to the SCC Portal. We will describe the process in our guide with the direct connect to the SCC. For more information please look into the {slem} documentation.

Registering the system is possible from the command line using the *transactional-update register* command. For information that goes beyond the scope of this section, refer to the inline documentation with *SUSEConnect --help*. To register {slem} with SUSE Customer Center, run *transactional-update register* as follows:
[source, bash]
----
$ transactional-update register -r REGISTRATION_CODE -e EMAIL_ADDRESS
----
To register with a local registration server, additionally provide the URL to the server:

[source, bash]
----
$ transactional-update register -r REGISTRATION_CODE -e EMAIL_ADDRESS \
--url "https://suse_register.example.com/"
----
Replace *REGISTRATION_CODE* with the registration code you received with your copy of {slem}. Replace *EMAIL_ADDRESS* with the e-mail address associated with the SUSE account you or your organization uses to manage subscriptions.
. Reboot your system to switch to the latest snapshot.
. {slem} is now registered.
You can found more information in the {slem} {slem_version} link:https://documentation.suse.com/sle-micro/{slem_version}/single-html/SLE-Micro-deployment/[Deployment Guide] . 

=== Update your system
Login into the system and after your system is registered you can update it with the *transactional-update* command.
[source, bash]
----
$ transactional-update
----

=== Disable automatic reboot
Per default {slem} runs a timer for *transactional-update* in the background which could automatic reboot your system. We will disable it.

[source, bash]
----
$ systemctl --now disable transactional-update.timer
----

++++
<?pdfpagebreak?>
++++

=== Preparation for {lh}
For {lh} we need to do some preparation steps. First we need to install addional packages on all worker nodes. Then we will attach a second disk to the worker nodes, create a filesystem ontop of it and mount it to the longhorn default location. The size of the second disk depends on your use case. 

We need to install some packages as a requirement for longhorn and Logical Volume Management for adding a filesystem to longhorn.
[source, bash]
----
$ transactional-update pkg install lvm2 jq nfs-client cryptsetup open-iscsi
----

After the needed packages are installed you need to reboot your machine. 
[source, bash]
----
$ reboot
----

Now we can you enable the iscsid server.

[source, bash]
----
$ systemctl enable iscsid  --now
----

++++
<?pdfpagebreak?>
++++

==== Create filesystem for longhorn
Then we will create with the Logical Volume Management a new logical volume. 

First we want to create a new physical volume. In our case the second disk is called vdb and we use this as longhorn volume.
[source, bash]
----
$ pvcreate /dev/vdb
----

After the physical volume is created we create a volume group called vgdata
[source, bash]
----
$ vgcreate vgdata /dev/vdb
----

Now we cann create the logical volume and we will use 100% of the disk. 
[source, bash]
----
$ lvcreate -n lvlonghorn -l100%FREE vgdata
----

We will create the XFS filesystem on the logical volume. You don't need to create a partion on top of it.
[source, bash]
----
$ mkfs.xfs /dev/vgdata/lvlonghorn
----

Before we can mount the device we need to create the directory structure.
[source, bash]
----
$ mkdir -p /var/lib/longhorn
----

That the mount of the filesystem is persistent we add an entry into the fstab
[source, bash]
----
$ echo -e "/dev/vgdata/lvlonghorn /var/lib/longhorn xfs defaults 0 0" >> /etc/fstab
----

Now we can mount the filesystem
[source, bash]
----
$ mount -a
----

