==== Installing and configuring {metallb}

There are multiple ways to install the {metallb} software. In this guide, we will cover how to install {metallb} using `kubectl` or Helm.
A complete overview and more details about {metallb} can be found on the 
link:https://metallb.universe.tf/[official website for {metallb}]

===== Prerequisites

Before starting the installation, ensure that all requirements are met. In particular, you should pay attention to network addon compatibility.
If you are trying to run {metallb} on a cloud platform, you should also look at the cloud compatibility page and make sure your cloud platform works with {metallb} (note that most cloud platforms do *not*).

There are several ways to deploy {metallb}. In this guide, we will describe how to use the {rac} to deploy {metallb}.

Make sure to have a range of IP addresses available for configuring {metallb}.

===== Preparation

Ensure that the associated kernel modules are loaded on your Kubernetes worker nodes as described in xref:SAP-EIC-SLEMicro#metal-slem[].

Make sure you enabled `strictarp` as described in xref:SAP-Rancher-RKE2-Installation.adoc#metal-rke[]


===== Installing {metallb}

To install {metallb} run the following lines in your terminal:

----
$ helm pull oci://dp.apps.rancher.io/charts/metallb --untar
$ helm install --namespace=metallb --set-json 'imagePullSecrets=[{"name":"application-collection"}]' --create-namespace metallb ./metallb
----

++++
<?pdfpagebreak?>
++++

==== Configuring {metallb}

{metallb} needs two configurations to function properly:

- IP address pool
- L2 advertisement configuration

Create the configuration files for the {metallb} IP address pool:

----
# cat <<EOF >iprange.yaml
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: first-example-pool
  namespace: metallb
spec:
  addresses:
  - 192.168.1.240-192.168.1.250
EOF
----

Create the layer 2 network advertisement:

----
# cat <<EOF > l2advertisement.yaml
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: example
  namespace: metallb
EOF
----

Apply the configuration:

----
# kubectl apply -f iprange.yaml
# kubectl apply -f l2advertisement.yaml
----
