This chapter is to guide you through the installation and configuration of MetalLB on your K8s cluster used for the SAP EIC.

=== Installation and Configuration of MetalLB loadbalancer

There are multiple ways to install the MetalLB software:

- with kubectl using the manifest
- with helm and the helmchart provided in the Metallb repositories.

==== Pre-requisites

Before starting with installation, make sure you meet all the requirements. In particular, you should pay attention to network addon compatibility.
If you are trying to run MetalLB on a cloud platform, you should also look at the cloud compatibility page and make sure your cloud platform can work with MetalLB (most cannot).
There are three supported ways to install MetalLB: using plain Kubernetes manifests, using Kustomize, or using Helm.
The preferred method should be by using helm.
Please make sure to have a range of ip addresses available for configuring the Metallb loadbalancer.

==== Preparations


On your rke2 cluster edit the kube-proxy configmap:
----
# kubectl edit configmap -n kube-system kube-proxy
----

set ipvs strictarp to true:
----
apiVersion: kubeproxy.config.k8s.io/v1alpha1
kind: KubeProxyConfiguration
mode: "ipvs"
ipvs:
  strictARP: true
----

==== Installation of MetalLB

===== Install Metallb by manifest

----
# kubectl apply -f https://raw.githubusercontent.com/metallb/metallb/v0.14.4/config/manifests/metallb-native.yaml
----

===== Or install Metallb via Helm chart

----
helm repo add metallb https://metallb.github.io/metallb
hwlm repo update
helm install metallb metallb/metallb
----

=== Configuration

Metallb needs two configurations to function properly:

- ip address pool
- l2 advertisment configuration

Create the configuration files for the MetalLB IP address pool:


----
# cat <EOF>>iprange.yaml
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: first-example-pool
  namespace: metallb-system
spec:
  addresses:
  - 192.168.1.240-192.168.1.250
EOF
----

and the layer 2 network advertisement:

----
# cat <EOF>> l2advertisment.yaml
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: example
  namespace: metallb-system
EOF
----

Apply the configuration:

----
# kubectl apply -f iprange.yaml
# kubectl apply -f l2advertisment.yaml
----


=== Test

Finally test the Metallb deployment and configuration by creating a service of type LoadBalancer:
E.g.:

____
Test example here ...
____

=== Conclusion


=== Resources

link: https://metallb.universe.tf/
