:postgres: PostgreSQL
:pg: CloudNativePG
:redis: Redis


IMPORTANT::
SUSE does not offer database support for {postgres}.
To get support, turn to 
link:https://www.postgresql.org/support/ [The PostgreSQL Global Development Group]


IMPORTANT::
In this guide we'll describe one variant of installing {postgres}.
There are other possible ways to setup {postgres} which are not focussed in this guide. It is also possible to install {postgres} as a single instance on top of the operation system.
We will focus on installing {postgres} into a kubernetes cluster, because we also need a {redis} database and we will put them together into one cluster. 

=== Deploying {postgres}
In our scenario we will use the {pg} Operator to deploy the {postgres} database via Helm Chart.  

==== Adding Helm Chart Repository
First we need to add the helm chart repository for the {pg} Operator.
----
$ helm repo add cnpg http://cloudnative-pg.github.io/charts
----

==== Deploy {pg} Operator
We will deploy the {pg} Operator Helm Chart with the defaults vaules.
----
helm upgrade --install cnpg --namespace cnpg-system --create-namespace cnpg/cloudnative-pg
----

==== Deply {postgres} Database
After the Helm Chart is deployed we can start to create the database. But first we need to create a values.yaml file to confige some settings. 

----
helm upgrade --install cnpg --namespace cnpg-database --create-namespace --values.yaml cnpg/cluster
----