== Installation and Configuration of {metallb}

There are multiple ways to install the {metallb} software. In this guide we'll cover how to install {metallb} using kubectl or Helm.
A complete overview and more details about {metallb} can be found on their 
link:https://metallb.universe.tf/[official website]

=== Pre-requisites

Before starting the installation, make sure you meet all the requirements. In particular, you should pay attention to network addon compatibility.
If you are trying to run {metallb} on a cloud platform, you should also look at the cloud compatibility page and make sure your cloud platform can work with {metallb} (most cannot).

There are several ways to deploy {metallb}. In this guide we'll describe how to use the {rac} to deploy {metallb}.

Please make sure to have a range of IP addresses available for configuring {metallb}.

Before you can deploy {metallb} from {rac}, you need to create the namespace and an ImagePullSecret.
To create the related namespace, run:
----
$ kubectl create namespace metallb
----

[#metalIBS]
Instructions how to create the *imagePullSecret* can be found in xref:SAP-EIC-ImagePullSecrets.adoc#imagePullSecret[]

=== Installation of {metallb}

To install {metallb} run the following lines in your terminal:

----
$ helm pull oci://dp.apps.rancher.io/charts/metallb --version=0.14.7 --untar
$ helm install --namespace=metallb --set-json 'imagePullSecrets=[{"name":"application-collection"}]' --create-namespace metallb ./metallb
----

++++
<?pdfpagebreak?>
++++

== Configuration

{metallb} needs two configurations to function properly:

- IP address pool
- L2 advertisement configuration

Create the configuration files for the {metallb} IP address pool:

----
# cat <<EOF >iprange.yaml
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: first-example-pool
  namespace: metallb
spec:
  addresses:
  - 192.168.1.240-192.168.1.250
EOF
----

and the layer 2 network advertisement:

----
# cat <<EOF > l2advertisement.yaml
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: example
  namespace: metallb
EOF
----

Apply the configuration:

----
# kubectl apply -f iprange.yaml
# kubectl apply -f l2advertisement.yaml
----
