:pg: PostgreSQL
:redis: Redis

In the instructions below, we only describe one variant of installing {pg}.
There are other possible ways to set up {pg} which are not covered in this guide. It is also possible 
to install {pg} as a single instance on the operating system.
We will focus on installing {pg} in a Kubernetes cluster as we also need a {redis} database and we will clustering that together. 

IMPORTANT::
SUSE does *not* offer database support for {pg} on Kubernetes.
To get support, go to link:https://www.postgresql.org/support/[The PostgreSQL Global Development Group].


==== Deploying {pg}
Although {pg} is available for deployment using the {rancher} Apps, we recommend using the {rac}.
The {pg} chart can be found at https://apps.rancher.io/applications/postgresql.

==== Creating the Secret for {rac}
First, create a namespace and the *imagePullSecret* for installing the {pg} database in the cluster.
----
kubectl create namespace postgresql
----

How to create the *imagePullSecret* is described in section xref:SAP-EIC-Main.adoc#imagePullSecret[].

===== Creating the Secret with certificates
Next, create the Kubernetes Secret with the certificates. You can find an example of the procedure in xref:SAP-EIC-Main.adoc#Appendix[].

===== Installing the application

Log in to the {rac}. This can be done as follows:
----
$ helm registry login dp.apps.rancher.io/charts -u <yourUser> -p <your-token>
----

Create a configuration file _values.yaml_ that holds some configurations for the {pg} Helm chart.
The configuration could look like this:
----
global:
  # -- Global override for container image registry pull secrets
  imagePullSecrets: ["application-collection"]
images:
  postgresql:
    # -- Image name to use for the PostgreSQL container
    repository: dp.apps.rancher.io/containers/postgresql
    # -- Image tag to use for the PostgreSQL container
    tag: "15.7"
auth:
  # -- PostgreSQL username for the superuser
  postgresUsername: postgres
  # -- PostgreSQL password for the superuser
  postgresPassword: "<your_password>"
  # -- Replication username
  replicationUsername: replication
  # -- Replication password
  replicationPassword: "<your_password>"
tls:
  # -- Enable SSL/TLS
  enabled: false
  # -- Name of the secret containing the PostgreSQL certificates
  existingSecret: "postgresqlcert"
  # -- Whether or with what priority a secure SSL TCP/IP connection will be negotiated with the server. Valid values: prefer (default), disable, allow, require, verify-ca, verify-full
  sslMode: "verify-full"
  # -- Certificate filename in the secret (will be ignored if empty)
  certFilename: "server.pem"
  # -- Certificate key filename in the secret (will be ignored if empty)
  keyFilename: "server.key"
  # -- CA certificate filename in the secret (will be ignored if empty)
  caCertFilename: "root.pem"
persistentVolumeClaimRetentionPolicy:
  whenDeleted: Delete
----

++++
<?pdfpagebreak?>
++++

To install the application run:
----
$ helm pull oci://dp.apps.rancher.io/charts/postgres --untar
$ helm install -f values.yaml --namespace=postgresql ./postgresql
----


