== Installing and configuring of {metallb}

There are multiple ways to install the {metallb} software. In this guide, we will cover how to install {metallb} using `kubectl` or Helm.
A complete overview and more details about {metallb} can be found on the 
link:https://metallb.universe.tf/[official website for {metallb}].

=== Prerequisites

Before starting the installation, ensure that all requirements are met. In particular, you should pay attention to network addon compatibility.
If you are trying to run {metallb} on a cloud platform, you should also look at the cloud compatibility page and make sure your cloud platform works with {metallb} (note that most cloud platforms do *not*).

There are several ways to deploy {metallb}. In this guide, we will describe how to use the {rac} to deploy {metallb}.

Make sure to have one IP address available for configuring {metallb}.

Before you can deploy {metallb} from {rac}, you need to create the namespace and an ImagePullSecret.
To create the related namespace, run:
----
$ kubectl create namespace metallb
----

[#metalIPS]
Instructions how to create the *imagePullSecret* can be found in <<imagePullSecret>>.

++++
<?pdfpagebreak?>
++++

=== Installation of {metallb}

[#metalLIR]
Before you can install the application, you need to login into the registry. You can find the instruction in <<LoginApplicationCollection>>.

Create a values.yaml file with the following configuration:

[source,yaml]
----
imagePullSecrets:
  - name: application-collection
----

Then install the metallb application.
[source, bash]
----
$ helm install metallb oci://dp.apps.rancher.io/charts/metallb \
-f values.yaml \
--namespace=metallb \
--version 0.14.7
----

++++
<?pdfpagebreak?>
++++

== Configuring {metallb}

{metallb} needs two configurations to function properly:

- IP address pool
- L2 advertisement configuration

Create the configuration files for the {metallb} IP address pool:
[source,bash]
----
$ cat <<EOF >iprange.yaml
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: first-example-pool
  namespace: metallb
spec:
  addresses:
  - 192.168.1.240/32
EOF
----

and the layer 2 network advertisement:
[source,bash]
----
$ cat <<EOF > l2advertisement.yaml
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: example
  namespace: metallb
EOF
----

Apply the configuration:

[source,bash]
----
$ kubectl apply -f iprange.yaml
$ kubectl apply -f l2advertisement.yaml
----
