:pg: PostgreSQL
:pg_app_name: postgresql
:redis: Redis


IMPORTANT::
SUSE does *not* offer database support for {pg} on Kubernetes.
Find information about support options at link:https://www.postgresql.org/support/[The PostgreSQL Global Development Group].


IMPORTANT::
The instructions below describe only one variant of installing {pg}.
There are other possible ways to set up {pg} which are not covered in this guide. 
It is also possible to install {pg} as a single instance on the operating system.
We will focus on installing {pg} in a Kubernetes cluster, as we also need a {redis} database, and we will clustering that together.

== Deploying {pg}
Even though {pg} is available for deployment using the {rancher} Apps, we recommend to use the {rac}.
The {pg} chart can be found at https://apps.rancher.io/applications/postgresql.

== Creating secret for {rac}
First, create a namespace and the *imagePullSecret* for installing the {pg} database onto the cluster.
[source, bash, subs="attributes"]
----
kubectl create namespace {pg_app_name}
----

[#pgIPS]
How to create the *imagePullSecret* is described in <<imagePullSecret>>.

=== Creating secret with certificates
Second, create the Kubernetes secret with the certificates. You will find an example how to do this in <<selfSignedCertificates>>.

=== Installing the application
[#pgLIR]
Before you can install the application, you need to log in to the registry. You can find the instruction in <<LoginApplicationCollection>>.

Create a file *values.yaml* which holds some configurations for the {pg} Helm chart.
The configuration may look like:
[source, yaml]
----
global:
  # -- Global override for container image registry pull secrets
  imagePullSecrets: ["application-collection"]
images:
  postgresql:
    # -- Image registry to use for the PostgreSQL container
    registry: dp.apps.rancher.io
    # -- Image repository to use for the PostgreSQL container
    repository: containers/postgresql
    # -- Image tag to use for the PostgreSQL container
    tag: "15.7"
auth:
  # -- PostgreSQL username for the superuser
  postgresUsername: postgres
  # -- PostgreSQL password for the superuser
  postgresPassword: "<your_password>"
  # -- Replication username
  replicationUsername: replication
  # -- Replication password
  replicationPassword: "<your_password>"
tls:
  # -- Enable SSL/TLS
  enabled: false
  # -- Name of the secret containing the PostgreSQL certificates
  existingSecret: "postgresqlcert"
  # -- Whether or with what priority a secure SSL TCP/IP connection will be negotiated with the server. Valid values: prefer (default), disable, allow, require, verify-ca, verify-full
  sslMode: "verify-full"
  # -- Certificate filename in the secret (will be ignored if empty)
  certFilename: "server.pem"
  # -- Certificate key filename in the secret (will be ignored if empty)
  keyFilename: "server.key"
  # -- CA certificate filename in the secret (will be ignored if empty)
  caCertFilename: "root.pem"
statefulset:
  # -- Enable the StatefulSet template for PostgreSQL standalone mode
  enabled: true
  # -- Lifecycle of the persistent volume claims created from PostgreSQL volumeClaimTemplates
  persistentVolumeClaimRetentionPolicy:
    ## -- Volume behavior when the StatefulSet is deleted
    whenDeleted: Delete
podSecurityContext:
  # -- Enable pod security context
  enabled: true
  # -- Group ID for the pod
  fsGroup: 1000
----

To install the application, run:
[source, bash, subs="attributes"]
----
helm install {pg_app_name} oci://dp.apps.rancher.io/charts/{pg_app_name} -f values.yaml --namespace={pg_app_name}
----


