==== Installation and Configuration of {metallb}

There are multiple ways to install the {metallb} software. In this guide we'll cover how to install {metallb} using kubectl or Helm.
A complete overview and more details about {metallb} can be found on their 
link:https://metallb.universe.tf/[official website]

===== Pre-requisites

Before starting the installation, make sure you meet all the requirements. In particular, you should pay attention to network addon compatibility.
If you are trying to run {metallb} on a cloud platform, you should also look at the cloud compatibility page and make sure your cloud platform can work with {metallb} (most cannot).

There are several ways to deploy {metallb}. In this guide we'll describe how to use the {rac} to deploy {metallb}.

Please make sure to have a range of IP addresses available for configuring {metallb}.

===== Preparations

// 
//
// See github issue: https://github.com/rancher/rke2/issues/3710
//

First make sure that the kernel modules for ip_vs are loaded correctly at boot time:

Create on each cluster node the file 

----
sudo vi /etc/modules-load.d/ip_vs.conf
----

Add entries for the kernel modules:
----
ip_vs
ip_vs_rr
ip_vs_wrr
ip_vs_sh
----

Reboot the nodes and check that the kernel modules are loaded successfully:
----
lsmod | grep ip_vs
----

Next step will be enabling strictarp mode for ipvs in kube-proxy:

Add the following to the /etc/rancher/rke2/config.yaml on each node

----
kube-proxy-arg:
  - proxy-mode=ipvs
  - ipvs-strict-arp=true

----

Re-start your RKE2 cluster.



===== Installation of {metallb}

To install {metallb} run the following lines in your terminal:

----
$ helm pull oci://dp.apps.rancher.io/charts/metallb --untar
$ helm install --namespace=metallb --set-json 'imagePullSecrets=[{"name":"application-collection"}]' --create-namespace metallb ./metallb
----

++++
<?pdfpagebreak?>
++++

==== Configuration

{metallb} needs two configurations to function properly:

- IP address pool
- L2 advertisement configuration

Create the configuration files for the {metallb} IP address pool:

----
# cat <EOF>>iprange.yaml
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: first-example-pool
  namespace: metallb
spec:
  addresses:
  - 192.168.1.240-192.168.1.250
EOF
----

and the layer 2 network advertisement:

----
# cat <EOF>> l2advertisement.yaml
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: example
  namespace: metallb
EOF
----

Apply the configuration:

----
# kubectl apply -f iprange.yaml
# kubectl apply -f l2advertisement.yaml
----
