[#Redis]

:redis: Redis

The following instructions describe only one variant of installing {redis} which is called Redis Cluster.
There are other possible ways to set up {redis} that are not covered in this guide.
Check if you require link:https://redis.io/docs/management/sentinel/[{redis} Sentinel]
instead of link:https://redis.io/docs/management/scaling/[{redis} Cluster].

IMPORTANT::
SUSE does not offer database support for {redis}.
For support requests contact link:https://redis.com/[Redis Ltd.].


==== Deploying Redis

Although {redis} is available for deployment using the {rancher} Apps, we recommend using the {rac}.
The {redis} chart can be found at https://apps.rancher.io/applications/redis .

++++
<?pdfpagebreak?>
++++


===== Deploying the chart

If you want to use self-signed certificates, you can find instructions how to create such certificates in xref:SAP-EIC-Main.adoc#Appendix[].

Create a configuration file _values.yaml_ that holds some configurations for the {redis} Helm chart.
The configuration could look like this:
----
storageClassName: "longhorn"
global:
  imagePullSecrets: ["application-collection"]
architecture: cluster
nodeCount: 3
auth:
  password: <redisPW>
tls:
  # -- Enable TLS
  enabled: true
  # -- Whether to require Redis clients to authenticate with a valid certificate (authenticated against the trusted root CA certificate)
  authClients: false
  # -- Name of the secret containing the Redis certificates
  existingSecret: "redisCert"
  # -- Certificate filename in the secret
  certFilename: "server.pem"
  # -- Certificate key filename in the secret
  keyFilename: "server.key"
  #  CA certificate filename in the secret - needs to hold the CA.crt and the server.pem
  caCertFilename: "root.pem"
----

To install the application run:

----
$ helm pull oci://dp.apps.rancher.io/charts/redis --untar
$ helm install -f values.yaml --namespace=redis --create-namespace redis ./redis
----
