[#Redis]

:app_name: redis
:redis: Redis


IMPORTANT::
SUSE does not offer database support for {redis}.
For support requests contact link:https://redis.com/[Redis Ltd.].


IMPORTANT::
The following instructions describe only one variant of installing {redis} which is called Redis Cluster.
There are other possible ways to set up {redis} that are not covered in this guide.
Check if you require link:https://redis.io/docs/management/sentinel/[{redis} Sentinel]
instead of link:https://redis.io/docs/management/scaling/[{redis} Cluster].


== Deploying Redis

Although {redis} is available for deployment using the {rancher} Apps, we recommend using the {rac}.
The {redis} chart can be found at https://apps.rancher.io/applications/redis.

++++
<?pdfpagebreak?>
++++


=== Deploying the chart

To deploy the chart, create the related namespace and *imagePullSecret* first.
To create the namespace, run:

[source, bash, subs="attributes"]
----
$ kubectl create namespace {app_name}
----

[#redisIPS]
Instructions how to create the *imagePullSecret* can be found in <<imagePullSecret>>.


If you want to use self-signed certificates, you can find instructions how to create such in <<selfSignedCertificates>>.

[#redisLIR]
Before you can install the application, you need to log in to the registry. You can find the instruction in <<LoginApplicationCollection>>.


Create a file *values.yaml* which holds some configurations for the {redis} Helm chart.
The configuration may look like:

[source, yaml]
----
images:
  redis:
    # -- Image registry to use for the Redis container
    registry: dp.apps.rancher.io
    # -- Image repository to use for the Redis container
    repository: containers/redis
    # -- Image tag to use for the Redis container
    tag: 7.2.5
storageClassName: "longhorn"
global:
  imagePullSecrets: ["application-collection"]
architecture: cluster
nodeCount: 3
auth:
  password: <redisPW>
tls:
  # -- Enable TLS
  enabled: true
  # -- Whether to require Redis clients to authenticate with a valid certificate (authenticated against the trusted root CA certificate)
  authClients: false
  # -- Name of the secret containing the Redis certificates
  existingSecret: "redisCert"
  # -- Certificate filename in the secret
  certFilename: "server.pem"
  # -- Certificate key filename in the secret
  keyFilename: "server.key"
  #  CA certificate filename in the secret - needs to hold the CA.crt and the server.pem
  caCertFilename: "root.pem"
----

To install the application, run:
[source, bash, subs="attributes"]
----
$ helm install {app_name} oci://dp.apps.rancher.io/charts/{app_name} \
-f values.yaml \
--namespace={app_name}
----
