[#Redis]

:redis: Redis

IMPORTANT::
SUSE does not offer database support for {redis}.
To get support, turn to 
link:https://redis.com/[Redis Ltd.]


IMPORTANT::
In this guide we'll describe one variant of installing {redis} which is called Redis Cluster.
There are other possible ways to setup {redis} which are not focussed in this guide.
Please check out if you rather require 
link:https://redis.io/docs/management/sentinel/[Sentinel]
instead of 
link:https://redis.io/docs/management/scaling/[Cluster]

==== Deploying Redis

Even though {redis} is available for deployment using the {rancher} Apps, we recommend to use the {rac}.
The {redis} chart can be found at https://apps.rancher.io/applications/redis .

++++
<?pdfpagebreak?>
++++


===== Deploy the chart

If you want to use self signed certificates, you can find instructions how to create such in xref:SAP-EIC-Main.adoc#Appendix[]

Create a file *values.yaml* which holds some configuration for the {redis} Helm chart.
The config may look like:
----
storageClassName: "longhorn"
global:
  imagePullSecrets: ["application-collection"]
architecture: cluster
nodeCount: 3
auth:
  password: <redisPW>
tls:
  # -- Enable TLS
  enabled: true
  # -- Whether to require Redis clients to authenticate with a valid certificate (authenticated against the trusted root CA certificate)
  authClients: false
  # -- Name of the secret containing the Redis certificates
  existingSecret: "redisCert"
  # -- Certificate filename in the secret
  certFilename: "server.pem"
  # -- Certificate key filename in the secret
  keyFilename: "server.key"
  #  CA certificate filename in the secret - needs to hold the CA.crt and the server.pem
  caCertFilename: "root.pem"
----

To install the application run:

----
$ helm pull oci://dp.apps.rancher.io/charts/redis --untar
$ helm install -f values.yaml --namespace=redis --create-namespace redis ./redis
----
