:app_name: {istio}
:lb_addr: <LB-address>

# tag::intro[]

== Installing {istio}

This chapter describes how to install {istio} in an RKE2 cluster using Helm.

# end::intro[]

# tag::prerequisites[]

=== Prerequisites

To deploy the chart, create the related namespace and *imagePullSecret* first.
To create the namespace, run:

[source, bash, subs="attributes"]
----
kubectl create namespace {istio_namespace}
----

[#istioIPS]
Find instructions how to create the *imagePullSecret* in <<imagePullSecret>>.


[#istioLIR]
Before you can install the application, you need to log in to the registry.
Find the instructions in <<LoginApplicationCollection>>.
# end::prerequisites[]

# tag::deployment[]
=== Deploying the chart

Create a `values.yaml` file to store the configuration for the {istio} Helm chart.
The file content can resemble the following example:

[source, yaml]
----
base:
  '*': null
  enabled: true
  profile: ''
cni:
  '*': null
  enabled: false
  profile: ''
gateway:
  '*': null
  enabled: true
  profile: ''
global:
  '*': null
  imagePullSecrets: ['application-collection']
  imageRegistry: ''
  platform: ''
istiod:
  '*': null
  enabled: true
  profile: ''
ztunnel:
  '*': null
  enabled: false
  profile: ''
----

IMPORTANT: Due to a known bug in the chart, name the helm installation *ingressgateway*.

To install the application, run:

[source, bash, subs="attributes"]
----
helm install ingressgateway oci://dp.apps.rancher.io/charts/istio \
-f values.yaml \
--namespace={istio_namespace} \
--version {istio_chart_version}
----

This deploys the {istio} application, including a *LoadBalancer* Service that consumes the IP address configured in <<metalConfig>>.

To allow {dme} to properly route traffic using the {istio}  service mesh, enable automatic sidecar injection on the target namespace. 
To label the `dm-edge` namespace, run the following command:

[source, bash, subs="attributes"]
----
kubectl label namespace {dme_namespace} istio-injection=enabled
----

For more information on installing and configuring {istio}, check the https://docs.apps.rancher.io/reference-guides/istio/[{istio} reference guide].

# end::deployment[]

# tag::certificate[]

== Certificates

To allow TLS encrypted traffic through the {istio} gateway, configure the certificates.

=== Istio Gateway server certificate

The first certificate needed is the Istio server certificate.
Its purpose is to terminate HTTPS traffic at the Istio Gateway and present the server identity for the _*.<LB-address>_ domains to inbound connections.

Save the following configuration to an _istio-server-cert.yaml_ file, and fill out the required fields:

[source, yaml, subs="attributes"]
----
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: istio-server-cert
  namespace: {istio_namespace}
spec:
  secretName: tls-secret
  duration: 8760h
  renewBefore: 720h
  commonName: "{lb_addr}"
  isCA: false
  privateKey:
    algorithm: RSA
    size: 4096
  usages:
    - server auth
  dnsNames:
    - "server.local"
    - "localhost"
    - "{lb_addr}"
    - "*.{lb_addr}"
  issuerRef:
    name: my-cluster-ca-issuer
    kind: ClusterIssuer
----

To apply it, run:
[source, bash]
----
kubectl apply -f istio-server-cert.yaml
----

This creates a secret in the {istio_namespace} namespace called *tls-secret*.

=== Client Certificate

The next required certificate is the client certificate.
It serves as a client-side identity (`client.crt` and `client.key`) to authenticate requests to the cluster.

Save the following configuration to a `my-client-cert.yaml` file:

[source, yaml, subs="attributes"]
----
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: my-client-cert
  namespace: {istio_namespace}
spec:
  secretName: client-tls-secret
  duration: 8760h
  renewBefore: 720h
  commonName: "dm-edge-services"
  isCA: false
  privateKey:
    algorithm: RSA
    size: 4096
  usages:
    - client auth
  issuerRef:
    name: my-cluster-ca-issuer
    kind: ClusterIssuer
----

To apply it, run:
[source, bash]
----
kubectl apply -f my-client-cert.yaml
----

This creates a secret in the {istio_namespace} namespace called *client-tls-secret*.

=== Istio CA Bundle

Finally, create a placeholder certificate to automate copying the root `ca.crt` into {istio_namespace}. 
This satisfies the hardcoded <ingressServerCertificate>-cacert naming requirement for SAP DM Edge.

Save the following configuration to a `my-client-cert.yaml` file:

[source, yaml, subs="attributes"]
----
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: istio-ingress-ca-bundle
  namespace: {istio_namespace}
spec:
  secretName: tls-secret-cacert
  commonName: "dummy-istio-ca"
  duration: 8760h
  isCA: false
  issuerRef:
    name: my-cluster-ca-issuer
    kind: ClusterIssuer
----

To apply it, run:
[source, bash]
----
kubectl apply -f my-client-cert.yaml
----

This creates a secret in the {istio_namespace} namespace called *tls-secret-cacert*.

# end::certificate[]

