=== Azure Command-Line Interface Environment Preparation

This guide uses the Azure Command-Line Interface (CLI) which is installed on SUSE Linux Enterprise Server 15 (SLES15) Service Pack 1 (SP1) to interact with the Microsoft Azure public cloud.
Please follow the https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-zypper?view=azure-cli-latest[Microsoft instructions] to install Azure CLI for SUSE distributions. 

TIP: Refer to https://docs.microsoft.com/en-us/cli/azure/?view=azure-cli-latest[The Azure Command-Line Interface portal] for more information.

After successful Azure CLI installation, login to the Azure portal using the `az login` command, then list the current Azure account information. Following is an example of the Azure account used during this guide creation time:

.Azure account information list:
========
[subs="specialchars,quotes,attributes"]
----
$ az account list
[
  {
    "cloudName": "AzureCloud",
    "homeTenantId": "*<HOME TENANT ID>*",
    "id": "*<ACCOUNT ID>",*
    "isDefault": true,
    "managedByTenants": [],
    "name": *"<ACCOUNT NAME>",*
    "state": "Enabled",
    "tenantId": "*<TENANT ID>*",
    "user": {
      "name": "*<USER NAME>*",
      "type": "*<USER TYPE>*"
    }
  }
]
----
========


=== Azure Storage Account Preparation

An Azure storage account is needed to host the SAP HANA installation media.

Create a new _file share_ inside the Azure storage account, upload the SAP HANA installation media to the newly created file share, and extract it.

IMPORTANT: It is a must to extract the SAP HANA installation media inside the Azure storage account file share. Saltstack provisioning would NOT work using the SAP HANA compressed installation media.

TIP: Refer to https://docs.microsoft.com/en-us/azure/storage/common/storage-account-create?tabs=azure-portal[Create an Azure Storage account] Microsoft documentation for more information about Azure storage account operations.


=== Terraform Installation

Starting from SLE15 SP1, `terraform` has been added to the SLE Public Cloud Module. Activate the Public Cloud Module and install the `terraform` package.

The following example shows the terraform version available for SLES15 SP1 at this guide creation time:
----
$ sudo zypper in terraform

$ terraform version
Terraform v0.12.19
----

Another way to use terraform is to utilize the `terraform` binary preinstalled in the https://azure.microsoft.com/en-us/features/cloud-shell/[Azure Cloud Shell]. The following example shows the terraform version used in Azure cloud shell at the time of this guide creation:
[subs="specialchars,quotes,attributes"]
----
$ terraform version
Terraform v0.12.23
----

TIP: The `terraform` version used to write this guide is `v0.12.19`. The terraform team keeps updating the terraform version over time. A newer version could be introduced when you applying this guide.  

=== GitHub Repository Cloning

This guide assumes that the _project directory path_ is `/home/*<USERNAME>*/ha-sap-terraform-deployments` where `*<USERNAME>*` is the SLES15 SP1 user used to create the project.

Clone the {projName} GitHub repository:
[subs="specialchars,quotes,attributes"]
----
$ cd /home/*<USERNAME>*

$ git clone https://github.com/SUSE/ha-sap-terraform-deployments.git
----
