This guide aims to build an automated SAP HANA System Replication (SR) Performance-Optimized High Availability (HA) cluster operating on Microsoft Azure public cloud. 

The guide uses the https://github.com/SUSE/ha-sap-terraform-deployments[{projName}] project that provides several functions, one of them is to provide an automated way to deploy SAP HANA HA cluster in public clouds.

The {projName} project uses _Terraform_ for the deployment phase and _Saltstack_ for the provisioning one.
The project is organized in folders containing the _terraform_ configuration files per public or private cloud providers and _Saltstack_ pillars.

For more information about how to create {sapHDSUPOHA} cluster on Microsoft Azure public cloud, please refer to the
https://docs.microsoft.com/en-us/azure/virtual-machines/workloads/sap/sap-hana-high-availability[High Availability of SAP HANA on Azure VMs on SUSE Linux Enterprise Server] guide.

[IMPORTANT]
====
SAP HA solutions are highly customized software solutions based on the customer's environments. This guide provides a _testing environment_ that enables SUSE customers to understand a basic implementation of SAP HANA HA solution utilizing the Microsoft Azure public cloud components.
*The production environments need to have the proper planning prior to the deployment phase.*

Please contact https://www.suse.com/services/consulting[SUSE Consulting Services] for further help.
====  