This guide aims to build an automated SAP HANA System Replication (SR) Performance Optimized High Availability (HA) cluster operating on Microsoft Azure public cloud. 

The guide uses the https://github.com/SUSE/ha-sap-terraform-deployments[{projName}] project that offers several functions. One of these functions is to provide an automated way to deploy SAP HANA HA cluster in public clouds.

The {projName} project uses _Terraform_ for the deployment phase and _SaltStack_ for the provisioning phase.
The project is organized in directories containing the _terraform_ configuration files per public or private cloud providers and _SaltStack_ pillars.

For more information about how to create an {sapHDSUPOHA} cluster on Microsoft Azure public cloud, refer to the guide
https://docs.microsoft.com/en-us/azure/virtual-machines/workloads/sap/sap-hana-high-availability[High Availability of SAP HANA on Azure VMs on SUSE Linux Enterprise Server].

[IMPORTANT]
====
SAP HA solutions are highly customized software solutions based on the customer's environments. This guide provides a _testing environment_ that enables SUSE customers to understand a basic implementation of an SAP HANA HA solution using the Microsoft Azure public cloud components.
*The production environments must be preceded by a proper planning phase prior to the deployment phase.*

Contact https://www.suse.com/services/consulting[SUSE Consulting Services] for further help.
====  