=== _SaltStack_ Pillars Adaptation

SAP HANA and cluster SaltStack Pillars templates are located in the cloned GitHub repository `pillar_example` directory.

Copy the SAP HANA and cluster SaltStack Pillars templates to the proper Salt directory:
[subs="specialchars,quotes,attributes"]
----
$ cd /home/*<{projUser}>*/ha-sap-terraform-deployments

$ cp -av pillar_examples/automatic/hana/*.sls salt/hana_node/files/pillar/
----

Excepting some few parameters' values changes, `/home/*<USERNAME>*/ha-sap-terraform-deployments/salt/hana_node/files/pillar/hana.sls` SaltStack Pillar contents are suitable for this guide. 

The main parameters' values to be updated are:

* SAP users-related passwords
* SAP HANA primary site name
* SPA HANA secondary site name

NOTE: Refer to the section *Appendix* -> *SAP HANA SaltStack Pillar Configuration*, then change the parameters' values highlighted in bold with your appropriate ones.


=== Terraform Configuration Adaptation

The `terraform.tfvars.example` file contains the terraform variables template used to create the cluster infrastructure. 


In this guide, we kept the default values except for the following changed ones:

* Azure virtual machine (VM) instance type
* SAP HANA VMs and iSCSI operating system (OS) subscription model details
* SSH keys path
* Azure storage account name
* SAP HANA installation media path
* HA/SAP deployment packages software repository 

.Adapt the Terraform Variables file:
========
. Change the directory to the terraform azure provider directory path and rename the `terraform.tfvars.example` file to `terraform.tfvars`:
+
[subs="specialchars,quotes,attributes"]
----
$ cd /home/*<{projUser}>*/ha-sap-terraform-deployments/azure

$ mv -v terraform.tfvars.example terraform.tfvars
----

. Generate the private and public keys which will be used by the terraform deployment and SaltStack provisioning:
+
[subs="specialchars,quotes,attributes"]
----
$ mkdir -v /home/*<{projUser}>*/ha-sap-terraform-deployments/salt/hana_node/files/sshkeys

$ ssh-keygen -t rsa -f /home/*<{projUser}>*/ha-sap-terraform-deployments/salt/hana_node/files/sshkeys/cluster.id_rsa
----

. It is given that this guide uses the following OS-related values:
+
|===
| Parameter | Value

| SAP HANA OS version | SUSE Linux Enterprise Server 15 for SAP applications
| iSCSI Target OS version | SUSE Linux Enterprise Server 15 SP1
| Subscription Model | Pay as you GO (PAYGO)
|===
+
Only change the following parameters' values in the `/home/*<{projUser}>*/ha-sap-terraform-deployments/azure/terraform.tfvars` terraform variables configuration file:
+
|===
| Parameter | Old Value | New Value

| instancetype | Standard_M128s | *<CHOSEN INSTANCE TYPE>* 
| hana_public_sku | 12-sp4 | 15
| admin_user | OUR_USERNAME_HERE | *<CHOSEN ADMIN ID>*
| public_key_location | /path/to/your/public/ssh/key | ../salt/hana_node/files/sshkeys/cluster.id_rsa.pub
| private_key_location | /path/to/your/private/ssh/key | ../salt/hana_node/files/sshkeys/cluster.id_rsa
| storage_account_name | YOUR_STORAGE_ACCOUNT_NAME | *<AZURE STORAGE ACCOUNT ID>*
| storage_account_key  | YOUR_STORAGE_ACCOUNT_KEY | *<AZURE STORAGE ACCOUNT KEY #1>*
| hana_inst_master | //YOUR_STORAGE_ACCOUNT_NAME.file.core.windows.net/*path/to/your/hana/installation/master | *<SAP HANA INSTALLATION MEDIA PATH>*
| ha_sap_deployment_repo | "" | "https://download.opensuse.org/repositories/network:/ha-clustering:/Factory/SLE_15/"
|===
========

NOTE: Refer to the section *Appendix* -> *Terraform Configurations* -> *Pay as you Go Subscription Model* to view a complete sample of a `terraform.tfvars` configuration file.

[IMPORTANT]
====
Despite using a specific OS version and subscription model aims to provide a complete test case scenario for this guide, the *{projName}* project gives the opportunity to use different OS version, subscription models and other parameters.

All parameters highlighted in bold in the section *Appendix* -> *Terraform Configurations* -> *Pay as you Go Subscription Model* can be adjusted based on the customer's environment and needs.
====

=== Terraform Deployment

.Deploy the Azure infrastructure using `terraform`:
========
. Initialize the terraform Azure provider:
+
[subs="specialchars,quotes,attributes"]
----
$ cd /home/*<{projUser}>*/ha-sap-terraform-deployments/azure
$ terraform init
----

. Create a new terraform workspace. Select it to be used in the terraform plan and apply phases:
[subs="specialchars,quotes,attributes"]
+
----
$ terraform workspace new *<TERRAFORM WORKSPACE NAME>*
$ terraform workspace select *<TERRAFORM WORKSPACE NAME>*
----

. Plan the terraform deployment:
+
----
$ terraform plan
----

. Apply the terraform deployment:
+
----
$ terraform apply
----

TIP: Terraform deployment and SaltStack provisioning take approximately 40 to 50 minutes.
========
