[#Rancher]

== Installing {rancher}

=== Preparation

==== Install haproxy based Loadbalancer (skip if you do not plan a HA setup)

Setup a virtual machine or bare metal server with {sles} and the HA Extension or use SLES for SAP. Install the haproxy package.

----
# zypper in haproxy
----

Create the configuration for haproxy:
----
cat <EOF>> /etc/haproxy/haproxy.cfg 
EOF 
----

Check the configuration file:
----
#
----

Enable and start the haproxy loadbalancer:
----
# systemctl enable haproxy
# systemctl start haproxy
----



==== Installing Helm

The easiest option to install Helm is to run:
----
# curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
----


==== Installing RKE2

To install RKE2, the script provided at https://get.rke2.io can be used as follows:
----
# curl -sfL https://get.rke2.io | sh -
----

For HA setups it is necessary to create rke2 cluster configuration files in advance:
----
# mkdir -p /etc/rancher/rke2
# cat <EOF >> /etc/rancher/rke2/config.yaml
token: 'your cluster token'
tls-san:
  - FQDN of fixed registration address on Loadbalancer
  - other hostname
  - IP v4 address
EOF
----

Create configuration files for additional cluster nodes:
----
# cat <EOF>> /etc/rancher/rke2/config.yaml
server: https://"FQDN of registration address":9345
token: 'your cluster token'
tls-san:
  - FQDN of fixed registration address on Loadbalancer
  - other hostname
  - IP v4 address
  
EOF
----


After the script finished, start the RKE2 components and run on each cluster node:
----
# systemctl enable rke2-server --now
----

To verify the installation, run the following command:
----
# /var/lib/rancher/rke2/bin/kubectl --kubeconfig /etc/rancher/rke2/rke2.yaml get nodes
----

For convenience, the `kubectl` binary can be added to the *$PATH* and the given `kubeconfig` can be set via an environment variable:
----
# export PATH=$PATH:/var/lib/rancher/rke2/bin/
# export KUBECONFIG=/etc/rancher/rke2/rke2.yaml
----

==== Installing certmanager

----
# helm repo add 
# helm repo update
# kubectl apply -f
# helm install
----

=== Installing {rancher}

To install {rancher}, you need to add the related Helm repository.
To achieve that, use the following command:
----
$ helm repo add rancher-stable https://releases.rancher.com/server-charts/stable
----

As a next step, create the cattle-system namespace in Kubernetes as follows:
----
$ kubectl create namespace cattle-system
----

The Kubernetes cluster is now ready for the installation of {rancher}:
----
$ helm install rancher rancher-stable/rancher \
    --namespace cattle-system \
    --set hostname=<your.domain.com> \
    --set replicas=3
----

During the rollout of {rancher}, you can monitor the progress using the following command:
----
$ kubectl -n cattle-system rollout status deploy/rancher
----

When the deployment is done, you can access the {rancher} cluster at https://<your.domain.com>[]. 
Here you will also find a description about how to log in for the first time.

