[#Rancher]

== Installing {rancher}

=== Preparations

==== Install Helm

The easiest option to install Helm is to run:
----
# curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
----


==== Install RKE2

To install RKE2, the script provided at https://get.rke2.io can be used as followed:
----
# curl -sfL https://get.rke2.io | sh -
----

After the script finished, the RKE2 components need to be started. Therefore, run:
----
# systemctl enable rke2-server --now
----

To verify the installation, run the given command:
----
# /var/lib/rancher/rke2/bin/kubectl --kubeconfig /etc/rancher/rke2/rke2.yaml get nodes
----

For convenience, the kubectl binary can be added to the $PATH and the given kubeconfig can be set via a environment variable:
----
# export PATH=$PATH:/var/lib/rancher/rke2/bin/
# export KUBECONFIG=/etc/rancher/rke2/rke2.yaml
----


=== {rancher} installation

To install {rancher}, the related Helm repository needs to be added.
To achieve that, use the following command:
----
$ helm repo add rancher-stable https://releases.rancher.com/server-charts/stable
----

As a next step, the cattle-system namespace in Kubernetes needs to be created:
----
$ kubectl create namespace cattle-system
----

The Kubernetes cluster is now ready for the installation of {rancher}:
----
$ helm install rancher rancher-stable/rancher \
    --namespace cattle-system \
    --set hostname=<your.domain.com> \
    --set replicas=3
----

During the rollout of {rancher}, the progress can be monitored using:
----
$ kubectl -n cattle-system rollout status deploy/rancher
----

When the deployment is done, the {rancher} cluster can be accessed at https://<your.domain.com>[] where's a description how to login first time too.

