:docinfo:


:di: SAP Data Intelligence
:di_version: 3.3
:sles: SUSE Linux Enterprise Server
:sles_version: 15 SP4
:lh: Longhorn
:rancher: SUSE Rancher
:harvester: Harvester


= {di} 3 on SUSE's Kubernetes stack

== Introduction

This guide describes the on-premises installation of {di} {di_version} using {harvester} and Rancher Kubernetes Engine (RKE) 2.
In a nutshell, the installation of {di} {di_version} consists of the following steps:

* Installing {harvester}

* Installing {rancher}

* Installing RKE 2 Kubernetes cluster on the dedicated nodes

* Deploying {di} {di_version} on RKE 2 Kubernetes cluster

* Performing post-installation steps for {di} {di_version}

* Testing the installation of {di} {di_version}

To have a fully supported setup, there are 2 Kubernetes clusters required.
One to run {rancher} Management server and the other to run the actual workload, which will be {di} in this guide.


include::SAPDI3-Requirements.adoc[Requirements]

== Preparations

* Get a {sles} {sles_version} subscription.

* Download the installer for {sles} {sles_version}.

* Check the storage requirements.

* Create a or get access to a private container registry.

* Get an SAP S-user to access software and documentation by SAP.

* Read the relevant SAP documentation:

** https://launchpad.support.sap.com/#/notes/2871970[Release Note for SAP DI 3]

** https://launchpad.support.sap.com/#/notes/2589449[Release Note for SAP SLC Bridge]  

** https://help.sap.com/viewer/a8d90a56d61a49718ebcb5f65014bbe7/3.2.latest/en-US[Installation Guide at help.sap.com]  

IMPORTANT: Make sure that the Harvester version fits the {rancher} version.
A support matrix can be found here:
https://docs.harvesterhci.io/v1.0/rancher/rancher-integration#rancher--harvester-support-matrix


include::SAPDI3-Harvester-Installation.adoc[Harvester]

include::SAPDI3-Rancher.adoc[Rancher]

include::SAPDI3-Harvester-Rancher.adoc[Harvester-Rancher]

Within this guide it is recommended to deploy 3 Master nodes (roles: etcd & Control Plane) and 4 Worker nodes (roles: Worker) for {di}.
Check <<Hardware Sizing>> to fill out the machine specific configurations to meet the requirements for the given purpose and <<Provision virtual machines with RKE2>> to get an overview how to roll out a RKE2 cluster using {harvester}.

When all machines are provisioned and the RKE2 cluster is up and running, a storage must be made available for {di}.
SUSE offers {lh} which is a validated storage for {di} workloads. The next chapter describes how to setup {lh}.

IMPORTANT: {di} requires a S3 compatible storage for its backups, which is not delivered by {lh}. Check 
https://launchpad.support.sap.com/#/notes/2871970[the related SAP Note] to get an overview of the supported storage solutions together with RKE2.

include::SAPDI3-Longhorn.adoc[Longhorn]

include::SAPDI3-Install.adoc[DI-Install]
