
:docinfo:

= SAP Data Intelligence 3.2 on Harvester and Rancher Kubernetes Engine 2: Installation Guide  


== Introduction

== Prerequisites

== Preparations



== Installing Rancher Kubernetes Engine 2 cluster

The installation of Rancher Kubernetes Engine 2 cluster is straight forward. 
After the installation and basic configuration of the operating system the Kubernetes cluster configuration is created on the management host. 
Subsequently, the Kubernetes cluster will be deployed. 

The following sections describe the installation steps in more detail.


===  Preparing management host and Kubernetes cluster nodes

All servers in our scenario use SUSE Linux Enterprise 15 SP3 (SLES 15 SP3) on the AMD64/Intel 64 architecture.
The documentation for SUSE Linux Enterprise Server can be found at:

* https://documentation.suse.com/sles/15-SP3/


// TODO
// Requirements
// Setup Harvester
// Setup template
// Setup Rancher
// Connect Harvester & Rancher
// Setup K8s cluster
// Install Longhorn
// Install SAP DI



