[#Longhorn]

:lh_version: 1.6.2

== Installing {lh}

This chapter details the minimum requirements to install {lh} and describes three different ways for the installation.
For more details, visit https://longhorn.io/docs/{lh_version}/deploy/install/ 

=== Requirements

Before {lh} can be installed on a Kubernetes cluster,
all nodes must have the `open-iscsi` package installed, and the ISCSI daemon needs to be started. To do so, run:
----
# zypper in -y open-iscsi
# systemctl iscsid enable --now
----

To make sure a node is prepared for {lh}, you can use the following script to check:
----
$ curl -sSfL https://raw.githubusercontent.com/longhorn/longhorn/v1.6.2/scripts/environment_check.sh | bash
----


=== Installing {lh} using {rancher}

Up-to-date and detailed instructions how to install {lh} using {rancher} can be found at
https://longhorn.io/docs/{lh_version}/deploy/install/install-with-rancher/


=== Installing {lh} using Helm

To install Longhorn using Helm, run the following commands:
----
$ helm repo add longhorn https://charts.longhorn.io
$ helm repo update
$ helm install longhorn longhorn/longhorn --namespace longhorn-system --create-namespace
----

These commands will add the Longhorn Helm charts to the list of Helm repositories, update the Helm repository, and execute the installation of Longhorn.

=== Installing {lh} using `kubectl`

You can install {lh} using `kubectl` with the following command:

[subs="attributes"]
----
$ kubectl apply -f https://raw.githubusercontent.com/longhorn/longhorn/v{lh_version}/deploy/longhorn.yaml
----


=== Exposing {lh} UI by creating an Ingress with Basic Authentication



* Create a basic _auth_ file:
+
----
$ USER=<USERNAME_HERE>; \
  PASSWORD=<PASSWORD_HERE>; \
  echo "${USER}:$(openssl passwd -stdin -apr1 <<< ${PASSWORD})" >> auth
----

* Create a secret from the file _auth_:
+
----
$ kubectl -n longhorn-system create secret generic basic-auth --from-file=auth
----

* Create the Ingress with basic authentication:
+
----
$ cat <<EOF > longhorn-ingress.yaml
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: longhorn-ingress
  namespace: longhorn-system
  annotations:
    # type of authentication
    nginx.ingress.kubernetes.io/auth-type: basic
    # prevent the controller from redirecting (308) to HTTPS
    nginx.ingress.kubernetes.io/ssl-redirect: 'false'
    # name of the secret that contains the user/password definitions
    nginx.ingress.kubernetes.io/auth-secret: basic-auth
    # message to display with an appropriate context why the authentication is required
    nginx.ingress.kubernetes.io/auth-realm: 'Authentication Required '
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: longhorn-frontend
          servicePort: 80
EOF

$ kubectl -n longhorn-system apply -f longhorn-ingress.yaml
----


For more details, visit https://longhorn.io/docs/{lh_version}/deploy/accessing-the-ui/longhorn-ingress/.