[#Rancher]

# tag::rancher-rke2-install[]

=== Installing RKE2

To install RKE2, the script provided at https://get.rke2.io can be used as follows:
[source, bash]
----
sudo curl -sfL https://get.rke2.io | INSTALL_RKE2_VERSION=v1.31.7+rke2r1 sh
----

For HA setups, you must create RKE2 cluster configuration files in advance.
On the first master node, do the following:
[source, bash]
----
sudo mkdir -p /etc/rancher/rke2
cat <<EOF > /etc/rancher/rke2/config.yaml
token: 'your cluster token'
system-default-registry: registry.rancher.com
tls-san:
  - FQDN of fixed registration address on load balancer
  - other hostname
  - IP v4 address
EOF
----


Create configuration files for additional cluster nodes:
[source, bash]
----
cat <<EOF > /etc/rancher/rke2/config.yaml
server: https://"FQDN of registration address":9345
token: 'your cluster token'
system-default-registry: registry.rancher.com
tls-san:
  - FQDN of fixed registration address on load balancer
  - other hostname
  - IP v4 address
EOF
----

IMPORTANT: You also need to consider taking etcd snapshots and perform backups of your Rancher instance. These topics are not covered in this document, but you can find more information in our official documentation.
Helpful links are https://documentation.suse.com/cloudnative/rke2/latest/en/backup_restore.html and 
https://documentation.suse.com/cloudnative/rancher-manager/latest/en/rancher-admin/back-up-restore-and-disaster-recovery/back-up-restore-and-disaster-recovery.html.
IMPORTANT: For security reasons, we generally recommend activating the CIS profile when installing RKE2. 
This is currently still being validated and will be included in the documentation at a later date. 

Now enable and start the RKE2 components and run the following command on each cluster node:

[source, bash]
----
sudo systemctl enable rke2-server --now
----

To verify the installation, run the following command:

[source, bash]
----
/var/lib/rancher/rke2/bin/kubectl --kubeconfig /etc/rancher/rke2/rke2.yaml get nodes
----

For convenience, you can add the `kubectl` binary to the *$PATH* and set the specified `kubeconfig` 
via an environment variable:

[source, bash]
----
export PATH=$PATH:/var/lib/rancher/rke2/bin/
export KUBECONFIG=/etc/rancher/rke2/rke2.yaml
----


# end::rancher-rke2-install[]

# tag::helm-install[]

=== Installing Helm

To install {rancher} and some of its required components, you need to use Helm.

One way to install Helm is to run:
[source, bash]
----
curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
----

# end::helm-install[]

# tag::cert-manager-install[]

=== Installing cert-manager

To install the `cert-manager` package, do the following:

[source, bash]
----
kubectl create namespace cert-manager
----

# end::cert-manager-install[]


# tag::application-collection[]
If you want to install `cert-manager` from the _application-collection_ , you must create an imagePullSecret.

[#rancherIPS]
How to create the *imagePullSecret* is described in the <<imagePullSecret>>.

# end::application-collection[]

# tag::rancher-manager-install[]
==== Installing the application

ifdef::eic[]
[#rancherLIR]
Before you can install the application, you need to login into the registry. You can find the instruction in <<LoginApplicationCollection>>.
endif::[]

ifndef::eic[]
You will need to login to the {rac}:

[source, bash]
----
helm registry login dp.apps.rancher.io/charts -u <yourUser> -p <your-token>
----
endif::[]

[source, bash]
----
helm install cert-manager oci://dp.apps.rancher.io/charts/cert-manager \
    --set crds.enabled=true \
    --set-json 'global.imagePullSecrets=[{"name":"application-collection"}]' \
    --namespace=cert-manager \
    --version 1.15.2
----

=== Installing {rancher}

To install {rancher}, you need to add the related Helm repository.
To achieve that, use the following command:

[source, bash]
----
helm repo add rancher-prime https://charts.rancher.com/server-charts/prime
----

Next, create the `cattle-system` namespace in Kubernetes as follows:
[source, bash]
----
kubectl create namespace cattle-system
----

The Kubernetes cluster is now ready for the installation of {rancher}:

[source, bash]
----
helm install rancher rancher-prime/rancher \
    --namespace cattle-system \
    --set hostname=<your.domain.com> \
    --set replicas=3
----

During the rollout of {rancher}, you can monitor the progress using the following command:

[source, bash]
----
kubectl -n cattle-system rollout status deploy/rancher
----

When the deployment is done, you can access the {rancher} cluster at \https://<your.domain.com>[]. 
Here you will also find a description about how to log in for the first time.
# end::rancher-manager-install[]