[#Harvester-Installation]

== Installation of SUSE Rancher Harvester

=== Introduction

Harvester is an opensource hcl solution running on Kubernetes.
Harvester provides the ability to manage and run virtual machines. 

=== Prerequistites

Depending on the purpose of the Harvester installation (development, testing or productive use) one or more (virtual) machines are needed.
Systemarchitecture is x86_64 only by the time of this writing.
For the Harvester deployment the following informations should be handy:
- IP address for the host
- IP address to be used as management address
- Gateway address
- IP address of name server
- access to a timeserver
- access to the internet ( for airgapped installations see: ) //FIXME link

=== Preparations

- Download installation media as needed //FIXME link
- prepare hardware to run Harvester install on.
- network setup (ip addresses, vlans)


=== Installation

The installation of Harvester is straight forward:
- Boot the machines dedicated to Harvester from the install media.
- After booting a guided setup leads through the installation. Information of hostname, ip address, network interface to be used, gateway, timehost, dns servers and if necessary proxy servers can be entered.
After entering the required information, a review panel is shown. Confirm and the installation will start.
As soon as the install has finished successfully the following screen will be shown

=== Accessing the management UI

- use the management (VIP) to access the Harvester UI via a internet browser.
- setting up the administration account

==== Creation of network settings

==== Import OS images for VMs

From the main menu  choose Images, then click on the create button.
The image needs to have a name and an optional description
There two ways  to import an OS image, either by download from an internet source or by uploading a file from local computer.
Finally click the save button.
The image will be stored for later use in Harvester.

==== Create VM

Virtual machines are created by selecting the virtual machine item from menu list and clicking create.

- Give a unique name to the VM 
- select the cpu count
- select the size of RAM
- define the disk size and number of disks
- select network and access method (masquerade or bridged, this depends on the Harvester network configuration)

Start VM deployment by clicking the save button.

