[#Rancher]

== Installing {rancher}

=== Preparation

==== Installing Helm

The easiest option to install Helm is to run:
----
# curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
----


==== Installing RKE2

To install RKE2, the script provided at https://get.rke2.io can be used as follows:
----
# curl -sfL https://get.rke2.io | sh -
----

After the script finished, start the RKE2 components and run:
----
# systemctl enable rke2-server --now
----

To verify the installation, run the following command:
----
# /var/lib/rancher/rke2/bin/kubectl --kubeconfig /etc/rancher/rke2/rke2.yaml get nodes
----

For convenience, the `kubectl` binary can be added to the *$PATH* and the given `kubeconfig` can be set via an environment variable:
----
# export PATH=$PATH:/var/lib/rancher/rke2/bin/
# export KUBECONFIG=/etc/rancher/rke2/rke2.yaml
----


=== Installing {rancher}

To install {rancher}, you need to add the related Helm repository.
To achieve that, use the following command:
----
$ helm repo add rancher-stable https://releases.rancher.com/server-charts/stable
----

As a next step, create the cattle-system namespace in Kubernetes as follows:
----
$ kubectl create namespace cattle-system
----

The Kubernetes cluster is now ready for the installation of {rancher}:
----
$ helm install rancher rancher-stable/rancher \
    --namespace cattle-system \
    --set hostname=<your.domain.com> \
    --set replicas=3
----

During the rollout of {rancher}, you can monitor the progress using the following command:
----
$ kubectl -n cattle-system rollout status deploy/rancher
----

When the deployment is done, you can access the {rancher} cluster at https://<your.domain.com>[]. 
Here you will also find a description about how to log in for the first time.

