// TODO: unify with HANA and ENSA setup guides

= SUSE Product Documentation

// TODO PRIO2: use variables, e.g. {sles4sapDocs15}
Best Practices for {sap} on SUSE Linux Enterprise::
 {reslibrary}
SUSE product manuals and documentation::
 https://documentation.suse.com/
Release notes::
 https://www.suse.com/releasenotes/
Online documentation of {sles4sapa}::
 https://documentation.suse.com/sles-sap/15-SP4/
Online documentation of {sleha}::
 {haAdminGuide15}
Deployment guide for {sls}::
 {deploymentGuide15}
Tuning guide for {sls}::
 {tuningGuide15}
Storage administration guide for {sls}::
 {storageGuide15}
{sls} Persistent Memory Guide::
 {persMemDoc}

////
// TODO PRIO2: still relevant?
// {SUSE} partners with {SAP} and IBM on Persistent Memory::
// https://www.suse.com/c/suse-partners-with-intel-and-sap-to-accelerate-it-transformation-with-persistent-memory-in-the-data-center/
// Persistent Memory on Power9::
// https://www.suse.com/c/using-ibm-power9-powervm-virtual-persistent-memory-for-sap-hana-with-suse-linux/
////

SUSE Linux Enterprise kernel specs::
https://www.suse.com/releasenotes/x86_64/SUSE-SLES/15-SP4/index.html#kernel-limits
SUSE Linux Enterprise file system specs::
https://www.suse.com/releasenotes/x86_64/SUSE-SLES/15-SP4/index.html#file-system-comparison
////
// TODO PRIO2: fix tech info URL
// {slsa} technical information::
//  https://www.suse.com/products/server/
////
XFS file system::
 https://www.suse.com/c/xfs-the-file-system-of-choice/
{SUSE} YES certified hardware database::
 https://www.suse.com/yessearch/
{suma} Product Page::
 {sumalandingpage}
{suma} Documentation::
 {sumadoc}
{RMT} = {rmtool} documentation::
 {rmtGuide15}
{scc} Frequently Asked Questions::
 {sccfaq}


= Related Manual Pages

- chronyc(8)
- corosync.conf(8)
- corosync_overview(8)
- crm(8)
- crm_mon(8)
- crm_simulate(8)
- cs_clusterstate(8)
- cs_man2pdf(8)
- cs_show_hana_info(8)
- cs_show_sbd_devices(8)
- cs_wait_for_idle(8)
- ha_related_sap_notes(7)
- ha_related_suse_tids(7)
- ocf_heartbeat_IPaddr2(7)
- ocf_heartbeat_SAPInstance(7)
- ocf_suse_SAPHanaController(7)
- ocf_suse_SAPHanaFilesystem(7)
- ocf_suse_SAPHanaTopology(7)
- ocf_suse_SAPHanaFilesystem(7)
- SAPHanaSR(7)
- SAPHanaSR-alert-fencing(8)
- SAPHanaSR-angi(7)
- SAPHanaSR_basic_cluster(7)
- SAPHanaSR-hookHelper(8)
- SAPHanaSR_maintenance_examples(7)
- SAPHanaSR-manageAttr(8)
- SAPHanaSR-manageProvider(8)
- SAPHanaSR-monitor(8)
- SAPHanaSR-replay-archive(8)
- SAPHanaSR-ScaleOut(7)
- SAPHanaSR-ScaleOut_basic_cluster(7)
- SAPHanaSR-showAttr(8)
- SAPHanaSR-show-hadr-runtimes(8)
- saptune(8)
- sbd(8)
- stonith_sbd(7)
- sudo(8)
- sudoers(5)
- supportconfig(8)
- susChkSrv.py(7)
- susCostOpt.py(7)
- susHanaSR.py(7)
- susTkOver.py(7)
- systemctl(8)
- systemd-cgls(8)
- votequorum(5)
- zypper(8)


= Related SUSE TIDs

// TODO PRIO1: check if still relevant
SAP HANA SR Performance Optimized Scenario - Setup Guide - Errata::
 {tidNotes}7023882
Estimate correct multipath timeout::
 {tidNotes}7016305
Can't open watchdog device: /dev/watchdog: Device or resource busy::
 {tidNotes}7008216
Systemd-udev-settle timing out::
 {tidNotes}7022681
Configuring Persistent Memory Devices (PMEM) results in booting to the recovery shell::
 {tidNotes}000019517
Slow boot boot initialization on machines with Intel Optane DC Memory causing auto-mount to fail::
 {tidNotes}000019462
How to load the correct watchdog kernel module::
 {tidNotes}7016880
TID XFS metadata corruption and invalid checksum on SAP Hana servers::
 {tidNotes}7022921
Overcommit Memory in SLES::
 {tidNotes}7002775
Recommended SUSE SLES 4 SAP Settings::
 {tidNotes}7024082
SAPHanaController running in timeout when starting SAP Hana::
 {tidNotes}000019899
Troubleshooting the SAPHanaSR python hook::
 {tidNotes}000019865
Entry "CALLING CRM: ... rc=256" in HANA trace after upgrading SAPHanaSR-ScaleOut::
 {tidNotes}000020599
SAP HANA monitors timed out after 5 seconds::
 {tidNotes}000020626
HA cluster takeover takes too long on HANA indexserver failure::
 {tidNotes}000020845
Cluster node fence as SAPHanaTopology fails with error code 1 (OCF_ERR_GENERIC) during a normal cluster stop::
 {tidNotes}000020964
SUSE HA for HANA cluster node fenced at shutdown, despite of systemd integration::
 {tidNotes}000021046
SAP HANA scale-out - pacemaker.service: "Cannot find sapstartsrv and sapcontrol executable, please set DIR_EXECUTABLE parameter!"::
 {tidNotes}000021062
SAPHanaSR-showAttr fails with error "Error: NIECONN_REFUSED ..."::
 {tidNotes}000020548
Protect HANA against manually caused dual-primary situation in SUSE HA cluster::
 {tidNotes}000021044
Address space monitoring and HANA DB performance::
 {tidNotes}000020746
HANA DB resource failed to start::
 {tidNotes}000020948
SAPHanaController monitor timeout leads to database restart::
 {tidNotes}000021249
HANA Database Planning Engine crashes in __strncmp_avx2_rtm+0x1b3::
 {tidNotes}000021026
Basic health check for two-node SAP HANA performance based model::
 {tidNotes}7022984
How to re-enable replication in a two-node SAP performance based model::
 {tidNotes}7023127
Showing SOK Status in Cluster Monitoring Tools Workaround::
 {tidNotes}7023526
HANA SystemReplication doesn't provide SiteName to Corosync Cluster::
 {tidNotes}000019754
SUSE Cluster Support for SAP HANA System Replication Active / Active Read Enabled Feature::
 {tidNotes}7023884
SAP Generating 'Database host operating system is not supported' alerts::
 {tidNotes}7023744
sapstartsrv does not respawn after a forceful kill of the master nameserver::
 {tidNotes}7024291
SAPHanaSR HANA system replication automation without layer 2 network::
 {tidNotes}000020333
The vIP cluster resource does not follow the SAP HANA master ...::
 {tidNotes}000019769
Handling failed NFS share in SUSE HA cluster for HANA system replication::
 {tidNotes}000019904
SAP Instances failed stop on shutdown (PACEMAKER, SYSTEMD, SAP)::
 {tidNotes}7022671
SAP on SLES shows Error: NIECONN_REFUSED in the logs::
 {tidNotes}7023236
Indepth HANA Cluster Debug Data Collection (PACEMAKER, SAP)::
 {tidNotes}7022702
How to prevent certain values in limits.conf from being changed by saptune::
 {tidNotes}7023104
Disabling fstrim - under which conditions?::
 {tidNotes}7023805
saptune: WARNING saptune.io.go:66: 'noop' is not a valid scheduler for device::
 {tidNotes}000019572
How to patch a SAP Application Pacemaker Cluster::
 {tidNotes}000020268


= Related SUSE blogs

How to upgrade to SAPHanaSR-angi::
https://www.suse.com/c/how-to-upgrade-to-saphanasr-angi/
Emergency Braking for SAP HANA Dying Indexserver::
https://www.suse.com/c/emergency-braking-for-sap-hana-dying-indexserver/
SAP HANA Cockpit with SUSE HA integration greatly improves data integrity::
https://www.suse.com/c/sap-hana-cockpit-with-suse-ha-integration-greatly-improves-data-integrity/
Handover for the Next Round – SAP on SUSE Cluster and systemd Native Integration::
 https://www.suse.com/c/handover-for-the-next-round-sap-on-suse-cluster-and-systemd-native-integration/
SAPHanaSR-ScaleOut for Multi-Target Architecture and Principles::
 https://www.suse.com/c/saphanasr-scaleout-multi-target/
SAP HANA Scale-Out System Replication for large ERP Systems::
 https://www.suse.com/c/sap-hana-scale-out-system-replication-for-large-erp-systems/
SAP HANA Cost-optimized – An alternative Route is available::
 https://www.suse.com/c/sap-hana-cost-optimized-an-alternative-route-is-available/
Let’s flip the flags! Is my SAP HANA database in sync or not?::
 https://www.suse.com/c/lets-flip-the-flags-is-my-sap-hana-database-in-sync-or-not/
Entry to blog series #towardsZeroDowntime::
 https://www.suse.com/c/tag/towardszerodowntime/
Fail-Safe Operation of {SAPHANA}: {SUSE} Extends Its High-Availability Solution::
 http://scn.sap.com/community/hana-in-memory/blog/2014/04/04/fail-safe-operation-of-sap-hana-suse-extends-its-high-availability-solution


= Related SAP Documentation

{sap} Product Availability Matrix::
 https://support.sap.com/en/release-upgrade-maintenance.html#section_1969201630
{SAPHANA} Installation and Update Guide::
 https://help.sap.com/doc/e9702d76c3284623b02de196c0e79e49/2.0.05/en-US/SAP_HANA_Server_Installation_Guide_en.pdf
{SAPHANA} Administration Guide::
 https://help.sap.com/doc/eb75509ab0fd1014a2c6ba9b6d252832/2.0.05/en-US/SAP_HANA_Administration_Guide_en.pdf
{SAPHANA} Documentation Entry Page::
 https://help.sap.com/viewer/product/SAP_HANA_PLATFORM/2.0.05/en-US
{SAPHANA} Tailored Data Center Integration - FAQ::
 https://www.sap.com/documents/2016/05/e8705aae-717c-0010-82c7-eda71af511fa.html
{SAPHANA} and Persistent Memory::
 https://blogs.sap.com/2020/01/30/sap-hana-and-persistent-memory/
{SAPHANA} HA/DR Provider Hook Methods::
 https://help.sap.com/viewer/6b94445c94ae495c83a19646e7c3fd56/2.0.05/en-US/5df2e766549a405e95de4c5d7f2efc2d.html


= Related SAP Notes

[[sap-notes]]
// TODO PRIO1: check if still relevant
611361 - Hostnames of SAP servers::
 {launchPadNotes}611361
768727 - Automatic restart functions in sapstart for processes::
 {launchPadNotes}768727
927637 - Web service authentication in sapstartsrv as of Release 7.00::
 {launchPadNotes}927637
1092448 - IBM XL C/C++ runtime environment for Linux on system p::
 {launchPadNotes}1092448
1514967 - SAP HANA: Central Note::
 {launchPadNotes}1514967
1552925 - Linux: High Availability Cluster Solutions::
 {launchPadNotes}1552925
1763512 - Support details for SUSE Linux Enterprise for SAP applications::
 {launchPadNotes}1763512
1846872 - "No space left on device" error reported from HANA::
{launchPadNotes}1846872
1876398 - Network configuration for System Replication in HANA SP6::
 {launchPadNotes}1876398
1888072 - SAP HANA DB: Indexserver crash in strcmp sse42::
 {launchPadNotes}1888072
2021789 - SAP HANA Revison and Maintenance Strategy::
 {launchPadNotes}2021789
2196941 - SAP HANA Software Replication Takeover Hook Changes::
 {launchPadNotes}2196941
2235581 - SAP HANA: Supported Operating Systems::
 {launchPadNotes}2235581
2369981 - Required configuration steps for authentication with HANA System Replication::
 {launchPadNotes}2369981
2369910 - SAP Software on Linux: General information::
 {launchPadNotes}2369910
2380229 - SAP HANA Platform 2.0 - Central Note::
 {launchPadNotes}2380229
2434562 - System Replication Hanging in Status "SYNCING" or "ERROR" With Status Detail "Missing Log" or "Invalid backup size"::
 {launchPadNotes}2434562
2578899 - SUSE Linux Enterprise Server 15: Installation Note::
 {launchPadNotes}2578899
2647673 - HANA Installation Failure::
 {launchPadNotes}2647673
2684254 - SAP HANA DB: Recommended OS settings for SLES 15 / SLES for SAP applications 15::
 {launchPadNotes}2684254
2733483 - Host Auto-Failover Not Occur when Indexserver Crash on Worker Node::
 {launchPadNotes}2733483
2750199 - Incorrect Alert Regarding Unsupported Operating System Version::
 {launchPadNotes}2750199
2844322 - SAP HANA Platform 2.0 SPS 05 Release Note::
 {launchPadNotes}2844322
2945239 - SAP HANA Platform 2.0 SPS 06 Release Note::
 {launchPadNotes}2945239
3007062 - FAQ: SAP HANA & Third Party Cluster Solutions::
 {launchPadNotes}3007062
3014176 - Applying System Size Dependent Resource Limits During Installation or Upgrade::
 {launchPadNotes}3014176
3043459 - SAP HANA 2 SPS05 Revision 056.00::
 {launchPadNotes}3043459
3072590 - Python 3 Support for Non-Productive SAP HANA Systems::
 {launchPadNotes}3072590
3070359 - Python 3 Migration Guide For SAP HANA::
 {launchPadNotes}3070359
3084229 - SAP HANA Python Support Scripts Fail due to Incompatibility With Python 3::
 {launchPadNotes}3084229
3091152 - sapstartsrv - improved deregistration for UNIX/Linux::
 {launchPadNotes}3091152
3093542 - Transition to Python 3 of the Python Distribution Delivered With SAP HANA 2.0 Server::
 {launchPadNotes}3093542
3139184 - Linux: systemd integration for sapstartsrv and SAP Hostagent::
 {launchPadNotes}3139184
3145200 - SAP Host Agent 7.22 PL57::
 {launchPadNotes}3145200
3446532 - Pacemaker cluster resource unavailable due to inadequate memory garbage collection parameter settings::
 {launchPadNotes}3446532

// TODO PRIO3: check whether still relevant:
////
1056161 - SUSE Priority Support for SAP applications::
{launchPadNotes}1056161
1275776 - Preparing SLES for Sap Environments::
{launchPadNotes}1275776
1514967 - SAP HANA: Central Note::
{launchPadNotes}1514967
1501701 - Single Computing Unit Performance and Sizing::
{launchPadNotes}1501701
1944799 - SAP HANA Guidelines for SLES Operating System Installation::
{launchPadNotes}1944799
////


//
// REVISION 1.0 (2024-05-27)
//   - copied from scale-out multi-target 
//
