// TODO: unify with HANA and ENSA setup guides

= SUSE Product Documentation

Best Practices for {sap} on SUSE Linux Enterprise::
 {reslibrary}
SUSE product manuals and documentation::
 https://documentation.suse.com/
Online documentation of {sles4sapa}::
 https://documentation.suse.com/sles-sap/15-SP3/
Online documentation of {sleha}::
 {haAdminGuide15}
Deployment guide for {sls}::
 {deploymentGuide15}
Tuning guide for {sls}::
 {tuningGuide15}
Storage administration guide for {sls}::
 {storageGuide15}
Release notes::
 https://www.suse.com/releasenotes/
{slsa} technical information::
 https://www.suse.com/products/server/technical-information/
XFS file system::
 https://www.suse.com/communities/conversations/xfs-the-file-system-of-choice/


= Related Manual Pages

- chronyc(8)
- corosync.conf(8)
- corosync_overview(8)
- crm(8)
- crm_mon(8)
- crm_simulate(8)
- cs_clusterstate(8)
- cs_man2pdf(8)
- cs_show_hana_info(8)
- cs_show_sbd_devices(8)
- cs_wait_for_idle(8)
- ha_related_sap_notes(7)
- ha_related_suse_tids(7)
- ocf_heartbeat_IPAddr2(7)
- ocf_heartbeat_SAPInstance(7)
- ocf_suse_SAPHana(7)
- ocf_suse_SAPHanaController(7)
- ocf_suse_SAPHanaTopology(7)
- SAHanaSR(7)
- SAPHanaSR-filter(8)
- SAPHanaSR_maintenance_examples(7)
- SAPHanaSR-replayArchive(8)
- SAPHanaSR-ScaleOut(7)
- SAPHanaSR-ScaleOut_basic_cluster(7)
- SAPHanaSR-showAttr(8)
- SAPHanaSR.py(7)
- SAPHanaSrMultiTarget.py(7)
- sbd(8)
- stonith_sbd(7)
- sudo(8)
- sudoers(5)
- supportconfig(8)
- systemctl(8)
- systemd-cgls(8)
- votequorum(5)
- zypper (8)


= Related SUSE TIDs

// TODO PRIO1: check if still relevant
SUSE SAP Best Practice Guide Errata::
 {tidNotes}7023713
SAP HANA SR Performance Optimized Scenario - Setup Guide - Errata::
 {tidNotes}7023882
Estimate correct multipath timeout::
 {tidNotes}7008216
How to load the correct watchdog kernel module::
 {tidNotes}7016880
Overcommit Memory in SLES::
 {tidNotes}7002775
Recommended SUSE SLES 4 SAP Settings:: 
 {tidNotes}7024082
SAPHanaController running in timeout when starting SAP Hana::
 {tidNotes}000019899
Troubleshooting the SAPHanaSR python hook::
 {tidNotes}000019865
Basic health check for two-node SAP HANA performance based model::
 {tidNotes}7022984
How to re-enable replication in a two-node SAP performance based model::
 {tidNotes}7023127
Showing SOK Status in Cluster Monitoring Tools Workaround::
 {tidNotes}7023526
HANA SystemReplication doesn't provide SiteName to Corosync Cluster::
 {tidNotes}000019754
SUSE Cluster Support for SAP HANA System Replication Active / Active Read Enabled Feature::
 {tidNotes}7023884
SAP Generating 'Database host operating system is not supported' alerts::
 {tidNotes}7023744
sapstartsrv does not respawn after a forceful kill of the master nameserver::
 {tidNotes}7024291
SAPHanaSR HANA system replication automation without layer 2 network::
 {tidNotes}000020333
The vIP cluster resource does not follow the SAP HANA master ...::
 {tidNotes}000019769
Handling failed NFS share in SUSE HA cluster for HANA system replication::
 {tidNotes}000019904
SAP Instances failed stop on shutdown (PACEMAKER, SYSTEMD, SAP)::
 {tidNotes}7022671
SAP on SLES shows Error: NIECONN_REFUSED in the logs::
 {tidNotes}7023236
Indepth HANA Cluster Debug Data Collection (PACEMAKER, SAP)::
 {tidNotes}7022702
How to prevent certain values in limits.conf from being changed by saptune::
 {tidNotes}7023104
Memory, I/O and DefaultTasksMax related considerations for SLES for SAP servers with huge memory::
 {tidNotes}7021211
Disabling fstrim - under which conditions?::
 {tidNotes}7023805
saptune: WARNING saptune.io.go:66: 'noop' is not a valid scheduler for device::
 {tidNotes}000019572
How to patch a SAP Application Pacemaker Cluster::
 {tidNotes}000020268


= Related SUSE blogs

Handover for the Next Round – SAP on SUSE Cluster and systemd Native Integration::
 https://www.suse.com/c/handover-for-the-next-round-sap-on-suse-cluster-and-systemd-native-integration/
SAPHanaSR-ScaleOut for Multi-Target Architecture and Principles::
 https://www.suse.com/c/saphanasr-scaleout-multi-target/
SAP HANA Scale-Out System Replication for large ERP Systems::
 https://www.suse.com/c/sap-hana-scale-out-system-replication-for-large-erp-systems/
SAP HANA Cost-optimized – An alternative Route is available::
 https://www.suse.com/c/sap-hana-cost-optimized-an-alternative-route-is-available/
Let’s flip the flags! Is my SAP HANA database in sync or not?::
 https://www.suse.com/c/lets-flip-the-flags-is-my-sap-hana-database-in-sync-or-not/
Entry to blog series #towardsZeroDowntime::
 https://www.suse.com/c/tag/towardszerodowntime/


= Related SAP Documentation

SAP Product Availability Matrix::
 https://support.sap.com/en/release-upgrade-maintenance.html#section_1969201630
SAP HANA Installation and Update Guide::
 http://help.sap.com/hana/SAP_HANA_Server_Installation_Guide_en.pdf
SAP HANA Administration Guide::
 http://help.sap.com/hana/SAP_HANA_Administration_Guide_en.pdf
SAP HANA Tailored Data Center Integration - FAQ::
 https://www.sap.com/documents/2016/05/e8705aae-717c-0010-82c7-eda71af511fa.html

= Related SAP Notes

// TODO PRIO1: check if still relevant
611361 - Hostnames of SAP servers::
 {launchPadNotes}611361
768727 - Automatic restart functions in sapstart for processes::
 {launchPadNotes}768727
927637 - Web service authentication in sapstartsrv as of Release 7.00::
 {launchPadNotes}927637
1092448 - IBM XL C/C++ runtime environment for Linux on system p::
 {launchPadNotes}1092448
1514967 - SAP HANA: Central Note::
 {launchPadNotes}1514967
1552925 - Linux: High Availability Cluster Solutions::
 {launchPadNotes}1552925
1763512 - Support details for SUSE Linux Enterprise for SAP Applications::
 {launchPadNotes}1763512
1876398 - Network configuration for System Replication in HANA SP6::
 {launchPadNotes}1876398
2021789 - SAP HANA Revison and Maintenance Strategy::
 {launchPadNotes}2021789
2196941 - SAP HANA Software Replication Takeover Hook Changes::
 {launchPadNotes}2196941
2235581 - SAP HANA: Supported Operating Systems::
 {launchPadNotes}2235581
2369981 - Required configuration steps for authentication with HANA System Replication::
 {launchPadNotes}2369981
2369910 - SAP Software on Linux: General information::
 {launchPadNotes}2369910
2380229 - SAP HANA Platform 2.0 - Central Note::
 {launchPadNotes}2380229
2434562 - System Replication Hanging in Status "SYNCING" or "ERROR" With Status Detail "Missing Log" or "Invalid backup size"::
 {launchPadNotes}2434562
2578899 - SUSE Linux Enterprise Server 15: Installation Note::
 {launchPadNotes}2578899
2647673 - HANA Installation Failure::
 {launchPadNotes}2647673
2684254 - SAP HANA DB: Recommended OS settings for SLES 15 / SLES for SAP Applications 15::
 {launchPadNotes}2684254
2733483 - Host Auto-Failover Not Occur when Indexserver Crash on Worker Node::
 {launchPadNotes}2733483
2750199 - Incorrect Alert Regarding Unsupported Operating System Version::
 {launchPadNotes}2750199
3007062 - FAQ: SAP HANA & Third Party Cluster Solutions::
 {launchPadNotes}3007062
3043459 - SAP HANA 2 SPS05 Revision 056.00::
 {launchPadNotes}3043459
3072590 - Python 3 Support for Non-Productive SAP HANA Systems::
 {launchPadNotes}3072590
3070359 - Python 3 Migration Guide For SAP HANA::
 {launchPadNotes}3070359
3084229 - SAP HANA Python Support Scripts Fail due to Incompatibility With Python 3::
 {launchPadNotes}3084229
3091152 - sapstartsrv - improved deregistration for UNIX/Linux::
 {launchPadNotes}3091152
3093542 - Transition to Python 3 of the Python Distribution Delivered With SAP HANA 2.0 Server::
 {launchPadNotes}3093542
3139184 - Linux: systemd integration for sapstartsrv and SAP Hostagent::
 {launchPadNotes}3139184
3145200 - SAP Host Agent 7.22 PL57::
 {launchPadNotes}3145200

// REVISION 1.0 2022/02
//   - copied from SAPNotes_s4_1809.adoc

