// Load document variables
:prodNr: 16
:pMinor16: 0
include::Var_SLES4SAP-{prodNr}.txt[]
include::Var_SLES4SAP-hana-angi-{prodNr}.txt[]
include::Var_SLES4SAP-hana-angi-param-{prodNr}.txt[]
[[app.hana-sr.example]]
== Examples

// DONE PRIO1: "replace ha-cluster-init" by "crm cluster init"
// TODO PRIO2: Remove HAWK
// TODO PRIO2: replace local values (like disk-path) by refernces

=== Example `{slehainit}` configuration
[subs="attributes,quotes"]
----
INFO: Loading "default" profile from /etc/crm/profiles.yml
INFO: Loading "knet-default" profile from /etc/crm/profiles.yml
INFO: A public key is added to authorized_keys for user root: 2048 SHA256:BpU1NYKSI1pLWQVkZCotf1jdiThQlMrCd77Pz2XTGf0 root@glishorn01 (RSA)
INFO: The user 'hacluster' will have the login shell configuration changed to /bin/bash
Continue (y/n)? y
INFO: A new ssh keypair is generated for user hacluster.
INFO: A public key is added to authorized_keys for user hacluster: 3072 SHA256:sOI39ogMRs3WOJqFzFO12mTy+gAf9jS7Bu7Y334W5g4 Cluster internal on {sapnode1} (RSA)
INFO: Added firewalld service high-availability on {sapnode1}
Address for ring0 [{sapip1node1}]
INFO: Configuring disk-based SBD
INFO: Initializing SBD device /dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_drive-scsi0-0-0
INFO: Update SBD_DEVICE in /etc/sysconfig/sbd: /dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_drive-scsi0-0-0
INFO: Update SBD_WATCHDOG_DEV in /etc/sysconfig/sbd: /dev/watchdog0
INFO: Enable sbd.service on node {sapnode1}
INFO: Configure Qdevice/Qnetd:
  QDevice participates in quorum decisions. With the assistance of 
  a third-party arbitrator Qnetd, it provides votes so that a cluster 
  is able to sustain more node failures than standard quorum rules 
  allow. It is recommended for clusters with an even number of nodes 
  and highly recommended for 2 node clusters.

Do you want to configure QDevice (y/n)? n
INFO: Hawk cluster interface is now running. To see cluster status, open:
INFO:   https://{sapip1node1}:7630/
INFO: Log in with username 'hacluster', password 'linux'
WARNING: You should change the hacluster password to something more secure!
INFO: Starting and enable pacemaker.service on {sapnode1}
INFO: BEGIN Waiting for cluster
............                                                                                                                                                                                                       
INFO: END Waiting for cluster
INFO: Loading initial cluster configuration
INFO: Configuring fence agent stonith:fence_sbd
INFO: Update SBD_DELAY_START in /etc/sysconfig/sbd: 41
INFO: Adjusting stonith-timeout to 71
WARNING: "stonith-timeout" in crm_config is set to 71, it was 60s
INFO: Setting stonith-enabled to true
WARNING: "stonith-enabled" in crm_config is set to true, it was false
INFO: Createing runtime drop-in file /run/systemd/system/sbd.service.d/sbd_delay_start_disabled.conf to unset SBD_DELAY_START
WARNING: "stonith-timeout" is deprecated, please consider using "fencing-timeout"
WARNING: "stonith-enabled" is deprecated, please consider using "fencing-enabled"
INFO: Configure Administration IP Address:
  Optionally configure an administration virtual IP
  address. The purpose of this IP address is to
  provide a single IP that can be used to interact
  with the cluster, rather than using the IP address
  of any specific cluster node.

Do you wish to configure a virtual IP address (y/n)? n
INFO: Done (log saved to /var/log/crmsh/crmsh.log on {sapnode1})
----

// TODO PRIO2: add the crm cluster join to the examples (see below)
// TODO PRIO2: replace besler3+4 and disk-path + ip addr by references
////
besler4:~ # crm cluster join -c besler3
INFO: The user 'hacluster' will have the login shell configuration changed to /bin/bash
Continue (y/n)? y
INFO: A new ssh keypair is generated for user hacluster.
INFO: A public key is added to authorized_keys for user hacluster: 3072 SHA256:XU8AHmSS8Zr1UT5FSBuoOoDP7ljFFHdyjHZY7w55kXs Cluster internal on besler4 (RSA)
INFO: Added firewalld service high-availability on besler4
INFO: Merging known_hosts
INFO: BEGIN Probing for new partitions
INFO: END Probing for new partitions
INFO: BEGIN Retrieving all configuration files from besler3
INFO: END Retrieving all configuration files from besler3
Address for ring0 [192.168.2.64]

INFO: Sync file /etc/corosync/corosync.conf to besler3
INFO: Got SBD configuration
INFO: Enable sbd.service on node besler4
INFO: Hawk cluster interface is now running. To see cluster status, open:
INFO:   https://192.168.2.64:7630/
INFO: Log in with username 'hacluster', password 'linux'
WARNING: You should change the hacluster password to something more secure!
INFO: Starting and enable pacemaker.service on besler4
INFO: BEGIN Waiting for cluster
..                                                                                                                                                                                                                 
INFO: END Waiting for cluster
INFO: Setting pcmk_delay_max parameter to 30s in resource fencing-sbd
INFO: Update SBD_DELAY_START in /etc/sysconfig/sbd: 71
INFO: Sync file /etc/sysconfig/sbd to besler3
WARNING: "stonith-timeout" is deprecated, please consider using "fencing-timeout"
WARNING: "stonith-enabled" is deprecated, please consider using "fencing-enabled"
WARNING: "priority" in rsc_defaults is set to 1, it was 0
WARNING: "priority-fencing-delay" in crm_config is set to 60, it was 0
INFO: Sync file /etc/corosync/corosync.conf to besler3
INFO: BEGIN Reloading cluster configuration
INFO: END Reloading cluster configuration
INFO: Done (log saved to /var/log/crmsh/crmsh.log on besler4)
////

// DO NOT CHANGE AUTOGENERATED SECTION ID: id-example-cluster-configuration
// DO NOT CHANGE SECTION TITLE as this would change autogenerated section ID
// Refer to Trento check
=== Example cluster configuration

The following complete progressive crm configuration is for a two-node cluster
({sapnode1}, {sapnode2}) and an {HANA} database with SID {sapsid}
and instance number {sapino}. A failed primary will be automatically registered
as secondary after reboot.
Priority fencing prefers the {HANA} primary in case of split-brain.
The virtual IP address in the example is {sapip1srv1}.

[subs="attributes,quotes"]
----
node {sapnode1}
node {sapnode2}

primitive rsc_SAPHanaTop_{sapsid}_HDB{sapino} ocf:suse:SAPHanaTopology \
    op start interval=0 timeout=600 \
    op stop interval=0 timeout=300 \
    op monitor interval=50 timeout=600 \
    params SID={sapsid} InstanceNumber={sapino}

primitive rsc_SAPHanaFil_{sapsid}_HDB{sapino} ocf:suse:SAPHanaFilesystem \
    op start interval=0 timeout=10 \
    op stop interval=0 timeout=20 \
    op monitor interval=120 timeout=120 \
    params SID={sapsid} InstanceNumber={sapino} \
        ON_FAIL_ACTION=fence

primitive rsc_SAPHanaCon_{sapsid}_HDB{sapino} ocf:suse:SAPHanaController \
    op start interval=0 timeout=3600 \
    op stop interval=0 timeout=600 \
    op promote interval=0 timeout=900 \
    op demote interval=0 timeout=320 \
    op monitor interval=60 role=Promoted timeout=700 \
    op monitor interval=61 role=Unpromoted timeout=700 \
    params SID={sapsid} InstanceNumber={sapino} \
        PREFER_SITE_TAKEOVER=true DUPLICATE_PRIMARY_TIMEOUT=7200 \
        AUTOMATED_REGISTER=true ON_FAIL_ACTION=fence \
    meta priority=100

primitive rsc_ip_{sapsid}_HDB{sapino} ocf:heartbeat:IPaddr2 \
    op monitor interval=10 timeout=20 \
    params ip={sapip1srv1}

primitive stonith-sbd stonith:fence_sbd \
    params pcmk_delay_max=15

clone mst_SAPHanaCon_{sapsid}_HDB{sapino} rsc_SAPHanaCon_{sapsid}_HDB{sapino} \
    meta clone-node-max=1 interleave=true promotable=true

clone cln_SAPHanaTop_{sapsid}_HDB{sapino} rsc_SAPHanaTop_{sapsid}_HDB{sapino} \
    meta clone-node-max=1 interleave=true

clone cln_SAPHanaFil_{sapsid}_HDB{sapino} rsc_SAPHanaFil_{sapsid}_HDB{sapino} \
    meta clone-node-max=1 interleave=true

colocation col_saphana_ip_{sapsid}_HDB{sapino} 2000: \
    rsc_ip_{sapsid}_HDB{sapino}:Started mst_SAPHanaCon_{sapsid}_HDB{sapino}:Promoted

order ord_saphana_{sapsid}_HDB{sapino} Optional: \
    cln_SAPHanaTop_{sapsid}_HDB{sapino} mst_SAPHanaCon_{sapsid}_HDB{sapino}

property cib-bootstrap-options: \
    cluster-infrastructure=corosync \
    stonith-enabled=true \
    stonith-action=reboot \
    stonith-timeout=150 \
    priority-fencing-delay=30

rsc_defaults rsc-options: \
    resource-stickiness=1000 \
    migration-threshold=5000

op_defaults op-options \
    timeout=600 \
    record-pending=true
----

// DO NOT CHANGE AUTOGENERATED SECTION ID: id-example-for-etccorosynccorosync-conf
// DO NOT CHANGE SECTION TITLE as this would change autogenerated section ID
// Refer to Trento checks
// Refer to Trento checks
=== Example for _/etc/corosync/corosync.conf_

The following file shows a typical corosync configuration with two rings.
Review the SUSE product documentation about details.
See also manual pages corosync.conf(5) and votequorum(5).
// TODO PRIO3: get corosync.conf from common include file

[subs="attributes,quotes"]
----
# Read the corosync.conf.5 manual page
totem {
    version: 2
    secauth: on
    crypto_hash: sha1
    crypto_cipher: aes256
    cluster_name: suse-ha
    clear_node_high_bit: yes
    token: 5000
    token_retransmits_before_loss_const: 10
    join: 60
    consensus: 6000
    max_messages: 20
    interface {
        ringnumber: 0
        mcastport: 5405
        ttl: 1
    }
    interface {
        ringnumber: 1
        mcastport: 5407
        ttl: 1
    }
    rrp_mode: passive
    transport: udpu
}

logging {
    fileline: off
    to_stderr: no
    to_logfile: no
    logfile: /var/log/cluster/corosync.log
    to_syslog: yes
    debug: off
    timestamp: on
    logger_subsys {
        subsys: QUORUM
        debug: off
    }
}

nodelist {
    node {
            ring0_addr: {sapIp1Node1}
            ring1_addr: {sapIp2Node1}
            nodeid: 1
    }
    node {
            ring0_addr: {sapIp1Node2}
            ring1_addr: {sapIp2Node2}
            nodeid: 2
    }
}

quorum {
        provider: corosync_votequorum
        expected_votes: 2
        two_node: 1
}
----

=== Examples for alternate fencing methods

==== Example for deterministic SBD fencing

These SBD resources make sure that node {sapnode1} will win in case of split-brain.

[subs="attributes,quotes"]
----
primitive rsc_sbd_{sapnode1} stonith:external/sbd \
    params pcmk_host_list={sapnode2} pcmk_delay_base=0

primitive rsc_sbd_{sapnode2} stonith:external/sbd \
    params pcmk_host_list={sapnode1} pcmk_delay_base=30
----

[[cha.hanasr-example-ipmi]]
==== Example for the IPMI fencing method

[subs="attributes,quotes"]
----
primitive rsc_{sapnode1}_stonith stonith:external/ipmi \
    params hostname="{sapnode1}" ipaddr="{sapip1ipmi1}" userid="stonith" \
    passwd="k1llm3" interface="lanplus" \
    op monitor interval=1800 timeout=30
    ...
primitive rsc_{sapnode2}_stonith stonith:external/ipmi \
    params hostname="{sapnode2}" ipaddr="{sapip1ipmi2}" userid="stonith" \
    passwd="k1llm3" interface="lanplus" \
    op monitor interval=1800 timeout=30
    ...
location loc_{sapnode1}_stonith rsc_{sapnode1}_stonith -inf: {sapnode1}
location loc_{sapnode2}_stonith rsc_{sapnode2}_stonith -inf: {sapnode2}
----

////
// TODO remove: [[cha.hanasr-example-systemv]]
// TODO remove: === Example for checking legacy SystemV integration
//
// TODO remove: include::SLES4SAP-hana-systemv-appendix.adoc[]
////

++++
<?pdfpagebreak?>
++++
