//multi vendor solution (mvs)

# tag::mvs-general[]

==== Multi Vendor solution

This section will provided some advise how to handle business critical solutions where multiple vendors are involved.

# end::mvs-general[]

# tag::mvs-sql[]

==== SUSE and Microsoft SQL Server

The solution in this guide requires a support contract for both products. With SUSE (valid and active subscription) for the operating system and with Microsoft a license for  MS SQL Server.

Details about the SUSE subscriptions can be found here:

* https://www.suse.com/support/

Details about the SQL Server licensing can be found here:

* https://www.microsoft.com/en-us/sql-server/sql-server-2022-pricing
* https://www.microsoft.com/licensing/docs/view/SQL-Server

In case your infrastructure is running in a public cloud environment, your CSP (cloud service provider) may have different support contract offerings.

* BYOS ( = SUSE Subscription + support for OS)
* PAYG ( = only CSP support for OS)

In case of support is required: Depending on the support contract, a decision must be made.

[discrete]
.Support from Microsoft
A collection support channels can be found here:
https://learn.microsoft.com/en-us/troubleshoot/sql/database-engine/install/windows/support-policy-sql-server#obtain-support-from-microsoft

# end::mvs-sql[]
