// Load document variables
:prodNr: 16
:pMinor16: 0
include::Var_SLES4SAP-{prodNr}.txt[]
include::Var_SLES4SAP-hana-angi-{prodNr}.txt[]
include::Var_SLES4SAP-hana-angi-param-{prodNr}.txt[]
// DO NOT CHANGE SECTION ID: refer to Trento checks
[[cha.hana-sr.scenario]]
== Supported scenarios and prerequisites

For the `{saphanasr}` package configuration as decribed in this document,
we limit the support to scale-up (single-box to single-box) system replication
with the following configurations and parameters:

* Two-node clusters are standard. Three node clusters are fine if you install
the resource agents also on that third node. But define in the cluster that
{HANA} resources must never run on that third node. In this case the third
node is an additional majority maker in case of cluster separation.
* The cluster must include a valid fencing method.
** Any fencing mechanism supported for production use by {sleha} {prodnr} (like
SBD, IPMI) is supported with {saphanasr}.
** This guide is focusing on the SBD fencing method as this is hardware independent.
** If you use disk-based SBD as the fencing mechanism, you need one or more shared
drives. For productive environments, we recommend SBD devices. For
details on disk-based SBD, read the product documentation for {sleha} and the
manual pages sbd(8) and stonith_sbd(7).
** For diskless SBD, you need at least three cluster nodes. The diskless SBD
mechanism has the benefit that you do not need a shared drive for fencing.
Since diskless SBD is based on self-fencing, reliable detection of lost quorum
is absolutely crucial.
** Priority fencing is an optional improvement for two nodes, but does not work
for three nodes.
* Both nodes are in the same network segment (layer 2). Similar methods provided
by cloud environments such as overlay IP addresses and load balancer functionality
are also fine. Follow the cloud specific guides to set up your {sles4sap} cluster.
* Technical users and groups, such as _{refsidadm}_ are defined
locally in the Linux system. If that is not possible, additional measures are needed
to ensure reliable resolution of users, groups and permissions at any time.
This might include caching.
* Name resolution of the cluster nodes and the virtual IP address must be done
locally on all cluster nodes. If that is not possible, additional measures are
needed to ensure reliable resolution of host names at any time.
* Time synchronization between the cluster nodes, such as NTP, is required.
* Both {HANA} instances of the system replication pair (primary and secondary)
have the same SAP Identifier (SID) and instance number.
* If the cluster nodes are installed in different data centers or data center
areas, the environment must match the requirements of the {sleha} cluster product.
Of particular concern are the network latency and recommended maximum distance
between the nodes. Review the product documentation for {sleha} about those
recommendations.
* Automated registration of a failed primary after takeover prerequisites need
to be defined.
** As a good starting configuration for projects, we recommend to switch off the
automated registration of a failed primary. The setup `AUTOMATED_REGISTER="false"`
is set as default. In this case, you need to register a failed primary after a takeover
manually. For re-registration, use precisely the site names that are already known
by the cluster. Use {SAP} tools like {HANA} cockpit or _hdbnsutil_.
** For optimal automation, we recommend to set `AUTOMATED_REGISTER="true"`.
* Automated start of {HANA} instances during system boot must be switched off.
* Multi-tenancy (MDC) databases are supported.
** Multi-tenancy databases can be used in combination with any other setup
(performance-optimized, cost-optimized, multi-tier, multi-target and read-enabled).
** In MDC configurations, the {HANA} RDBMS is treated as a single system including
all database containers. Therefore, cluster takeover decisions are based on the
complete RDBMS status independent of the status of individual database containers.
** Tests on Multi-tenancy databases can force a different test procedure if you
are using strong separation of the tenants.
As an example, killing the complete {HANA} instance using _HDB kill_ does not work,
because the tenants are running with different Linux user UIDs.
_{refsidadm}_ is not allowed to terminate the processes of the other tenant users.
* Only one system replication between the two {HANA} database in the Linux
cluster.  Maximum one system replication to an {HANA} database outside the Linux
cluster.
** Once an {HANA} system replication site is known to the Linux cluster, that exact
site name needs to be used whenever the site is registered manually.
** If a third {HANA} site is connected by system replication, that {HANA} is not
controlled by another Linux cluster. If that third site should work as part of a
fall-back HA cluster in DR case, that HA cluster needs to be in standby.
** The replication mode is either sync or syncmem for the controlled replication.
Replication mode async is not supported. The operation modes delta_datashipping,
logreplay and logreplay_readaccess are supported.
** See also the dedicated section on requirements for susHanaSR.py.
* The current resource agent supports {HANA} in system replication beginning with
{HANA} version 2.0 SPS05 revision 59.04.
Even in {HANA} multi-target environments, the current resource agent manages only
two sites. Thus only two {HANA} sites are part of the Linux cluster.
* Besides {HANA} you need {SAP} hostagent installed and started on your system.
// TODO remove: ** For SystemV style, the _sapinit_ script needs to be active.
* On {slesAbbr} {prodNr} only systemd style is supported. The service SAP<SID>_<INO> can stay enabled.
The systemd enabled saphostagent and instance´s sapstartsrv is supported.
Refer to the OS documentation for the systemd version.
{HANA} comes with native systemd integration as default starting with version 2.0 SPS07.
Refer to {SAP} documentation for information on other {HANA} versions.
// TODO remove: ** Combining systemd style hostagent with SystemV style instance is allowed.
// TODO remove: However, all nodes in one Linux cluster need to use the same style.
* The RA's monitoring operations need to be active.
* Using HA/DR provider hook for srConnectionChanged() by enabling susHanaSR.py is
mandatory.
* RA and HA/DR provider hook script´s runtime almost completely depends on call-outs
to controlled resources, OS and Linux cluster. The infrastructure needs to allow
these call-outs to return in time.
* Colocation constraints between the SAPHanaController RA and other resources are
allowed only if they do not affect the RA's scoring. The location scoring finally
depends on system replication status and must not be overruled by additional
constraints. Thus it is not allowed to define rules forcing an SAPHanaController
promoted clone to follow another resource.
* Reliable access to the /hana/shared/ file system is crucial for {HANA} and the
Linux cluster.
// TODO PRIO2: point to SAPHanaFilesystem RA
* {HANA} feature Secondary Time Travel is not supported.
* The {HANA} Fast Restart feature on RAM-tmpfs and {HANA} on persistent
memory can be used, as long as they are supported by the OS and transparent to Linux HA.
* No manual actions must be performed on the {HANA} database while it is controlled
by the Linux cluster. All administrative actions need to be aligned with the cluster.
* No firewall rules must block any needed port.
* No SELinux rules must block any needed action.
* Sizing of both {HANA} sites needs to be done according to SAP rules. The scale-up
scenarios require both sites to be prepared to run the primary {HANA} database.

// TODO PRIO3: align with manual pages SAPHanaSR(7) and susHanaSR.py(7)
For the HA/DR provider hook scripts _susHanaSR.py_ and _susTkOver.py_, the following
requirements apply:

* {HANA} 2.0 SPS05 revision 059.04 and later provides Python3 and the HA/DR
provider hook method *srConnectionChanegd()* with multi-target-aware parameters. 
Python 3 and multi-target-aware parameters are needed for the `{saphanasr}` package.
* {HANA} 2.0 SPS05 and later provides the HA/DR provider hook method *preTakeover()*.
// TODO PRIO1: check above version
* The user _{refsidadm}_ needs execution permission as user root for the command
_crm_attribute_.
* The hook provider needs to be added to the {HANA} global configuration, in memory
and on disk (in persistence).

For the HA/DR provider hook script _susChkSrv.py_, the following requirements apply:

* {HANA} 2.0 SPS05 or later provides the HA/DR provider hook method srServiceStateChanged()
with needed parameters.
* No other HA/DR provider hook script should be configured for the *srServiceStateChanged()*
method. Hook scripts for other methods, provided in SAPHanaSR can be used in
parallel to _susChkSrv.py_, if not documented otherwise.
* The user {refsidadm} needs execution permission as user root for the command
SAPHanaSR-hookHelper.
* The hook provider needs to be added to the {HANA} global configuration, in
memory and on disk (in persistence).
* The hook script runs in the {HANA} name server. It runs on the node where the
event *srServiceStateChanged()* occurs.
* If susChkSrv.py parameter action_on_lost=stop is set and the RA SAPHanaController
parameter AUTOMATED_REGISTER=true is set, it depends on HANA to release all OS
resources prior to the registering attempt.
* If the hook provider should be pre-compiled, the particular Python version that
comes with {HANA} needs to be used.

See also manual pages SAPHanaSR(7), susHanaSR.py(7), susTkOver.py(7) and
susChkSrv.py(7) for more details and requirements.

IMPORTANT: Without a valid fencing method, the complete cluster is unsupported
and will not work properly.

If you need to implement a different scenario, we strongly recommend to define
a Proof of Concept (PoC) with {SUSE}. This PoC will focus on testing the existing
solution in your scenario. Most of the above mentioned limitations are set
because careful testing is needed.
