[[suse-linux-enterprise-server-jeos-quick-start-guide]]
SUSE Linux Enterprise Server JeOS Quick Start Guide
---------------------------------------------------

(SUSE Linux Enterprise Server 12 SP4)

*draft for fate#325678 - [DOC] Adding JeOS in our official
documentation* Original content on Etherpad:

*Table of contents:* 1) Introduction 2) Differences to SLES X 2.1)
jeos-firstboot 2.2) Usage of kernel-default-base 2.3) Packages a) zypper
configuration b) List of preinstalled packages c) From JeOS to a full
SLES system 2.4) Disk layout a) Minor disk layout change due to the
small footprinted image size 2.5) Full disk layout description 2.6) List
of preinstalled packages 2.7) Specific hosts tools packages 3) Available
Image Flavors 3.1) Supported Virtualization Hosts (Hypervisors) a)
Specific hosts tools packages 3.2) Difference between KVM/XEN and XEN
images a) KVM/XEN b) XEN 3.3) OpenStack Cloud a) Disk layout b) Kernel
c) Packages list 3.4) KVM-XEN and XEN 3.5) MS HyperV 3.6) VMware 4)
Building Custom SLE X JeOS Images 5) Using JeOS 5.1) Getting SLE X JeOS
5.2) Starting SLE X JeOS 5.3) Logging In 5.4) Registering Your System
5.5) Docker Images Installing the Containers Module 6) FAQ

[[introduction]]
##Introduction
~~~~~~~~~~~~~~

In todays cloud environments and virtualized data centers, fast
deployment is critical to achieve operational efficiency. SUSE Linux
Enterprise Server JeOS provides you with a minimal form factor of SUSE
Linux Enterprise Server that is ready to run in virtualization
environment and cloud.

The term JeOS (“Just enough Operating System”) refers to a customizable
operating system that precisely fits the needs of a particular
application. It contains the very basic components of an operating
system. The major goal is to make the system as small as possible while
providing the possibility to install additional software. You can tailor
your systems for your data center, or create virtual application images
or appliances for simplicity and speed. You decide which packages and
elements to include based on your requirements—whether you are building
a virtual machine or an appliance or imaging a new server. For that
purspose, all of the usual repositories can be used, just like with a
regular, general-purpose and full-size Linux distribution.

SUSE Linux Enterprise JeOS is a customizable configuration of SUSE Linux
Enterprise designed as a bare minimum bootable image. It helps you meet
your customer’s needs and deliver an OS that reduces support costs and
enhances the user experience. If you are certified on SUSE Linux
Enterprise Server today, you do not need to re-certify for JeOS, as it
is based on the same code base. With SUSE Linux Enterprise JeOS, you can
trim the size of the operating system to only those packages that are
critical to your needs. This lowers the number of packages and patches
that have to be managed and applied. Further, the number of potential
vulnerabilities is substantially reduced as you remove unnecessary
packages. This improves the security of the operating system and overall
solution. The reduced footprint consumes fewer system resources,
improving performance for the end customer. SUSE Linux Enterprise JeOS
delivers all of this and more, allowing you to focus your time where it
matters most: your products.

In short, SUSE Linux Enterprise Server JeOS is a customizable,
lightweight configuration of SUSE Linux Enterprise with a minimal
installation footprint that provides only the functionality that you
need. It is easy to deploy and maintain, consumes fewer resources,
improves security, and offers better performance. To keep storage and
maintanance efforts low, it contains only the essential components of an
operating system. It can be customized as container host, virtual
machine guest, appliance base or small server image.

SUSE JeOS provides ready to deploy server images on the x86_64
architecture for:

* KVM/Xen with HVM
* Xen Paravirtualized
* Microsoft Hyper-V
* VMware
* OpenStack Cloud SUSE Linux Enterprise Server JeOS-specific key
features:
* Delivered as pre-installed and ready-to-run virtual machine images
* Contains a wizard (jeos-firstboot) to configure system locales and
root password at the first boot of the image
* Provides a minimal installation footprint: * Ships less packages
installed by default compared to a default SUSE Linux Enterprise Server
installation
* Enables for the creation of customized images:
** Kiwi templates (kiwi-templates) allow you to create your own
customized SUSE Linux Enterprise Server JeOS images
* Comes with SSH server enabled and excluded from firewall by default

[[system-requirements]]
System Requirements
^^^^^^^^^^^^^^^^^^^

*Minimum Linux server system requirements for installation* JeOS trims
unnecessary components down to keep the initial disk footprint size
small (about 300 MB) to save your time in deployment and configuration.
Depending on additional software added to the initial system, this size
can increase and will depend on your specific use case. To allow a save
start for your optimizations, SUSE Linux Enterprise Server system
requirements are listed.

....
   * Local Installation: 512 MiB RAM (1024 GiB RAM recommened), 512 MiB Swap recommended
   * 2 GiB available disk space (more recommended, 8.5 GiB for all patterns)
   * 16 GiB for snapshot/rollback of the OS
....

*_<(check the "system requirements" in the download page of JeOS (change
the content with PM -> vmoutoussamy (Dobrin)>_*

[[differences-to-suse-linux-enterprise-server-12-sp4]]
Differences to SUSE Linux Enterprise Server 12 SP4
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

[[jeos-firstboot]]
jeos-firstboot
^^^^^^^^^^^^^^

JeOS uses its own configuration tool for the first boot of the machine.
Some basic configuration parameters can be set here. Your user input is
requested for the acceptance of the following settings:

* EULA
* Language
* Keyboard layout
* Timezone
* Root password (root password is set by the user)
* In the background the network is initialized, and a Btrfs snapshot is
taken to save the initial default configuration. ### ###Usage of
kernel-default-base Because of size constraints, JeOS images use the
package "kernel-default-base" as the default kernel. This kernel does
not contain drivers for non-virtualized environments. This allows for a
much smaller footprint. However, if needed, you can manually install the
"kernel-default" to replace the "kernel-default-base".
* *SUSE Linux Enterprise Server 12 SP4 and SUSE Linux Enterprise Server
15*
* If your specific use case requires any of the omitted modules, you
need to manually install the package
* "kernel-default" to get a full tree of the kernel modules. Currently
there is no scheme in place to make this an
* automatic operation.
* 

[[packages]]
Packages
^^^^^^^^

....
zypper configuration
JeOS is a smaller form factor of SUSE Linux Enterprise Server. This means it has a smaller foot print but provides all the proper configurations
and capabilities to be transformed into a full SUSE Linux Enterprise Server operating system.
For achieving this smaller system, two configurations of zypper (/etc/zypp/zypp.conf) differ from the regular SUSE Linux Enterprise Server installation.

These different configurations JeOS uses are : 
    
....

* rpm.install.excludedocs = yes
* This excludes all files marked as documentation from being installed
by default.
* solver.onlyRequires = true
* Do not install suggested and recommended packages by default.
* 
* List of preinstalled packages The kiwi configuration files used to
create the official SUSE Linux Enterprise Server JeOS images are
available on build.opensuse.org. For instance you can check the packages
list for SUSE Linux Enterprise Server 15 JeOS:

*_<(provide 12SP4 list instead of 15 -> vmoutoussamy)>_*

To get a detailed list of the specific host tools packages

* open-vm-tools for VMWare
* hyper-v package for Hyper-V image *__*
+
From JeOS to a full SUSE Linux Enterprise Server System You can of
course make a JeOS images closer to a full SUSE Linux Enterprise Server
system by manually installing packages and patterns. For example, if you
want to add a Graphical Desktop Environnement, you can install either
GNOME or LXDE with the following command: zypper in
* #Describe further how to install the usual basic tools (Yast and the
like) and point to the regular documentation
* explaining how to install specific system modules and roles.
* 
* *_<(check with RPI guys, on how to phrase this section (install UI) ->
vmoutoussamy)>_* ###Disk layout
+
Minor disk layout change due to the small footprinted image size When
installing a regular SUSE Linux Enterprise Server, the disk layout is
calculated during the installation. Keep in mind that the disk layout
may vary. JeOS strives to be compatible with the original disk layouts.
Given the small footprint, a fixed geometry is installed in the virtual
images:
* For *SLE12-SP4* the disk layout is:
** 2Mb BIOS boot
** 20Mb EFI System
** 24Gb Linux filesystem
* For SLE15-SP1 layout is:
** 2Mb BIOS boot
** 33Mb EFI System
** 24Gb Linux filesystem For additional disk space, add a secondary disk
to the VM. *_<(double check numbers with requirement)>_*

[[full-disk-layout-description]]
Full disk layout description
^^^^^^^^^^^^^^^^^^^^^^^^^^^^

The kiwi configuration files used to create the official SUSE Linux
Enterprise Server JeOS images are available on build.opensuse.org. For
instance you can check the disk layouts for SUSE Linux Enterprise Server
15 JeOS:

*_<(replace SLE15 with SLE12SP4 links)>_*

[[available-image-flavors]]
Available Image Flavors
~~~~~~~~~~~~~~~~~~~~~~~

Ready-to-use SUSE Linux Enterprise Server JeOS images are currently
provided for the x86_64 architecture only. JeOS for x86-64 is available
as images for download for the following deployment targets:

....
   * JeOS for KVM and Xen
   * JeOS for VMware
   * JeOS for MicroSoft HyperV
   * JeOS for SUSE OpenStack Cloud
   * JeOS for Xen
....

* 

[[supported-virtualization-hosts-hypervisors]]
Supported Virtualization Hosts (Hypervisors)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

SUSE Linux Enterprise Server JeOS as a virtualization guest is supported
on the same supported Virtualization Hosts (Hypervisors) as SUSE Linux
Enterprise Server. Please check the Supported Virtualization Hosts of a
SUSE Linux Enterprise Server JeOS version with the corresponding SUSE
Linux Enterprise Server version.

For example, the hypervisors supported with SUSE Linux Enterprise Server
15 can be found in the product documentation at -> *_<(replace SLE15
with SLE12SP4 links)>_*

a.  Specific hosts tools packages Please check "*Specific hosts tools
packages*" in section "*Differences to SLES X*"

*__*

[[differences-between-kvmxen-and-xen-images]]
Differences between KVM/XEN and XEN images
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

....
(12SP4)


KVM/XEN:
kernelcmdline:
....

* plymouth.enable=0 console=ttyS0,115200 console=tty0

_ _ * * * * * * * * *

....
XEN
....

kernelcmdline: * plymouth.enable=0 console=tty0

_ _ * * * * * * * * * * * * * * * * * * * * * *

[[openstack-cloud]]
OpenStack Cloud:
^^^^^^^^^^^^^^^^

....
Disk layout:
....

filesystem="xfs"

....
Kernel:
....

kernelcmdline="plymouth.enable=0 console=ttyS0,115200 console=tty0
net.ifnames=0"

....
Packages list:
....

*Packages not included in the OpenStack Cloud images * As the OpenStack
Cloud images use XFS as file system instead fo BTRFS, the following
packages shipped with the images for the other deployment targets are
NOT included:

....
  ***<(OpenStack Cloud image uses XFS instead of BTRFS - do we really need to list the btrfs packages as "not in OpenStack Cloud?>***
....

*__*

* btrfsprogs
* btrfsmaintenance
* cron (needed by btrfsmaintenance)
* grub2-snapper-plugin (snapper - grub2 - integration, "small")
* snapper-zypp-plugin (this is key snapper/zypp integration, as
requested in the PRD)
* rollback-helper
* snapper *_<(cron still included in openstack? ->vmoutoussamy)>_*

In addition, OpenStack Cloud images use cloud-init instead of
jeos-firstboot. This means the following packages are also not included:

* jeos-firstboot
* fbiterm +
There are some packages which are specific to OpenStack Cloud images
* cloud-init
* cloud-init-config-suse
* xfsprogs ###KVM-XEN and XEN

Packages specific to KVM/XEN and XEN are:

* xen-tools-domU
* grub2-x86_64-xen
* xen-libs ###MS Hyper-V

Packages specific to MicroSoft Hyper-V are:

* hyper-v ###VMware: Packages specific to VMware are:
* open-vm-tools *_<(check if we can use the xml config file format for
this kind of info -> vmoutoussamy)>_*

*_<(starting with this section, think about possible screenshot/graphics
and note them here -> vmoutoussamy)>_*

[[building-custom-suse-linux-enterprise-server-x-jeos-images]]
Building Custom SUSE Linux Enterprise Server X JeOS Images:
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

 * Support status * can these templates be used to build images for a
different architecture? (Yes, but untested and only with more than
trivial changes)

The templates used to build the official ready-to-use SUSE Linux
Enterprise Server 12 JeOS images are available from the package
"kiwi-templates-SLES12-JeOS" which can be obtained from *_???_*. Having
installed this package, the templates can be found in the following
directory

/usr/share/kiwi/image/suse-SLE12-Enterprise-JeOS/

Detailed instructions on how to customize the templates and build the
images are provided with the KIWI documentation. You can find the
documentation online at . You can also make the documentation available
locally by installing the package "kiwi-doc".

*_<(It's actually not possible to build JeOS (without changes) outside
of OBS currently)>_* *_<(Poke Fabian about more detail in this section
-> vmoutoussamy)>_*

[[using-jeos]]
Using JeOS:
~~~~~~~~~~~

[[getting-suse-linux-enterprise-server-12-sp4-jeos]]
Getting SUSE Linux Enterprise Server 12 SP4 JeOS:
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

*__* * Where to get SLE 12 SP4 JeOS * How/where to get the different
flavors *__* *_ vmoutoussamy>_*

[[starting-suse-linux-enterprise-server-12-sp4-jeos]]
Starting SUSE Linux Enterprise Server 12 SP4 JeOS
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Please refer to your Hypervisor documentation on how to start a virtual
machine based on an existing image.

[[firstboot]]
firstboot
^^^^^^^^^

*** < (screenshot (png) are important HERE for both -> vmoutoussamy)>**_
The jeos-firstboot will ask you for a root password during the firstboot
of the JeOS image. _** ***

However for the OpenStack Cloud images, the root password is not set at
all and SHOULD be set via cloud-init. We suggest you to set it
immediately. *_<(provide the cloud-init link -> vmoutoussamy (maybe a
second step would be to produce our own for JEOS (based on cloud team
feedback))>_*

[[registering-your-system]]
Registering Your System:
^^^^^^^^^^^^^^^^^^^^^^^^

*_<(jeos and SLES are similar in regard of registration - for now c&p
the SLES installation procedure from existing guide)>_* *_<(difference
between SLES and JEOS -> SLES has the installation media as the default
offline channel, JeOS has NO channel by default, you need to register
first)>_*

Registering your system gives you access to updates and security fixes
for SUSE Linux Enterprise Server 12 and is a prerequisite to be eligible
for support. Register the image by either using your existing SUSE
entitlement . To register the system run the following command from
within the running JeOS:

sudo SUSEConnect -e -r

Replace with the e-mail address from your organization's account at the
SUSE Customer Center (SCC). Replace with a valid registration code.

*__*

IMPORTANT: Images started with "qemu" on a SLES 12 host
.................................................. In case you start an
image directly with "qemu-kvm" on a SUSE Linux Enterprise Server12 host,
the virtual BIOS will not provide a system UUID. Such a UUID is used
when registering systems with "SUSEConnect". In case a system is
registered without a UUID, it cannot be properly tracked and may not
have access to all repositories. Therefore it is recommended to provide
a UUID on the "qemu-kvm" command line: qemu-kvm -smbios type=1,uuid=

A simple MYUUID could look like this:
00000000-0000-0000-0000-$\{VIRTUALMACADDRESS}

Note that this problem does not occur when starting virtual machines
with libvirt (recommended). Newer version of qemu (for example the one
shipped with SUSE Linux Enterprise Server 12 SP1) do not have this
problem either.

*__* *_ vmoutoussamy >_*

[[docker-images-installing-the-containers-module-bonus-not-an-issue-if-not-in-the-final-doc-for-12sp4]]
Docker Images: Installing the Containers Module (BONUS! not an issue if
not in the final doc for 12SP4)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

*__* * We do not have a Docker flavor nor a template, so this section is
IMHO completely out of context. How are customers supposed to get/create
a Docker image? * Is this module required to build Docker images? I
would have imagined that it only adds Docker support to an existing
(bare metal) SLE 12 installation. +
Again, I am lacking context. * Is this module available for other
architectures apart from x86_64

*__* Users can use JeOS as a host for Docker containers (as described
below), but that's is. JeOS is a VM image, not an Docker image. To
install the Containers Module, run the following command after you have
registered your system:

sudo SUSEConnect -p sle-module-containers/12/x86_64

[[faq]]
FAQ
~~~

<(nice idea but maybe not in the quickstart, let's think about it)>

* When we have certain SLES version certified, the same version of JeOS
is automatically certified too?
* Is there any extra differences in between SLES and JeOS? Meaning JeOS
has anything that is not in SLES? NOTES for documentation/Wiki: If you
want to use JeOS image as a SCSI controller attached disk you will need
to use any of the VMware tools capable of converting disks. If you have
control over the server this can be as basic as running from the ssh
shell available in ESXi:

vmkfstools -i SLES15-JeOS.x86_64-15.0-VMware-Build.vmdk
jeos-converted-image.vmdk

This will clone the disk in a VMFS type thin provisioned disk, using
this converted image with a configuration compatible with your needs
(e.g. lsilogic controller) should work. The system will easily recognise
a disk attached to any controller and do the appropriate initialization.
(Note) The image can still hold in the DDB(metadata of the disk)
ddb.adapterType = "ide", but that seems to be ignored by VMware given
priority to whatever is in the .vmx configuration.

We keep the default in JeOS as IDE to keep it as compatible as possible,
given that the format we convert right now (monolithicsparse) is not
compatible with all controllers in all versions.

Note on file sizes: When you convert an image using vmkfstools it should
by default make the image a thin provisioned image, meaning that besides
the size of the file it will NOT take all the space in the datastore
(similar to a sparse file) as opposed to thick provisioning where all
the space of the VDMK filesystem is allocated in the datastore, so the
size of the image shouldn't be a problem if the datastore is properly
configured.

Note on IDE vs SCSI: The image itself is not constructed in a IDE only
mode, the choice of disk controller is made outside of the image by the
configuration of the hypervisor, the linux kernel will only see the
defined controller and the disk attached to it like it was real
hardware. What that means in practice is that if you are able to attach
the vmdk and start the VM with a SCSI controller you are already using
the image as a SCSI disk.

TODO: Possibly comments on ESXi 5 vs ESXi 6
