// Load document variables
:prodNr: 16
:pMinor16: 0
include::Var_SLES4SAP-{prodNr}.txt[]
include::Var_SLES4SAP-hana-angi-{prodNr}.txt[]
include::Var_SLES4SAP-hana-angi-param-{prodNr}.txt[]
[[app.hana-sr.example]]
== Examples

// TODO PRIO1: "replace ha-cluster-init" by "crm cluster init"

=== Example `{slehainit}` configuration

[subs="attributes,quotes"]
----
{sapnode1}:~ # ha-cluster-init -u
  Generating SSH key
  Configuring csync2
  Generating csync2 shared key (this may take a while)...done
  csync2 checking files...done

Configure Corosync (unicast):
  This will configure the cluster messaging layer.  You will need
  to specify a network address over which to communicate (default
  is eth0's network, but you can use the network address of any
  active interface).

  Address for ring0 [{sapip1node1}]
  Port for ring0 [5405]

Configure SBD:
  If you have shared storage, for example a SAN or iSCSI target,
  you can use it avoid split-brain scenarios by configuring SBD.
  This requires a 1 MB partition, accessible to all nodes in the
  cluster.  The device path must be persistent and consistent
  across all nodes in the cluster, so /dev/disk/by-id/* devices
  are a good choice.  Note that all data on the partition you
  specify here will be destroyed.

Do you wish to use SBD (y/n)? y
  Path to storage device (e.g. /dev/disk/by-id/...), or "none" []{sapsbd1}
WARNING: All data on {sapsbd1} will be destroyed!
Are you sure you wish to use this device (y/n)? y
  Initializing SBD......done
  Hawk cluster interface is now running. To see cluster status, open:
    https://{sapip1node1}:7630/
  Log in with username 'hacluster', password 'linux'
You should change the hacluster password to something more secure!
  Waiting for cluster........done
  Loading initial cluster configuration

Configure Administration IP Address:
  Optionally configure an administration virtual IP
  address. The purpose of this IP address is to
  provide a single IP that can be used to interact
  with the cluster, rather than using the IP address
  of any specific cluster node.

Do you wish to configure a virtual IP address (y/n)? n
  Done (log saved to /var/log/ha-cluster-bootstrap.log)
----

// DO NOT CHANGE AUTOGENERATED SECTION ID: id-example-cluster-configuration
// DO NOT CHANGE SECTION TITLE as this would change autogenerated section ID
// Refer to Trento check
=== Example cluster configuration

The following complete progressive crm configuration is for a two-node cluster
({sapnode1}, {sapnode2}) and an {HANA} database with SID {sapsid}
and instance number {sapino}. A failed primary will be automatically registered
as secondary after reboot.
Priority fencing prefers the {HANA} primary in case of split-brain.
The virtual IP address in the example is {sapip1srv1}.

[subs="attributes,quotes"]
----
node {sapnode1}
node {sapnode2}

primitive rsc_SAPHanaTop_{sapsid}_HDB{sapino} ocf:suse:SAPHanaTopology \
    op start interval=0 timeout=600 \
    op stop interval=0 timeout=300 \
    op monitor interval=50 timeout=600 \
    params SID={sapsid} InstanceNumber={sapino}

primitive rsc_SAPHanaFil_{sapsid}_HDB{sapino} ocf:suse:SAPHanaFilesystem \
    op start interval=0 timeout=10 \
    op stop interval=0 timeout=20 \
    op monitor interval=120 timeout=120 \
    params SID={sapsid} InstanceNumber={sapino} \
        ON_FAIL_ACTION=fence

primitive rsc_SAPHanaCon_{sapsid}_HDB{sapino} ocf:suse:SAPHanaController \
    op start interval=0 timeout=3600 \
    op stop interval=0 timeout=600 \
    op promote interval=0 timeout=900 \
    op demote interval=0 timeout=320 \
    op monitor interval=60 role=Promoted timeout=700 \
    op monitor interval=61 role=Unpromoted timeout=700 \
    params SID={sapsid} InstanceNumber={sapino} \
        PREFER_SITE_TAKEOVER=true DUPLICATE_PRIMARY_TIMEOUT=7200 \
        AUTOMATED_REGISTER=true ON_FAIL_ACTION=fence \
    meta priority=100

primitive rsc_ip_{sapsid}_HDB{sapino} ocf:heartbeat:IPaddr2 \
    op monitor interval=10 timeout=20 \
    params ip={sapip1srv1}

primitive stonith-sbd stonith:fence_sbd \
    params pcmk_delay_max=15

clone mst_SAPHanaCon_{sapsid}_HDB{sapino} rsc_SAPHanaCon_{sapsid}_HDB{sapino} \
    meta clone-node-max=1 interleave=true promotable=true

clone cln_SAPHanaTop_{sapsid}_HDB{sapino} rsc_SAPHanaTop_{sapsid}_HDB{sapino} \
    meta clone-node-max=1 interleave=true

clone cln_SAPHanaFil_{sapsid}_HDB{sapino} rsc_SAPHanaFil_{sapsid}_HDB{sapino} \
    meta clone-node-max=1 interleave=true

colocation col_saphana_ip_{sapsid}_HDB{sapino} 2000: \
    rsc_ip_{sapsid}_HDB{sapino}:Started mst_SAPHanaCon_{sapsid}_HDB{sapino}:Promoted

order ord_saphana_{sapsid}_HDB{sapino} Optional: \
    cln_SAPHanaTop_{sapsid}_HDB{sapino} mst_SAPHanaCon_{sapsid}_HDB{sapino}

property cib-bootstrap-options: \
    cluster-infrastructure=corosync \
    stonith-enabled=true \
    stonith-action=reboot \
    stonith-timeout=150 \
    priority-fencing-delay=30

rsc_defaults rsc-options: \
    resource-stickiness=1000 \
    migration-threshold=5000

op_defaults op-options \
    timeout=600 \
    record-pending=true
----

// DO NOT CHANGE AUTOGENERATED SECTION ID: id-example-for-etccorosynccorosync-conf
// DO NOT CHANGE SECTION TITLE as this would change autogenerated section ID
// Refer to Trento checks
// Refer to Trento checks
=== Example for _/etc/corosync/corosync.conf_

The following file shows a typical corosync configuration with two rings.
Review the SUSE product documentation about details.
See also manual pages corosync.conf(5) and votequorum(5).
// TODO PRIO3: get corosync.conf from common include file

[subs="attributes,quotes"]
----
# Read the corosync.conf.5 manual page
totem {
    version: 2
    secauth: on
    crypto_hash: sha1
    crypto_cipher: aes256
    cluster_name: suse-ha
    clear_node_high_bit: yes
    token: 5000
    token_retransmits_before_loss_const: 10
    join: 60
    consensus: 6000
    max_messages: 20
    interface {
        ringnumber: 0
        mcastport: 5405
        ttl: 1
    }
    interface {
        ringnumber: 1
        mcastport: 5407
        ttl: 1
    }
    rrp_mode: passive
    transport: udpu
}

logging {
    fileline: off
    to_stderr: no
    to_logfile: no
    logfile: /var/log/cluster/corosync.log
    to_syslog: yes
    debug: off
    timestamp: on
    logger_subsys {
        subsys: QUORUM
        debug: off
    }
}

nodelist {
    node {
            ring0_addr: {sapIp1Node1}
            ring1_addr: {sapIp2Node1}
            nodeid: 1
    }
    node {
            ring0_addr: {sapIp1Node2}
            ring1_addr: {sapIp2Node2}
            nodeid: 2
    }
}

quorum {
        provider: corosync_votequorum
        expected_votes: 2
        two_node: 1
}
----

=== Examples for alternate STONITH methods

==== Example for deterministic SBD STONITH

These SBD resources make sure that node {sapnode1} will win in case of split-brain.

[subs="attributes,quotes"]
----
primitive rsc_sbd_{sapnode1} stonith:external/sbd \
    params pcmk_host_list={sapnode2} pcmk_delay_base=0

primitive rsc_sbd_{sapnode2} stonith:external/sbd \
    params pcmk_host_list={sapnode1} pcmk_delay_base=30
----

[[cha.hanasr-example-ipmi]]
==== Example for the IPMI STONITH method

[subs="attributes,quotes"]
----
primitive rsc_{sapnode1}_stonith stonith:external/ipmi \
    params hostname="{sapnode1}" ipaddr="{sapip1ipmi1}" userid="stonith" \
    passwd="k1llm3" interface="lanplus" \
    op monitor interval=1800 timeout=30
    ...
primitive rsc_{sapnode2}_stonith stonith:external/ipmi \
    params hostname="{sapnode2}" ipaddr="{sapip1ipmi2}" userid="stonith" \
    passwd="k1llm3" interface="lanplus" \
    op monitor interval=1800 timeout=30
    ...
location loc_{sapnode1}_stonith rsc_{sapnode1}_stonith -inf: {sapnode1}
location loc_{sapnode2}_stonith rsc_{sapnode2}_stonith -inf: {sapnode2}
----

////
// TODO remove: [[cha.hanasr-example-systemv]]
// TODO remove: === Example for checking legacy SystemV integration
//
// TODO remove: include::SLES4SAP-hana-systemv-appendix.adoc[]
////

++++
<?pdfpagebreak?>
++++
