// Alertmanager adoc file
// Please use the following line to implement each tagged content to the main document:
// include::SLES4SAP-sap-infra-monitoring-alertmanager.adoc[tag=alert-XXXXX]

// Alertmanager general
# tag::alert-general[]
===== Alertmanager

The  https://prometheus.io/docs/alerting/latest/alertmanager/[Alertmanager] handles alerts sent by client applications such as the Prometheus or Loki server.
It takes care of deduplicating, grouping, and routing them to the correct receiver integration such as email or PagerDuty. It also takes care of
silencing and inhibition of alerts.
# end::alert-general[]


// Alertmanager Implementing
# tag::alert-impl[]
=== Alertmanager
The Alertmanager package can be found in the PackageHub repository.
The repository needs to be activated via the SUSEConnect command first, unless you have activated it in the previous steps already.


[source]
----
SUSEConnect --product PackageHub/15.3/x86_64
----

Alertmanager can then be installed via the `zypper` command:
[subs="attributes,specialchars,verbatim,quotes"]
----
zypper in  golang-github-prometheus-alertmanager
----


Notification can be done to different receivers. A receivers can be simply be an email, chat systems, webhooks and more. 
(for a complete list please take a look at the https://prometheus.io/docs/alerting/latest/configuration/#receiver[Alertmanager documentation]) +


The example configuration below is using email for notification (receiver). +


Edit the Alertmanager configuration file `/etc/alertmanager/config.yml` like below: +

[subs="attributes,specialchars,verbatim,quotes"]
----
global:
  resolve_timeout: 5m
  smtp_smarthost: '<mailserver>'
  smtp_from: '<mail-address>'
  smtp_auth_username: '<username>'
  smtp_auth_password: '<passwd>'
  smtp_require_tls: true

route:
  group_by: ['...']
  group_wait: 10s
  group_interval: 5m
  repeat_interval: 4h
  receiver: 'email'

receivers:
  - name: 'email'
    email_configs:
      - send_resolved: true
        to: '<target mail-address>'
        from: 'mail-address>'
        headers:
          From: <mail-address>
          Subject: '{{ template "email.default.subject" . }}'
          html: '{{ template "email.default.html" . }}'
----


[subs="attributes,specialchars,verbatim,quotes"]
Start and enable the alertmanager service:
----
systemctl enable --now prometheus-alertmanager.service
----

# end::alert-impl[]