// Load document variables
:prodNr: 16
:pMinor16: 0
include::Var_SLES4SAP-{prodNr}.txt[]
include::Var_SLES4SAP-hana-angi-{prodNr}.txt[]
include::Var_SLES4SAP-hana-angi-param-{prodNr}.txt[]
[[cha.s4s.configure-cluster]]
== {stepCluster}

image::SAPHanaSR-ScaleOut-Plan-Phase6.svg[scaledwidth="100%"]

This chapter describes the configuration of the cluster software {sleha}, which
is part of {sles4sap}, and the {saphana} database integration.

.Actions
. Basic cluster configuration

. Configuration of cluster properties and resources

. Testing the HA/DR provider hook integration

// TODO PRIO2: Describe the hook test (for example restart secondary) to trigger the write of cluster attributes

=== Configuring the basic cluster

The first step is to set up the basic cluster framework. For convenience, use 
the crmsh command `{slehainit}` . 

// TODO PRIO1: Actions needed after crm init? It is strongly recommended to add a second corosync ring,
// change it to UCAST communication and adjust the timeout values to fit your environment.

==== Setting up watchdog for SBD fencing

// TODO PRIO2: Should we add some more information here?

If you use the storage-based fencing (SBD) mechanism (diskless or disk-based),
you must also configure a watchdog. The watchdog is needed to reset a node if
the system cannot longer access the SBD (diskless or disk-based).
It is mandatory to configure the Linux system for loading a watchdog driver.
It is strongly recommended to use a watchdog with hardware assistance (as is
available on most modern systems), such as hpwdt, iTCO_wdt, or others. As fallback,
you can use the softdog module.

.Setup for Watchdog

IMPORTANT: Access to the watchdog timer:
No other software must access the watchdog timer; it can only be accessed by one
process at any time. Some hardware vendors ship systems management software that
use the watchdog for system resets. Such software must
be disabled if the watchdog is to be used by SBD.

Determine the right watchdog module. Alternatively, you can find a list of installed
drivers with your kernel version.

----
# ls -l /lib/modules/$(uname -r)/kernel/drivers/watchdog
----

Check if any watchdog module is already loaded.

----
# lsmod | egrep "(wd|dog|i6|iT|ibm)"
----

If you get a result, the system has already a loaded watchdog. If the watchdog
does not match your watchdog device, you need to unload the module.

To safely unload the module, check first if an application is using the watchdog device.

----
# lsof /dev/watchdog
# rmmod <wrong_module>
----

Enable your watchdog module and make it persistent. For the example below, _softdog_
has been used. However, _softdog_ has some restrictions and should not be used as
first option.

----
# echo softdog > /etc/modules-load.d/watchdog.conf
# systemctl restart systemd-modules-load
----

Check if the watchdog module is loaded correctly.

----
# lsmod | grep dog
# ls -l /dev/watchdog
# systool -vc watchdog
----

Testing the watchdog can be done with a simple action. Make sure to stop your {HANA}
first, because the watchdog will force an unclean reset or shutdown of your system.

IMPORTANT: Triggering the watchdog without continuously updating the watchdog
resets/switches off the system. This is the intended mechanism. The following
commands will force your system to be reset/switched off.

The following action will activate the watchdog without feeding it and should cause
a reset/switch off:

----
# sync; cat /dev/watchdog & while date; do sleep 10; done
----
// # touch /dev/watchdog
// # echo 1 > /dev/watchdog

After your test was successful, you must implement the watchdog on all cluster members.

// DO NOT CHANGE AUTOGENERATED SECTION ID: id-setting-up-the-initial-cluster-using-ha-cluster-init
// DO NOT CHANGE SECTION TITLE as this would change autogenerated section ID
// Refer to Trento check
==== Setting up the initial cluster using `{slehainit}`

For more detailed information about setting up a cluster, refer to the sections
_Setting Up the First Node_ and _Adding the Second Node_ of the {dochaquickstart}
for {sleha} {pn16} {pm16} at {haquickstart16}.

This setup uses knet for corosync communication. Refer
to the {haAdminGuide16} on detailed explanations of the term knet.

Create an initial setup, using the `{slehainit}` command, and follow the
dialogs. Do this only on the first cluster node. Answer "no" to "Do you wish to
configure a virtual IP address" and to "Do you want to configure QDevice".

// TODO PRIO1: Check, if two corosync rings are still valid
To use two corosync rings make sure you have two interfaces configured and run:

[subs="specialchars,attributes,quotes"]
----
{sapnode1}:~ # {slehainit} -s {sapsbd1} -s {sapsbd2}
----

// TODO PRIO2: for disk less SBD: {slehainit} -u -S

This command configures the basic cluster framework including:

* SSH keys
* csync2 to transfer configuration files
* SBD (two in this guide, better three for production)
* corosync (at least one ring, better two rings)

IMPORTANT: As requested by `{slehainit}`, change the password of the user hacluster.

// DO NOT CHANGE AUTOGENERATED SECTION ID: id-checking-and-adapting-the-corosync-and-sbd-configuration
// DO NOT CHANGE SECTION TITLE as this would change autogenerated section ID
// Refer to Trento checks
==== Checking and adapting the corosync and SBD configuration

//It is recommended to add a second corosync ring. If you did not start {slehainit}
//with the _-u_ option, you need to change corosync to use UCAST communication.
//To change to UCAST, stop the already running cluster by using `{clusterstop}`.
//After the setup of the corosync configuration and the SBD parameters, start the cluster again.
===== Checking the corosync configuration

Check the following blocks in the file _/etc/corosync/corosync.conf_.
The important parts are _knet_ and the correct ring/IP configuration.

See also the example at the end of this document and refer to the manual pages
corosync.conf(5), votequorum(5) and corosync_overview(8) for details on parameters
and features.

// TODO PRIO1: Check, if two corosync rings are still valid

[subs="attributes,quotes"]
----
totem {
    ...
    transport: knet
    ...
}

nodelist {
    node {
            ring0_addr: {sapIp1Node1}
            ring1_addr: {sapIp2Node1}
            name: {sapnode1}
            nodeid: 1
    }
  
    node {
            ring0_addr: {sapIp1Node2}
            ring1_addr: {sapIp2Node2}
            name: {sapnode2}
            nodeid: 2
    }
}
    ...
----

// DO NOT CHANGE AUTOGENERATED SECTION ID: id-adapting-the-sbd-configuration
// DO NOT CHANGE SECTION TITLE as this would change autogenerated section ID
// Refer to Trento checks
===== Adapting the SBD configuration

// TODO PRIO2: Should we add some information about SBD timing tunables?

You can skip this section if you do not have any SBD devices, but be sure to
implement another supported fencing mechanism.

See the manual pages sbd(8) and stonith_sbd(7) for details.

.SBD Options in File /etc/sysconfig/SBD
[cols=",",options="header",]
|=======================================================================
|Parameter |Description
|SBD_WATCHDOG_DEV|
Define the watchdog device. It is mandatory to use a watchdog. SBD does not work
reliable without watchdog. Refer to the {slsa} manual and SUSE
TID 7016880 for setting up a watchdog.

|SBD_WATCHDOG_TIMEOUT|
This parameter is used with diskless SBD.
It defines the timeout, in seconds, the watchdog will wait before panicking the
node if noone tickles it. The value of fencing-watchdog-timeout in CIB should
be more than twice the value of SBD_WATCHDOG_TIMEOUT.

|SBD_STARTMODE|
Start mode. If set to `clean`, sbd will only start if the node was
previously shut down cleanly or if the slot is empty.

|SBD_DELAY_START|
Whether to delay after starting sbd on boot. Should be `no` for SBD_STSRTMODE
`clean`.

|SBD_PACEMAKER|
Check Pacemaker quorum and node health.

|=======================================================================

In the following, replace {sapsbd1} and {sapsbd2} by your real sbd
device names. As an example, the SBD_WATCHDOG_TIMEOUT is set to 20s.

[subs="attributes,quotes"]
----
# egrep -v "(\^#|^$)" /etc/sysconfig/sbd
SBD_PACEMAKER="yes"
SBD_STARTMODE="clean"
SBD_DELAY_START="no"
SBD_WATCHDOG_DEV="/dev/watchdog"
SBD_WATCHDOG_TIMEOUT="20"
SBD_TIMEOUT_ACTION="flush,reboot"
SBD_MOVE_TO_ROOT_CGROUP="auto"
SBD_OPTS=""
SBD_DEVICE="{sapsbd1};{sapsbd2}"
----

IMPORTANT: Also read the SUSE product documentation about calculation of timeouts
for more details:
https://documentation.suse.com/sle-ha/16.{prodMinor}/html/HA-sbd-configuring-diskbased/index.html#ha-sbd-setting-up-watchdog


// DO NOT CHANGE AUTOGENERATED SECTION ID: id-verifying-the-sbd-device
// DO NOT CHANGE SECTION TITLE as this would change autogenerated section ID
// Refer to Trento check
===== Verifying the SBD device

You can skip this section if you do not have any SBD devices, but make sure to
implement a supported fencing mechanism.

It is a good practice to check if the SBD device can be accessed from both nodes
and does contain valid records. Check this for all devices configured in
_/etc/sysconfig/sbd_. You can do so, for example, by calling `cs_show_sbd_devices`.

[subs="attributes,quotes"]
----
{sapnode1}:~ # sbd -d {sapsbd1} -d {sapsbd2} dump
==Dumping header on disk {sapsbd1}
Header version     : 2.1
UUID               : 0f4ea13e-fab8-4147-b9b2-3cdcfff07f86
Number of slots    : 255
Sector size        : 512
Timeout (watchdog) : 20
Timeout (allocate) : 2
Timeout (loop)     : 1
Timeout (msgwait)  : 40
==Header on disk {sapsbd1} is dumped
==Dumping header on disk {sapsbd2}
Header version     : 2.1
UUID               : 23c423df-675d-4937-a48c-5eb869fe0bb7
Number of slots    : 255
Sector size        : 512
Timeout (watchdog) : 20
Timeout (allocate) : 2
Timeout (loop)     : 1
Timeout (msgwait)  : 40
==Header on disk {sapsbd2} is dumped
----

// TODO PRIO3: Check if we need to explain the timeout parameters of the sbd device (watchdog, allocate, loop, msgwait)

IMPORTANT: The timeout values in our example are only start values.
It is a requirement that they are tuned to your environment. Refer to the
TIDs 7011346 and 7023689 for more information.

To check the current SBD entries for the various cluster nodes, you can
use `sbd list`. If all entries are `clear`, no fencing task is marked in
the SBD device.

[subs="attributes,quotes"]
----
{sapnode1}:~ # sbd -d {sapsbd1} -d {sapsbd2} list
0     {sapnode1}      clear
0     {sapnode1}      clear
----

For more information on SBD configuration parameters, consult the respective sections
of the SUSE Linux Enterprise High Availability Administration Guide and the
TIDs 7016880 and 7008216.

Now it is time to restart the cluster at the first node again (`{clusterstart}`).

==== Configuring the cluster on the second node

The second node of the two nodes cluster can be integrated by starting the command
`{slehajoin}`. This command asks for the IP address or name of the first cluster
node. With this command, all needed configuration files are copied over. As a result,
the cluster is started on both nodes.

[subs="specialchars,attributes,quotes"]
----
# {slehajoin} -c {refHost1}
----

Press _RETURN_ to acknowledge the IP address.

==== Checking the cluster for the first time

Now it is time to check and optionally start the cluster for the first
time on both nodes.

[subs="attributes,quotes"]
----
{sapnode1}:~ # {clusterstatus}
{sapnode1}:~ # {sbdstatus}
{sapnode2}:~ # {clusterstatus}
{sapnode2}:~ # {sbdstatus}
{sapnode1}:~ # {clusterstart}
{sapnode2}:~ # {clusterstart}
----

Check the cluster status with crm_mon. We use the option "-r" to also
see resources, which are configured but stopped.

[subs="attributes,quotes"]
----
# crm_mon -r1
----

The command will show the "empty" cluster and will print something similar to the
screen output below. The most interesting pieces of information for now are that
there are two nodes in the status "online", the message "partition with quorum",
and a running SBD resource.

[subs="attributes,quotes"]
----
Cluster Summary:
  * Stack: corosync (Pacemaker is running)
  * Current DC: {sapnode1} (version 3.0.2+20260429.40d19b75-160099.1.8-3.0.2+20260429.40d19b75) - partition with quorum
  * Last updated: Fri Jul 24 15:05:26 2026 on {sapnode1}
  * Last change:  Tue Jul 14 13:36:53 2026 by hacluster via crmd on {sapnode1}
  * 2 nodes configured
  * 1 resource instance configured

Node List:
  * Online: [ {sapnode1} {sapnode2}  ]

Full List of Resources:
  * fencing-sbd	(stonith:fence_sbd):	 Started {sapnode1}
----

=== Configuring cluster properties and resources

This section describes how to configure constraints, resources, bootstrap, and fencing,
using the `crm configure` shell command as described in part II _Configuration and Administration_
of the {sleha} Administration Guide.

Use the command `crm` to add the objects to the cluster information base (CIB). Copy the following
examples to a local file, edit the file and then load the configuration to the CIB:

[subs="attributes,quotes"]
----
{sapnode1}:~ # vi crm-fileXX
{sapnode1}:~ # crm configure load update crm-fileXX
----

// DO NOT CHANGE AUTOGENERATED SECTION ID: id-cluster-bootstrap-and-more
// DO NOT CHANGE SECTION TITLE as this would change autogenerated section ID
// Refer to Trento checks
==== Cluster bootstrap and more

The first example defines the cluster bootstrap options, the resource
and operation defaults. The fencing-timeout should be greater than 1.2
times the SBD on-disk msgwait timeout. The priority-fencing-delay should be
at least 2 times the SBD CIB pcmk_delay_max.

[subs="attributes,quotes"]
----
{sapnode1}:~ # vi crm-bs.txt
# enter the following to crm-bs.txt
property cib-bootstrap-options: \
    fencing-enabled="true" \
    fencing-action="reboot" \
    fencing-timeout="150" \
    priority-fencing-delay="30"
rsc_defaults build-resource-defaults: \
    resource-stickiness="1000" \
    migration-threshold="5000"
op_defaults op-options: \
    timeout="600" \
    record-pending=true
----

Now add the configuration to the cluster.

[subs="attributes,quotes"]
----
{sapnode1}:~ # crm configure load update crm-bs.txt
----

==== Fencing device

Skip this section if you are using diskless SBD.

The next configuration part defines an SBD disk fencing resource.

[subs="attributes,quotes"]
----
{sapnode1}:~ # vi crm-sbd.txt
# enter the following to crm-sbd.txt
primitive fencing-sbd stonith:fence_sbd \
        params pcmk_delay_max=15
----

Again we add the configuration to the cluster.

[subs="attributes,quotes"]
----
{sapnode1}:~ # crm configure load update crm-sbd.txt
----

// TODO PRIO1: check if IPMI still is supported / makes sense

For fencing with IPMI/ILO see section <<Using IPMI as fencing mechanism>>.

==== Using IPMI as fencing mechanism

For details about IPMI/ILO fencing see our cluster product documentation ({haAdminGuide16}).
An example for an IPMI fencing resource can be found in section <<Example for the IPMI fencing method>>
of this document.

To use IPMI, the remote management boards must be compatible with the IPMI standard.

For the IPMI-based fencing, configure a primitive per-cluster
node. Each resource is responsible to fence exactly one cluster node.
Adapt the IP addresses and login user / password of the
remote management boards to the fencing resource agent. We recommend to
create a special fencing user instead of providing root access to the
management board. Location rules must guarantee that a host should never
run its own fencing resource.

==== Using other fencing mechanisms

This section is only relevant if the recommended disk-based or diskless SBD fencing is not used.

We recommend to use SBD (best practice) or IPMI (second choice) as fencing mechanism.
The {sleha} product also supports additional fencing mechanism not covered here.

For further information about fencing, read the Administration Guide for {sleha} at {haAdminGuide16}. For public cloud environments, refer to your
cloud provider's documentation on supported fencing mechanisms.

==== SAPHanaTopology

This step is to define the resources needed, to analyze the {HANA} topology for the replicated pair.
Prepare the changes in a text file, for example _crm-saphanatop.txt_, and load it with the command:

`crm configure load update crm-saphanatop.txt`

[subs="attributes,quotes"]
----
{sapnode1}:~ # vi crm-saphanatop.txt
# enter the following to crm-saphanatop.txt
primitive rsc_SAPHanaTop_{sapsid}_HDB{sapino} ocf:suse:SAPHanaTopology \
    op start interval=0 timeout=600 \
    op stop interval=0 timeout=300 \
    op monitor interval=50 timeout=600 \
    params SID={sapsid} InstanceNumber={sapino}
clone cln_SAPHanaTop_{sapsid}_HDB{sapino} rsc_SAPHanaTop_{sapsid}_HDB{sapino} \
    meta clone-node-max=1 interleave=true
----

Additional information about all parameters can be found in manual page
ocf_suse_SAPHanaTopology(7).

Again, add the configuration to the cluster.

[subs="attributes,quotes"]
----
{sapnode1}:~ # crm configure load update crm-saphanatop.txt
----

The most important parameters here are SID and InstanceNumber, which are
quite self explaining in the SAP context. Beside these parameters, typical
tunables are the timeout values for the operations (start, monitor, stop).


==== SAPHanaFilesystem

This step is to define the resources to monitor the filesystem used by HANA, e.g.
/hana/shared/<SID>. The RA just monitors the filesystem, but neither does mount nor
umount it. Mounting and umounting is done by the OS thru /etc/fstab. 
Prepare the changes in a text file, for example _crm-saphanafil.txt_, and load it
with the command:

`crm configure load update crm-saphanafil.txt`

[subs="attributes,quotes"]
----
{sapnode1}:~ # vi crm-saphanafil.txt
# enter the following to crm-saphanafil.txt
primitive rsc_SAPHanaFil_{sapsid}_HDB{sapino} ocf:suse:SAPHanaFilesystem \
    op start interval=0 timeout=10 \
    op stop interval=0 timeout=20 \
    op monitor interval=120 timeout=120 \
    params SID={sapsid} InstanceNumber={sapino} ON_FAIL_ACTION=fence
clone cln_SAPHanaFil_{sapsid}_HDB{sapino} rsc_SAPHanaFil_{sapsid}_HDB{sapino} \
    meta clone-node-max=1 interleave=true
----

Additional information about all parameters can be found in manual page
ocf_suse_SAPHanaFilesystem(7).

Again, add the configuration to the cluster.

[subs="attributes,quotes"]
----
{sapnode1}:~ # crm configure load update crm-saphanafil.txt
----

The most important parameters here are SID and InstanceNumber, which are
quite self explaining in the SAP context. ON_FAIL_ACTION defines how the RA
should react on monitor failures. Beside these parameters, typical
tunables are the timeout values for the operations (start, monitor, stop).


==== SAPHanaController

This step is to define the resource needed, to control the replicated {HANA} pair.
Edit the changes in a text file, for example _crm-saphanacon.txt_, and load it
with the following command:

`crm configure load update crm-saphanacon.txt`

// DONE PRIO1: Check if this table makes sense in this setup guide

////
.Typical Resource Agent parameter settings for different scenarios
[width="99%",cols="52%,16%,16%,16%",options="header",]
|============================================================
|Parameter |Performance Optimized |Cost Optimized |Multi-Tier
|PREFER_SITE_TAKEOVER |true |false |false / true
|AUTOMATED_REGISTER |false / true |false / true |false
|DUPLICATE_PRIMARY_TIMEOUT |7200 |7200 |7200
|============================================================
////

// TODO PRIO1: Check if all parameters in special DUPLICATE_PRIMARY_TIMEOUT
// are explained well

.Description of important Resource Agent parameters
[width="100%",cols="42%,58%",options="header",]
|=======================================================================
|Parameter |Description

|PREFER_SITE_TAKEOVER|
Defines whether RA should prefer to take over to
the secondary instance instead of restarting the failed primary locally.

|AUTOMATED_REGISTER|
Defines whether a former primary should be automatically registered to
be secondary of the new primary. With this parameter you can adapt the
level of system replication automation.

If set to *false*, the former primary must be manually registered. The
cluster will not start this SAP HANA RDBMS until it is registered, to avoid
double primary up situations.

|DUPLICATE_PRIMARY_TIMEOUT|
Time difference needed between two primary
time stamps if a dual-primary situation occurs. If the time difference
is less than the time gap, the cluster holds one or both instances
in a "WAITING" status. This is to give an administrator the chance to react
on a failover. If the complete node of the former primary crashed, the former
primary will be registered after the time difference is passed. If
"only" the SAP HANA RDBMS has crashed, the former primary will be
registered immediately. After this registration to the new primary, all
data will be overwritten by the system replication.

|ON_FAIL_ACTION|
Defines how the RA escalates monitor failures on an HANA primary node.
If srHook=SOK, in case of monitor failure an node fencing could be triggered.
For srHook=SFAIL, the restart will be proceeded as usual. ON_FAIL_ACTION=*fence*
may speed up takeover, depending on how long HANA needs for stopping.
|=======================================================================

Additional information about all parameters of the SAPHanaController RA can be
found in manual page ocf_suse_SAPHanaController(7).

[subs="attributes,quotes"]
----
{sapnode1}:~ # vi crm-saphanacon.txt
# enter the following to crm-saphanacon.txt
primitive rsc_SAPHanaCon_{sapsid}_HDB{sapino} ocf:suse:SAPHanaController \
    op start interval=0 timeout=3600 \
    op stop interval=0 timeout=600 \
    op promote interval=0 timeout=900 \
    op demote interval=0 timeout=320 \
    op monitor interval=60 role=Promoted timeout=700 \
    op monitor interval=61 role=Unpromoted timeout=700 \
    params SID={sapsid} InstanceNumber={sapino} PREFER_SITE_TAKEOVER=true \
        DUPLICATE_PRIMARY_TIMEOUT=7200 AUTOMATED_REGISTER=false \
        ON_FAIL_ACTION=fence \
    meta priority=100
clone mst_SAPHanaCon_{sapsid}_HDB{sapino} rsc_SAPHanaCon_{sapsid}_HDB{sapino} \
    meta clone-node-max=1 promotable=true interleave=true maintenance=true
----

Now add the configuration to the cluster.

[subs="attributes,quotes"]
----
{sapnode1}:~ # crm configure load update crm-saphanacon.txt
----

The most important parameters here are again SID and InstanceNumber.
Beside these parameters the timeout values for the operations (start,
promote, monitors, stop) are typical tunables.

==== Adding a virtual IP address for the primary site

The last resource to be added is covering the virtual IP address.
For details, see manual page ocf_heartbeat_IPaddr2(7).

[subs="attributes,quotes"]
----
# vi crm-vip.txt
# enter the following to crm-vip.txt

primitive rsc_ip_{sapsid}_HDB{sapino} ocf:heartbeat:IPaddr2 \
    op monitor interval=10 timeout=20 \
    params ip={sapip1srv1}
----

Load the file to the cluster.

[subs="attributes,quotes"]
----
{sapnode1}:~ # crm configure load update crm-vip.txt
----

In most on-premise installations, only the parameter _ip_ needs to be set to the
virtual IP address to be presented to the client systems.
Public cloud environments often need specific settings.

==== Constraints for SAPHanaSR-angi

Two constraints are organizing the correct placement of the virtual IP
address for the client database access and the start order between the
resource agents SAPHanaController and SAPHanaTopology.

[subs="attributes,quotes"]
----
{sapnode1}:~ # vi crm-cs.txt
# enter the following to crm-cs.txt
colocation col_saphana_ip_{sapsid}_HDB{sapino} 2000: rsc_ip_{sapsid}_HDB{sapino}:Started \
    mst_SAPHanaCon_{sapsid}_HDB{sapino}:Promoted
order ord_saphana_{sapsid}_HDB{sapino} Optional: cln_SAPHanaTop_{sapsid}_HDB{sapino} \
    mst_SAPHanaCon_{sapsid}_HDB{sapino}
----

Load the file to the cluster.

[subs="attributes,quotes"]
----
{sapnode1}:~ # crm configure load update crm-cs.txt
----

==== Activating multi-state resource for cluster operation

The multi state resource was added to the cluster with in maintenance mode. To get
the resource operated by the cluster the maintenance must be ended by the command:

[subs="attributes,quotes"]
----
{sapnode1}:~ # crm resource refresh mst_SAPHanaCon_{sapsid}_HDB{sapino}
{sapnode1}:~ # cs_wait_for_idle -s 5
{sapnode1}:~ # crm resource maintenance mst_SAPHanaCon_{sapsid}_HDB{sapino} off
----

The command `cs_wait_for_idle` is part of the package `ClusterTools2`.
For more details, see manual pages cs_wait_for_idle(8), crm(8),
SAPHanaSR_maintenance_examples(7).

==== Active/active read-enabled scenario

This step is optional. If you have an active/active {HANA} system
replication with a read-enabled secondary, it is possible to integrate the
needed second virtual IP address into the cluster. This is done by adding a
second virtual IP address resource and a location constraint binding the
address to the secondary site.

[subs="attributes,quotes"]
----
{sapnode1}:~ # vi crm-re.txt
# enter the following to crm-re.txt
primitive rsc_ip_{sapsid}_HDB{sapino}_readenabled ocf:heartbeat:IPaddr2 \
    op monitor interval=10 timeout=20 \
    params ip={sapip1srv2}
colocation col_saphana_ip_{sapsid}_HDB{sapino}_readenabled 2000: \
    rsc_ip_{sapsid}_HDB{sapino}_readenabled:Started mst_SAPHanaCon_{sapsid}_HDB{sapino}:Unpromoted
----

Load the file to the cluster.

[subs="attributes,quotes"]
----
{sapnode1}:~ # crm configure load update crm-re.txt
----

