// PCM adoc file
// Please use the following line to implement each tagged content to the main document:
// include::SLES4SAP-sap-infra-monitoring-pcm.adoc[tag=pcm-XXXXX]

// PCM general
# tag::pcm-general[]

===== Processor Counter Monitor (PCM)

https://github.com/opcm/pcm[Processor Counter Monitor (PCM)] is an application programming interface (API) and a set of tools based on the API to monitor performance and energy metrics of Intel{reg} Core{tm}, Xeon{reg}, Atom{tm} and Xeon Phi{tm} processors.
PCM works on Linux, Windows, macOS X, FreeBSD and DragonFlyBSD operating systems.

# end::pcm-general[]


// PCM implementing
# tag::pcm-impl[]

=== Processor Counter Monitor (PCM)

Processor Counter Monitor (PCM) can be installed from its GitHub project pages.

Make sure the required tools are installed for building.

[subs="attributes,specialchars,verbatim,quotes"]
.Installing PCM from source
----
# zypper in -y git cmake gcc-c++
----

Clone the Git repository and build the tool using the following commands.

[subs="attributes,specialchars,verbatim,quotes"]
.Installing PCM from source
----
# git clone https://github.com/opcm/pcm.git
# cd pcm
# mkdir build
# cd build
# cmake ..
# cmake --build .
# cd bin
----

NOTE: Starting with SLES4SAP SP5 the PCM package is included.  


To start PCM on the observed host, first start a new `screen` session, and then start PCM.footnote:[Starting PCM should really be done by creating a systemd unit.]
// TODO: replace use of screen by a systemd unit for PCM
[subs="attributes,specialchars,verbatim,quotes"]
.Starting PCM
----
# screen -S pcm
# ./pcm-sensor-server -d
----

The PCM sensor server binary `pcm-sensor-server` has been started in a screen session which can be detached (type `Ctrl+a d`).
This lets the PCM sensor server continue running in the background.

==== PCM Systemd Service File

A more convenient and secure way to start pcm-sensor-server is using a systemd service.
To do so a service unit file has to be created under /etc/systemd/system/:

[subs="attributes,specialchars,verbatim,quotes"]
.Copy PCM binary
----
cp pcm-sensor-server /usr/local/bin/
----


[source]
----
# cat /etc/systemd/system/pcm.service
[Unit]
Description=
Documentation=/usr/share/doc/PCM
[Service]
Type=simple
Restart=no
ExecStart=/usr/local/bin/pcm-sensor-server 
[Install]
WantedBy=multi-user.target
----

The "systemd" needs to be informed about the new unit:

.reload the systemd daemon
[source]
----
# systemctl daemon-reload 
----

And finally enabled and started:

.Start pcm 
[source]
----
# systemctl enable --now pcm.service 
----

The PCM metrics can be queried from port 9738.

# end::pcm-impl[]