// Load document variables
:prodNr: 16
:pMinor16: 0
include::Var_SLES4SAP-{prodNr}.txt[]
include::Var_SLES4SAP-hana-angi-{prodNr}.txt[]
include::Var_SLES4SAP-hana-angi-param-{prodNr}.txt[]
// DO NOT CHANGE SECTION ID: refer to Trento check
[[cha.s4s.hana-sys-replication]]
== {stepHSR}

image::SAPHanaSR-ScaleOut-Plan-Phase4.svg[scaledwidth="100%"]

For more information read the section _Setting Up System Replication_ of the
{HANA} Administration Guide.

**Procedure**

. Back up the primary database.
. Enable the primary database.
. Register and start the secondary database.
. Verify the system replication.

=== Backing up the primary database

Back up the primary database as described in the {HANA} Administration Guide,
section _{HANA} Database Backup and Recovery_. We provide an example with SQL
commands. You need to adapt these backup commands to match your backup infrastructure.

.Simple backup for the system database and all tenants with one single backup call
=========================
As user _{refsidadm}_ enter the following command:

[subs="attributes,quotes"]
----
~> hdbsql -i {sapino} -u SYSTEM -d SYSTEMDB \
   "BACKUP DATA FOR FULL SYSTEM USING FILE ('backup')"
----

You will get a command output similar to the following:

----
0 rows affected (overall time 15.352069 sec; server time 15.347745 sec)
----
=========================

.Simple backup for a single container (non MDC) database
=========================
Enter the following command as user _{refsidadm}_:

[subs="specialchars,attributes"]
----
~> hdbsql -i {refInst} -u <dbuser> \
   "BACKUP DATA USING FILE ('backup')"
----
=========================

IMPORTANT: Without a valid backup, you cannot bring {HANA} into a system
replication configuration.

=== Enabling the primary node

As Linux user _{refsidadm}_, enable the system replication at the primary node. You
need to define a site name (like {sapsite1}). This site name must be unique for
all {HANA} databases which are connected via system replication. This means the
secondary must have a different site name. The site names must not be changed
later when the cluster has been activated.

NOTE: Do not use strings like "primary" and "secondary" as site names.

==== Enable primary node

Enable the primary using the `-sr_enable` option.

[subs="attributes,quotes"]
----
{sapnode1}:~> hdbnsutil -sr_enable --name={sapsite1}
checking local nameserver:
checking for active nameserver ...
nameserver is running, proceeding ...
configuring ini files ...
successfully enabled system as primary site ...
done.
----

==== Check system replication configuration on primary node

// the command output is still valid as of HANA 2.0 SPS5
Check the primary using the command `hdbnsutil -sr_stateConfiguration`.

[subs="specialchars,attributes,quotes"]
----
{sapnode1}:~> hdbnsutil -sr_stateConfiguration --sapcontrol=1
SAPCONTROL-OK: <begin>
mode=primary
site id=1
site name={sapsite1}
SAPCONTROL-OK: <end>
done.
----

The mode has changed from “none” to “primary”. The site now has a site name and a site ID.

=== Registering the secondary site

The {HANA} database instance on the secondary side must be stopped
before the instance can be registered for the system replication. You
can use your preferred method to stop the instance (like `HDB` or
`sapcontrol`). After the database instance has been stopped
successfully, you can register the instance using `hdbnsutil`. Again,
use the Linux user _{refsidadm}_:

==== Stop the secondary database

To stop the secondary, you can use the command line tool _HDB_.

[subs="attributes,quotes"]
----
{sapnode2}:~> HDB stop
----

==== Copy KEY and KEY-DATA file from the primary to the secondary site

Beginning with {HANA} 2.0, the system replication is running encrypted.
The key files need to be copied-over from the primary to the secondary site.

[subs="specialchars,attributes,quotes"]
----
~> cd /usr/sap/{refSID}/SYS/global/security/rsecssfs
~> rsync -va {,<node1-siteB>:}$PWD/data/SSFS_{refSID}.DAT
~> rsync -va {,<node1-siteB>:}$PWD/key/SSFS_{refSID}.KEY
----

==== Register secondary site

The registration of the secondary is triggered by calling _hdbnsutil -sr_register ..._.

[subs="attributes,quotes"]
----
...
{sapnode2}:~> hdbnsutil -sr_register --name={sapsite2} \
     --remoteHost={sapnode1} --remoteInstance={sapino} \
     --replicationMode=sync --operationMode=logreplay
adding site ...
checking for inactive nameserver ...
nameserver {sapnode2}:30001 not responding.
collecting information ...
updating local ini files ...
done.
----

The _remoteHost_ is the primary node in our case, the _remoteInstance_ is the
database instance number (here {sapino}).

Now start the database instance again and verify the system replication status.
On the secondary node, the mode should be one of "SYNC" or "SYNCMEM". "ASYNC" is
*not supported with automated cluster takeover*. The mode depends on the
*replicationMode* option defined during the registration of the secondary.

==== Start secondary and check system replication configuration

To start the new secondary, use the command line tool _HDB_. Then check the
SR configuration using `hdbnsutil -sr_stateConfiguration`.

[subs="specialchars,attributes,quotes"]
----
{sapnode2}:~> HDB start
...
{sapnode2}:~> hdbnsutil -sr_stateConfiguration --sapcontrol=1
SAPCONTROL-OK: <begin>
mode=sync
site id=2
site name={sapsite2}
active primary site=1
primary masters={sapnode1}
SAPCONTROL-OK: <end>
done.
----

To view the replication state of the whole {HANA} cluster, use the
following command as _{refsidadm}_ user on the primary node:

==== Check system replication status details

The python script _systemReplicationStatus.py_ provides details about the current
system replication.

[subs="attributes,quotes"]
----
{sapnode1}:~> cdpy; python3 systemReplicationStatus.py --sapcontrol=1
...
site/2/SITE_NAME={sapsite2}
site/2/SOURCE_SITE_ID=1
site/2/REPLICATION_MODE=SYNC
site/2/REPLICATION_STATUS=ACTIVE
overall_replication_status=ACTIVE
site/1/REPLICATION_MODE=PRIMARY
site/1/SITE_NAME={sapsite1}
local_site_id=1
...
----


=== Manually testing the {HANA} SR takeover
[[cha.s4s.testtakeover]]

Before you integrate your {HANA} system replication into the HA cluster, it is
mandatory to do a manual takeover. Testing without the cluster helps to make
sure that basic operation (takeover and registration) is working as expected.

* Stop {HANA} on node 1.

* Takeover {HANA} to node 2.

* Register node 1 as secondary.

* Start {HANA} on node 1.

* Wait until sync state is active.

=== Optional: Manually re-establishing {HANA} SR to original state

Bring the systems back to the original state:

* Stop {HANA} on node 2.

* Take over {HANA} to node 1.

* Register node 2 as secondary.

* Start {HANA} on node2.

* Wait until sync state is active.
