// Load document variables
:prodNr: 16
:pMinor16: 0
include::Var_SLES4SAP-{prodNr}.txt[]
include::Var_SLES4SAP-hana-angi-{prodNr}.txt[]
include::Var_SLES4SAP-hana-angi-param-{prodNr}.txt[]
[[app.hana-sr.example]]
:sapnode1: besler3
:sapnode2: besler4
:sapsid: HA1
:sapssid: ha1
:sapino: 00
:sapip1srv1: 192.168.2.66
:clustername: besler34
== Examples
The chapter "Examples" refers to our two-node lab cluster _{clustername}_. 
The two nodes are named _{sapnode1}_ and _{sapnode2}_.
{HANA} has the SID _{sapsid}_ and instance number _{sapino}_.

=== Example `{slehainit}` and join
. Example for `{slehainit}` dialog
----
include::SLES4SAP-hana-angi-scaleup-perfopt-16-example-crminit.txt[]
----

. Example for `{slehajoin}` dialog
----
include::SLES4SAP-hana-angi-scaleup-perfopt-16-example-crmjoin.txt[]
----

=== Example for corosync configuration
. Example _/etc/corosync/corosync.conf_ from lab cluster _{clustername}_
----
include::SLES4SAP-hana-angi-scaleup-perfopt-16-example-corosync.txt[]
----

=== Example cluster configuration
The following complete progressive crm configuration is for a two-node cluster
({sapnode1}, {sapnode2}) and an {HANA} database with SID {sapsid}
and instance number {sapino}. A failed primary will be automatically registered
as secondary after reboot.
Priority fencing prefers the {HANA} primary in case of split-brain.
The virtual IP address in the example is {sapip1srv1}.

. Example crm configuration from lab cluster _besler34_
----
include::SLES4SAP-hana-angi-scaleup-perfopt-16-example-cib.txt[]
----

++++
<?pdfpagebreak?>
++++
