:docinfo:

// = {title}
= Wordpress on LAMP on SUSE Linux Enterprise Server
// SUSE Linux Enterprise Server 15
// :author: James Yang
:revnumber: 0.0.1
:toc2:
:toc-title: Wordpress on LAMP on SLES
:toclevels: 4

:sles: SUSE Linux Enterprise Server

== Scope
This document details how to install and configure https://mariadb.org/[MariabDB], https://httpd.apache.org/[Apache], https://www.php.net/[PHP] to setup the https://en.wikipedia.org/wiki/LAMP_(software_bundle)[LAMP] stack on {sles}. To verify our LAMP stack is functional we'll install https://wordpress.com[Wordpress].

// TODO

=== Background

// TODO
Starting with {sles} 12, MySQL has been https://www.suse.com/releasenotes/x86_64/SUSE-SLES/12/#fate-316482[replaced] with MariaDB. MariaDB's client protocol is "wire" compatible with MySQL's protocol and in most scenarios even the data files are binary compatible. For our purposes MariaDB will work just fine. If you'd like more information visit https://mariadb.com/kb/en/mariadb-vs-mysql-compatibility/[MariaDB versus MySQL: Compatibility].

== Preinstallation

=== System requirements

* CPU with 1 core
* AMD64/Intel 64 architecture
* 2 GB disk space
* 2 GB RAM

NOTE: These requirements cover a minimal installation, adapt as needed to cover your use case.

[id="server_registration"]
=== Server registration

Before starting, ensure your {sles} instance is registered by following this knowledge base https://www.suse.com/support/kb/doc/?id=000018564[article] to enable access to repositories.


=== Refresh repositories
. Prior to starting the installation, let's refresh our repositories and ensure we have the latest packages

+
[source,bash]
----
> sudo zypper update --no-confirm

Refreshing service 'Basesystem_Module_15_SP3_x86_64'.
Refreshing service 'SUSE_Linux_Enterprise_Server_15_SP3_x86_64'.
Refreshing service 'Server_Applications_Module_15_SP3_x86_64'.
Loading repository data...
Reading installed packages...
Resolving package dependencies...
...
----

== Installation

We'll first start with MariaDB

=== MariaDB Setup
. Install the MariaDB package

+
[source,bash]
----
> sudo zypper in --no-confirm mariadb

Refreshing service 'Basesystem_Module_15_SP3_x86_64'.
Refreshing service 'SUSE_Linux_Enterprise_Server_15_SP3_x86_64'.
Refreshing service 'Server_Applications_Module_15_SP3_x86_64'.
Loading repository data...
Reading installed packages...
Resolving package dependencies...

The following 9 NEW packages are going to be installed:
  libJudy1 libmariadb3 libpq5 mariadb mariadb-client mariadb-errormessages psqlODBC python3-mysqlclient unixODBC

The following 2 recommended packages were automatically selected:
  mariadb psqlODBC

9 new packages to install.
Overall download size: 23.7 MiB. Already cached: 0 B. After the operation, additional 171.2 MiB will be used.
Continue? [y/n/v/...? shows all options] (y): y
Retrieving package libmariadb3-3.1.13-3.30.1.x86_64                                                                                             (1/9), 132.3 KiB (354.9 KiB unpacked)
...
----

. Enable MariaDB to start on boot (optional)
+
[source,bash]
----
> sudo systemctl enable mariadb

Created symlink /etc/systemd/system/mysql.service → /usr/lib/systemd/system/mariadb.service.
Created symlink /etc/systemd/system/multi-user.target.wants/mariadb.service → /usr/lib/systemd/system/mariadb.service.
----

. Start MariaDB
+
[source,bash]
----
> sudo systemctl start mariadb
----

. Ensure MariaDB is started -> active(running)
+
[source,bash]
----
> sudo systemctl status mariadb

● mariadb.service - MariaDB database server
   Loaded: loaded (/usr/lib/systemd/system/mariadb.service; disabled; vendor preset: disabled)
   Active: active (running) since Fri 2021-07-02 01:55:22 UTC; 7s ago
     Docs: man:mysqld(8)
           https://mariadb.com/kb/en/library/systemd/
  Process: 26513 ExecStartPre=/usr/lib/mysql/mysql-systemd-helper upgrade (code=exited, status=0/SUCCESS)
  Process: 26447 ExecStartPre=/usr/lib/mysql/mysql-systemd-helper install (code=exited, status=0/SUCCESS)
 Main PID: 26519 (mysqld)
   Status: "Taking your SQL requests now..."
    Tasks: 30
   CGroup: /system.slice/mariadb.service
           └─26519 /usr/sbin/mysqld --defaults-file=/etc/my.cnf --user=mysql
----

. Verify we can connect to MariaDB with the client
+
[source,bash]
----
> mariadb -u root

Welcome to the MariaDB monitor.  Commands end with ; or \g.
Your MariaDB connection id is 3
Server version: 10.5.11-MariaDB MariaDB package

Copyright (c) 2000, 2018, Oracle, MariaDB Corporation Ab and others.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

MariaDB [(none)]> 

----

. The MariaDB installation comes with a peskey default user that can mask login attempts from localhost. So let's first remove this user.
+
[source,sql]
----
MariaDB [(none)]> DROP USER ''@localhost;
Query OK, 0 rows affected (0.003 sec)
----

. Now let's create a database for wordpress and a corresponding user. Replace `password` with your own password.
+
[source,sql]
----
MariaDB [(none)]> CREATE DATABASE IF NOT EXISTS wordpress;
Query OK, 1 row affected (0.000 sec)

MariaDB [(none)]> GRANT ALL PRIVILEGES ON wordpress.* TO 'wordpress' IDENTIFIED BY 'password';
Query OK, 0 rows affected (0.003 sec)

MariaDB [(none)]> exit
Bye
----

. And verify we can connect as the wordpress user
 Now let's create a database for wordpress and a corresponding user. Replace `password` with your own password.
+
[source,sql]
----
mariadb -u wordpress -p wordpress
Enter password: 
Welcome to the MariaDB monitor.  Commands end with ; or \g.
Your MariaDB connection id is 4
Server version: 10.5.11-MariaDB MariaDB package

Copyright (c) 2000, 2018, Oracle, MariaDB Corporation Ab and others.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

MariaDB [wordpress]> exit
Bye

----


=== Apache Http Server Setup

Next up is Apache server.

. Install the apache2 package
+
[source,bash]
----
> zypper install --no-confirm apache2

zypper install --no-confirm apache2
Refreshing service 'Basesystem_Module_15_SP3_x86_64'.
Refreshing service 'SUSE_Linux_Enterprise_Server_15_SP3_x86_64'.
Refreshing service 'Server_Applications_Module_15_SP3_x86_64'.
Refreshing service 'Web_and_Scripting_Module_15_SP3_x86_64'.
Loading repository data...
Reading installed packages...
Resolving package dependencies...

The following 2 NEW packages are going to be installed:
  apache2 apache2-prefork

2 new packages to install.
Overall download size: 1.6 MiB. Already cached: 0 B. After the operation, additional 4.9 MiB will be used.
Continue? [y/n/v/...? shows all options] (y): y
Retrieving package apache2-2.4.43-3.22.1.
...

----


=== PHP Setup

Next let's install php.

. We'll need the Web and Scripting Module which is included with your {sles} subscription. Substitute with your specific version and architecture

+
[source,bash]
----
> sudo SUSEConnect --product sle-module-web-scripting/{sles_version}/{architecture}

Registering system to SUSE Customer Center

Updating system details on https://scc.suse.com ...

Activating sle-module-web-scripting 15.3 x86_64 ...
-> Adding service to system ...
-> Installing release package ...

Successfully registered system
----

. Now we can install php and the apache php module we'll need later on.

+
[source,bash]
----
> sudo zypper in -y php7 php7-mysql apache2-mod_php7 php7-zlib

Refreshing service 'Basesystem_Module_15_SP3_x86_64'.
Refreshing service 'SUSE_Linux_Enterprise_Server_15_SP3_x86_64'.
Refreshing service 'Server_Applications_Module_15_SP3_x86_64'.
Refreshing service 'Web_and_Scripting_Module_15_SP3_x86_64'.
Loading repository data...
Reading installed packages...
Resolving package dependencies...

The following 13 NEW packages are going to be installed:
  apache2-mod_php7 php7 php7-ctype php7-dom php7-iconv php7-json php7-mysql php7-pdo php7-sqlite php7-tokenizer php7-xmlreader php7-xmlwriter php7-zlib

The following 8 recommended packages were automatically selected:
  php7-ctype php7-dom php7-iconv php7-json php7-sqlite php7-tokenizer php7-xmlreader php7-xmlwriter

The following 3 packages are suggested, but will not be installed:
  php7-gd php7-gettext php7-mbstring

13 new packages to install.
Overall download size: 3.7 MiB. Already cached: 0 B. After the operation, additional 20.5 MiB will be used.
Continue? [y/n/v/...? shows all options] (y): y
...

----

. Check our php install

+
[source,bash]
----
> php --version

PHP 7.4.6 (cli) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
----

=== Wordpress Setup

Finally we can install wordpress

. First download wordpress 

+
[source,bash]
----
> curl -L https://wordpress.org/latest.zip -o /opt/wordpress_latest.zip

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 15.7M  100 15.7M    0     0  3209k      0  0:00:05  0:00:05 --:--:-- 3510k

> unzip /opt/wordpress_latest.zip -d /opt

 unzip /opt/wordpress_latest.zip -d /opt/wordpress
Archive:  /opt/wordpress_latest.zip
   creating: /opt/wordpress/wordpress/
  inflating: /opt/wordpress/wordpress/xmlrpc.php  
  inflating: /opt/wordpress/wordpress/wp-blog-header.php  
  inflating: /opt/wordpress/wordpress/readme.html  

...


----


== Configuration

=== Initial configuration

To configure and start SQL Server, `mssql-conf` can be used to accept the EULA, set the SQL Server Edition, and the SA password.

[TIP]
--
For convenience, you can add the configuration to your `PATH` to avoid typing the full path each time:

[source,bash]
----
echo 'export PATH="$PATH:/opt/mssql/bin"' >> ~/.bashrc
source ~/.bashrc
----

--

Then, to configure and start `msql-server` (`mssql-conf` starts the `msql-server` immediately after configuring),
run the following command:

[source,bash]
----
> sudo ACCEPT_EULA='Y' MSSQL_SA_PASSWORD=Suselove12 MSSQL_PID='Developer' mssql-conf --noprompt setup
----

* `ACCEPT_EULA` accepts the SQL Server EULA
* `MSQL_SA_PASSWORD` sets the SA user password. Ensure password requirements as outlined in <<password_requirements>> are followed.
* `MSQL_PID` sets the SQL Server edition, acceptable values are:
** Evaluation
** Developer
** Express
** Web
** Standard
** Enterprise
** Product key formatted as +#####-#####-#####-#####-#####+
* The `noprompt` option configures SQL Server non-interactively

WARNING: It is recommended to change the SA password later with `mssql-conf set-sa-password` 
or disable the history prior to configuring SQL Server with `set +o history`, and re-enabling it afterward with `set -o history` (Bash).

SQL Server should be started at this point. You can verify this with `netcat`. 
SQL Server listens for connections on port `1433` by default:

[source,bash]
----
> sudo zypper install --no-confirm netcat
nc -vz localhost 1433
----

For further configuration, use `mssql-conf` to set additional parameters. Changes will take effect after a restart:

[source,bash]
----
> sudo mssql-conf set ${parameter}
> sudo systemctl restart mssql-server
----

Available `mssql-conf` options are described in https://docs.microsoft.com/en-us/sql/linux/sql-server-linux-configure-mssql-conf[Configure SQL Server on Linux with the mssql-conf tool].

An alternative way to configure SQL Server is using the `/var/opt/mssql/mssql.conf` file. 
Settings are stored in the https://en.wikipedia.org/wiki/INI_file[INI] format.

A sample `mssql.conf` file is shown below. Edit the `mssql.conf` file and restart `mssql-server` to apply changes.

[source,ini]
----
[EULA]
accepteula = Y

[filelocation]
defaultdatadir = /var/opt/mssql/data/
defaultdumpdir = /var/opt/mssql/data/
defaultlogdir = /var/opt/mssql/data/

[network]
tcpport = 1433

[sqlagent]
enabled = true
----

== Tools

Now that SQL Server is running, you can query it. The `mssql-tools` package includes `sqlcmd`, which is a shell to query SQL Server. 
Install it similarly to the `mssql-server` package.

Add the repository:

[source,bash]
----
> sudo zypper addrepo --refresh --check https://packages.microsoft.com/config/sles/12/prod.repo
----

Install the `mssql-tools` package:

[source,bash]
----
> sudo ACCEPT_EULA=Y zypper install --no-confirm mssql-tools
----

[TIP]
--
You can add the tools to your `PATH` like you did for `mssql-conf`:

[source,bash]
----
echo 'export PATH="$PATH:/opt/mssql-tools/bin"' >> ~/.bashrc
source ~/.bashrc
----

Alternatively, you can symlink `sqlcmd` to `/usr/local/bin/` since it is a binary:

[source,bash]
----
> sudo ln --symbolic /opt/mssql-tools/bin/sqlcmd /usr/local/bin/sqlcmd
----

--

Then start `sqlcmd` and input a query. The `-S` option designates the server. The `-U` option specifies the user. 
Available options can be found at https://docs.microsoft.com/en-us/sql/tools/sqlcmd-utility?view=sql-server-ver15#syntax[sqlcmd Utility Syntax]. 


[source,bash]
----
> sudo sqlcmd -S localhost -U SA
----

[source,sql]
----
SELECT name from sys.databases
GO

name
master
tempdb
model
msdb
TestDB
----


`GO` is required here to execute the previous statements.

To exit `sqlcmd`, input `quit`:


[source,sql]
----
quit
----


The full `sqlcmd` documentation can be found at https://docs.microsoft.com/en-us/sql/tools/sqlcmd-utility?view=sql-server-ver15[sqlcmd Utility].


== Administration

=== `systemd`

The `mssql-server` package installs and configures SQL Server as a https://systemd.io/[`systemd`] service. 
`systemd` provides a framework for managing services, mounts, and system states. 
You can find more details about `systemd` unit files at https://www.freedesktop.org/software/systemd/man/systemd.unit.html[systemd.unit — Unit configuration]. 
To control the `mssql-server` service, use `systemctl` to retrieve the `status`, `start`, `stop`, `restart`, `enable`, and `disable` the service.

* Display `mssql-server` status:
+
[source,bash]
----
> sudo systemctl status mssql-server

● mssql-server.service - Microsoft SQL Server Database Engine
   Loaded: loaded (/usr/lib/systemd/system/mssql-server.service; enabled; vendor preset: disabled)
   Active: active (running) since Thu 2021-02-25 01:54:18 UTC; 16h ago
     Docs: https://docs.microsoft.com/en-us/sql/linux
 Main PID: 1341 (sqlservr)
    Tasks: 166
   CGroup: /system.slice/mssql-server.service
           ├─1341 /opt/mssql/bin/sqlservr
           └─1596 /opt/mssql/bin/sqlservr
----

* Start `mssql-server`:
+
[source,bash]
----
> sudo systemctl start mssql-server
----

* Stop `mssql-server`:
+
[source,bash]
----
> sudo systemctl stop mssql-server
----

* Restart `mssql-server`:
+
[source,bash]
----
> sudo systemctl restart mssql-server
----

* Enable `mssql-server` to start on boot (`mssql-server` is enabled by default on installation):
+
[source,bash]
----
> sudo systemctl enable mssql-server

Created symlink from /etc/systemd/system/multi-user.target.wants/mssql-server.service to /usr/lib/systemd/system/mssql-server.service.
----

* Disable `mssql-server` to present starting on boot:
+
[source,bash]
----
> sudo systemctl disable mssql-server

Removed symlink /etc/systemd/system/multi-user.target.wants/mssql-server.service.
----

=== Logs

For troubleshooting, the logs and crash dumps are written to `/var/opt/mssql/log` by default. 
Notable logs are the *errorlogs* (+errorlog*+), *trace logs* (+*.trc+), *sqlagent logs* (+sqlagent*+), 
and the *extended events logs* (*.xel). Core dumps are written with the `.tar.gz2` extension and SQL dumps with the `.mdmp` extension. 
To view these resources, you need `root` or the `mssql` user access.

[source,bash]
----
ls /var/opt/mssql/log
HkEngineEventFile_0_132574672188100000.xel	errorlog	errorlog.4	log_20.trc	sqlagent.2  		system_health_0_132574672201000000.xel
HkEngineEventFile_0_132574672310500000.xel	errorlog.1	health.log	log_21.trc	sqlagent.3		system_health_0_132574672319150000.xel
HkEngineEventFile_0_132575629019340000.xel	errorlog.2	log_18.trc	log_22.trc	sqlagent.out		system_health_0_132575629028000000.xel
HkEngineEventFile_0_132575645400520000.xel	errorlog.3	log_19.trc	sqlagent.1	sqlagentstartup.log	system_health_0_132575645408320000.xel
----

=== Loading sample data

Microsoft has provided some https://github.com/microsoft/sql-server-samples[sample databases] 
you can use to seed your `mssql-server` instance with some data. 

Here is an example of loading our SQL server instance with the sample database `WideWorldImporters`.

Download the `WideWorldImporters` database:

[source,bash]
----
curl --location https://github.com/Microsoft/sql-server-samples/releases/download/wide-world-importers-v1.0/WideWorldImporters-Full.bak \
    --output /tmp/WideWorldImporters-Full.bak
----

Restore full backup into `mssql-server` with `sqlcmd` while updating paths for the data, userdata, transaction log, and in-memory data:

[source,sql]
----
sqlcmd -S localhost \
    -U sa \
    -P Suselove12 \
    -Q "RESTORE DATABASE WideWorldImporters \
        FROM DISK ='/tmp/WideWorldImporters-Full.bak' WITH \
        MOVE 'WWI_Primary' TO '/var/opt/mssql/data/WideWorldImporters.mdf', \
        MOVE 'WWI_UserData' TO '/var/opt/mssql/data/WideWorldImporters_UserData.ndf', \
        MOVE 'WWI_Log' TO '/var/opt/mssql/data/WideWorldImporters.ldf', \
        MOVE 'WWI_InMemory_Data_1' TO '/var/opt/mssql/data/WideWorldImporters_InMemory_Data_1'"

Processed 1464 pages for database 'WideWorldImporters', file 'WWI_Primary' on file 1.
Processed 53096 pages for database 'WideWorldImporters', file 'WWI_UserData' on file 1.
Processed 33 pages for database 'WideWorldImporters', file 'WWI_Log' on file 1.
Processed 3862 pages for database 'WideWorldImporters', file 'WWI_InMemory_Data_1' on file 1.
Converting database 'WideWorldImporters' from version 852 to the current version 904.
Database 'WideWorldImporters' running the upgrade step from version 852 to version 853.
Database 'WideWorldImporters' running the upgrade step from version 853 to version 854.
...
Database 'WideWorldImporters' running the upgrade step from version 902 to version 903.
Database 'WideWorldImporters' running the upgrade step from version 903 to version 904.
RESTORE DATABASE successfully processed 58455 pages in 37.388 seconds (12.214 MB/sec).
----

When loaded, project ten table names from the `WideWorldImporters` database to test it out:

[source,sql]
----
sqlcmd -S localhost \
    -U sa \
    -P Suselove12 \
    -Q "SELECT TOP(10) table_name FROM \
        WideWorldImporters.information_schema.tables \
        WHERE table_type = 'BASE TABLE'"

table_name
--------------------------------------------------------------------------------------------------------------------------------

Colors
Colors_Archive
OrderLines
PackageTypes
PackageTypes_Archive
StockGroups
StockItemStockGroups
StockGroups_Archive
StateProvinces
CustomerTransactions

(10 rows affected)
----

== Summary

Businesses around the world look to SUSE to help them simplify and optimize their IT environments, 
modernize their applications and infrastructure, and accelerate innovation on-premises, in the cloud, and at the edge. 
With {sles} support for Microsoft SQL Server, businesses can streamline their IT landscape and operations 
without changing their preferred enterprise database management system.

At this point, you should have a rudimentary understanding of how to install SQL Server on {sles}, 
install SQL Server tools, query SQL Server and perform basic administration. 
To stay up to date on the latest SQL Server on Linux features bookmark https://docs.microsoft.com/en-us/sql/linux/sql-server-linux-release-notes-2019?view=sql-server-ver15[Release notes for SQL Server 2019 on Linux].


== Appendix

[id="password_requirements"]
=== SQL Server password requirements

SQL Server passwords must be between 8 and 128 (inclusive), cannot contain Unicode control characters `[Ll, Lu, Nd, Cc]` 
and must contain at least three of the following:

* Uppercase letters
* Lowercase letters
* Numbers
* Symbols from the set ``(`~!@#$%^&*_-+=|\\{}[]:;\"'<>,.?)/``

=== References

* https://en.wikipedia.org/wiki/LAMP_%28software_bundle%29[LAMP (software bundle)]
* https://www.ibm.com/cloud/learn/lamp-stack-explained[LAMP Stack explained]
* https://www.webopedia.com/definitions/lamp/[webopedia LAMP]
* https://wordpress.org/support/article/how-to-install-wordpress[How to install wordpress]
* http://httpd.apache.org/docs/current/install.html[Compiling and Installing Apache]
* https://mariadb.com/kb/en/installing-mariadb-with-zypper/[Installing MariaDB with zypper]
* https://www.suse.com/releasenotes/x86_64/SUSE-SLES/12/#fate-316482[SLES 12 Release Notes]
* https://mariadb.com/kb/en/mariadb-vs-mysql-compatibility/[MariaDB vs MySQL Compatibility]

:leveloffset: 0
// Standard SUSE Best Practices includes
== Legal notice
include::common_sbp_legal_notice.adoc[]

++++
<?pdfpagebreak?>
++++

// Standard SUSE Best Practices includes
// include::common_gfdl1.2_i.adoc[]

:leveloffset: 0
include::common_gfdl1.2_i.adoc[]
