:docinfo:

// = {title}
= Microsoft SQL Server on SUSE Linux Enterprise Server: Getting Started
// SUSE Linux Enterprise Server 12 SP3 - SP5, SQL Server 2019
// :author: James Yang
:revnumber: 0.0.1
:toc2:
:toc-title: Microsoft SQL Server on SUSE Linux Enterprise Server
:toclevels: 4

:sles: SUSE Linux Enterprise Server

== Motivation

=== Background

Since Microsoft released SQL Server for Linux in 2017 footnote:[https://cloudblogs.microsoft.com/sqlserver/2017/10/02/sql-server-2017-on-windows-linux-and-docker-is-now-generally-available], 
the feature gap footnote:[https://docs.microsoft.com/en-us/sql/linux/sql-server-linux-editions-and-components-2019?view=sql-server-ver15#Unsupported] for SQL Server between Windows and Linux has been closing quickly with each update. Aside from some niche features footnote:[https://docs.microsoft.com/en-us/sql/linux/sql-server-linux-editions-and-components-2019?view=sql-server-ver15#Unsupported], it's now extremely viable to consider running SQL Server workloads on Linux, with the 2019 release footnote:[https://docs.microsoft.com/en-us/sql/linux/sql-server-linux-release-notes-2019?view=sql-server-ver15#release-history].

=== Audience

This guide is intended for SQL Server DBAs, Developers, and DevOps/SRE engineers who are familiar with SQL Server on Windows and are looking 
to migrate to Linux. Operators who are adding a SQL Server requirement into a primarily Linux environment may prefer tools that run only on Linux servers for consistency and simplicity. Another reason may be lower negotiated pricing for Linux subscriptions to replace existing SQL Servers on Windows machines.

=== Scope

The guide covers a basic installation of SQL Server on {sles}. 
It is meant to be agnostic of underlying infrastructure excepting the nuance of registering your server discussed in <<server_registration>>.


== Installation

=== System requirements

* 2 GHz CPU with 2 cores
* AMD64/Intel 64 architecture
* XFS or Ext4 file system
* 6 GB disk space (not including data)

[id="server_registration"]
=== Server registration

To gain access to SUSE repositories, you first need to register your server with `SUSEConnect`. If you are launching an On-Demand (or Pay-As-You-Go) 
instance and not a BYOS (Bring Your Own Subscription) instance at a public cloud provider, skip this step.

[source,bash]
----
sudo SUSEConnect --regcode ${REGISTRATION_CODE} --email ${EMAIL_ADDRESS}
----


Alternatively, if you have a

* SUSE https://documentation.suse.com/sles/12-SP5/single-html/SLES-smt/#book-smt[SMT] (Subscription Management Tool)
* or SUSE https://documentation.suse.com/sles/15-SP2/single-html/SLES-rmt/#book-rmt[RMT] (Repository Mirroring Tool) 
* or https://documentation.suse.com/external-tree/en-us/suma/4.1/suse-manager/index.html[SUSE Manager] 

server you want to use, use the `--url` option instead.

[source,bash]
----
sudo SUSEConnect --url ${REGISTRATION_SERVER_URL}
----

More information about registering can be found in the https://documentation.suse.com/sles/12-SP5/html/SLES-all/cha-y2-sw.html#sec-y2-sw-register-suseconnect[{sles} 12 SP5 Deployment Guide].


=== Repositories

To verify packages from Microsoft’s SQL Server repositories, first add their package signing key:

[source,bash]
----
sudo rpm --import https://packages.microsoft.com/keys/microsoft.asc
----


Then add the repository. The `refresh` option enables auto refresh of the repository and the `check` option validates the URL:

[source,bash]
----
sudo zypper addrepo --refresh --check https://packages.microsoft.com/config/sles/12/mssql-server-2019.repo
----


=== Package

To install the SQL Server package non-interactively, run the following command:

[source,bash]
----
sudo zypper install --no-confirm mssql-server
----

== Configuration

=== Initial configuration

To configure and start SQL Server, `mssql-conf` can be used to accept the EULA, set the SQL Server Edition, and the SA password.

[TIP]
--
For convenience, you can add the configuration to your `PATH` to avoid typing the full path each time:

[source,bash]
----
echo 'export PATH="$PATH:/opt/mssql/bin"' >> ~/.bashrc
source ~/.bashrc
----

--

Then, to configure and start `msql-server` (`mssql-conf` starts the `msql-server` immediately after configuring),
run the following command:

[source,bash]
----
sudo ACCEPT_EULA='Y' MSSQL_SA_PASSWORD=Suselove12 MSSQL_PID='Developer' mssql-conf --noprompt setup
----

* `ACCEPT_EULA` accepts the SQL Server EULA
* `MSQL_SA_PASSWORD` sets the SA user password. Ensure password requirements as outlined in <<password_requirements>> are followed.
* `MSQL_PID` sets the SQL Server edition, acceptable values are:
** Evaluation
** Developer
** Express
** Web
** Standard
** Enterprise
** Product key formatted as +#####-#####-#####-#####-#####+
* The `noprompt` option configures SQL Server non-interactively

WARNING: It is recommended to change the SA password later with `mssql-conf set-sa-password` 
or disable the history prior to configuring SQL Server with `set +o history`, and re-enabling it afterward with `set -o history` (Bash).

SQL Server should be started at this point. You can verify this with `netcat`. 
SQL Server listens for connections on port `1433` by default:

[source,bash]
----
sudo zypper install --no-confirm netcat
nc -vz localhost 1433
----

For further configuration, use `mssql-conf` to set additional parameters. Changes will take effect after a restart:

[source,bash]
----
sudo mssql-conf set ${parameter}
sudo systemctl restart mssql-server
----

Available `mssql-conf` options are described in https://docs.microsoft.com/en-us/sql/linux/sql-server-linux-configure-mssql-conf[Configure SQL Server on Linux with the mssql-conf tool].

An alternative way to configure SQL Server is using the `/var/opt/mssql/mssql.conf` file. 
Settings are stored in the https://en.wikipedia.org/wiki/INI_file[INI] format.

A sample `mssql.conf` file is shown below. Edit the `mssql.conf` file and restart `mssql-server` to apply changes.

[source,ini]
----
[EULA]
accepteula = Y

[filelocation]
defaultdatadir = /var/opt/mssql/data/
defaultdumpdir = /var/opt/mssql/data/
defaultlogdir = /var/opt/mssql/data/

[network]
tcpport = 1433

[sqlagent]
enabled = true
----

== Tools

Now that SQL Server is running, you can query it. The `mssql-tools` package includes `sqlcmd`, which is a shell to query SQL Server. 
Install it similarly to the `mssql-server` package.

Add the repository:

[source,bash]
----
sudo zypper addrepo --refresh --check https://packages.microsoft.com/config/sles/12/prod.repo
----

Install the `mssql-tools` package:

[source,bash]
----
sudo ACCEPT_EULA=Y zypper install --no-confirm mssql-tools
----

[TIP]
--
You can add the tools to your `PATH` like you did for `mssql-conf`:

[source,bash]
----
echo 'export PATH="$PATH:/opt/mssql-tools/bin"' >> ~/.bashrc
source ~/.bashrc
----

Alternatively, you can symlink `sqlcmd` to `/usr/local/bin/` since it is a binary:

[source,bash]
----
sudo ln --symbolic /opt/mssql-tools/bin/sqlcmd /usr/local/bin/sqlcmd
----

--

Then start `sqlcmd` and input a query. The `-S` option designates the server. The `-U` option specifies the user. 
Available options can be found at https://docs.microsoft.com/en-us/sql/tools/sqlcmd-utility?view=sql-server-ver15#syntax[sqlcmd Utility Syntax]. 


[source,bash]
----
sudo sqlcmd -S localhost -U SA
----

[source,sql]
----
SELECT name from sys.databases
GO

name
master
tempdb
model
msdb
TestDB
----


`GO` is required here to execute the previous statements.

To exit `sqlcmd`, input `quit`:


[source,sql]
----
quit
----


The full `sqlcmd` documentation can be found at https://docs.microsoft.com/en-us/sql/tools/sqlcmd-utility?view=sql-server-ver15[sqlcmd Utility].


== Administration

=== `systemd`

The `mssql-server` package installs and configures SQL Server as a https://systemd.io/[`systemd`] service. 
`systemd` provides a framework for managing services, mounts, and system states. 
You can find more details about `systemd` unit files at https://www.freedesktop.org/software/systemd/man/systemd.unit.html[systemd.unit — Unit configuration]. 
To control the `mssql-server` service, use `systemctl` to retrieve the `status`, `start`, `stop`, `restart`, `enable`, and `disable` the service.

* Display `mssql-server` status:
+
[source,bash]
----
sudo systemctl status mssql-server

● mssql-server.service - Microsoft SQL Server Database Engine
   Loaded: loaded (/usr/lib/systemd/system/mssql-server.service; enabled; vendor preset: disabled)
   Active: active (running) since Thu 2021-02-25 01:54:18 UTC; 16h ago
     Docs: https://docs.microsoft.com/en-us/sql/linux
 Main PID: 1341 (sqlservr)
    Tasks: 166
   CGroup: /system.slice/mssql-server.service
           ├─1341 /opt/mssql/bin/sqlservr
           └─1596 /opt/mssql/bin/sqlservr
----

* Start `mssql-server`:
+
[source,bash]
----
sudo systemctl start mssql-server
----

* Stop `mssql-server`:
+
[source,bash]
----
sudo systemctl stop mssql-server
----

* Restart `mssql-server`:
+
[source,bash]
----
sudo systemctl restart mssql-server
----

* Enable `mssql-server` to start on boot (`mssql-server` is enabled by default on installation):
+
[source,bash]
----
sudo systemctl enable mssql-server

Created symlink from /etc/systemd/system/multi-user.target.wants/mssql-server.service to /usr/lib/systemd/system/mssql-server.service.
----

* Disable `mssql-server` to present starting on boot:
+
[source,bash]
----
sudo systemctl disable mssql-server

Removed symlink /etc/systemd/system/multi-user.target.wants/mssql-server.service.
----

=== Logs

For troubleshooting, the logs and crash dumps are written to `/var/opt/mssql/log` by default. 
Notable logs are the *errorlogs* (+errorlog*+), *trace logs* (+*.trc+), *sqlagent logs* (+sqlagent*+), 
and the *extended events logs* (*.xel). Core dumps are written with the `.tar.gz2` extension and SQL dumps with the `.mdmp` extension. 
To view these resources, you need `root` or the `mssql` user access.

[source,bash]
----
ls /var/opt/mssql/log
HkEngineEventFile_0_132574672188100000.xel	errorlog	errorlog.4	log_20.trc	sqlagent.2  		system_health_0_132574672201000000.xel
HkEngineEventFile_0_132574672310500000.xel	errorlog.1	health.log	log_21.trc	sqlagent.3		system_health_0_132574672319150000.xel
HkEngineEventFile_0_132575629019340000.xel	errorlog.2	log_18.trc	log_22.trc	sqlagent.out		system_health_0_132575629028000000.xel
HkEngineEventFile_0_132575645400520000.xel	errorlog.3	log_19.trc	sqlagent.1	sqlagentstartup.log	system_health_0_132575645408320000.xel
----

=== Loading sample data

Microsoft has provided some https://github.com/microsoft/sql-server-samples[sample databases] 
you can use to seed your `mssql-server` instance with some data. 

Here is an example of loading our SQL server instance with the sample database `WideWorldImporters`.

Download the `WideWorldImporters` database:

[source,bash]
----
curl --location https://github.com/Microsoft/sql-server-samples/releases/download/wide-world-importers-v1.0/WideWorldImporters-Full.bak \
    --output /tmp/WideWorldImporters-Full.bak
----

Restore full backup into `mssql-server` with `sqlcmd` while updating paths for the data, userdata, transaction log, and in-memory data:

[source,sql]
----
sqlcmd -S localhost \
    -U sa \
    -P Suselove12 \
    -Q "RESTORE DATABASE WideWorldImporters \
        FROM DISK ='/tmp/WideWorldImporters-Full.bak' WITH \
        MOVE 'WWI_Primary' TO '/var/opt/mssql/data/WideWorldImporters.mdf', \
        MOVE 'WWI_UserData' TO '/var/opt/mssql/data/WideWorldImporters_UserData.ndf', \
        MOVE 'WWI_Log' TO '/var/opt/mssql/data/WideWorldImporters.ldf', \
        MOVE 'WWI_InMemory_Data_1' TO '/var/opt/mssql/data/WideWorldImporters_InMemory_Data_1'"

Processed 1464 pages for database 'WideWorldImporters', file 'WWI_Primary' on file 1.
Processed 53096 pages for database 'WideWorldImporters', file 'WWI_UserData' on file 1.
Processed 33 pages for database 'WideWorldImporters', file 'WWI_Log' on file 1.
Processed 3862 pages for database 'WideWorldImporters', file 'WWI_InMemory_Data_1' on file 1.
Converting database 'WideWorldImporters' from version 852 to the current version 904.
Database 'WideWorldImporters' running the upgrade step from version 852 to version 853.
Database 'WideWorldImporters' running the upgrade step from version 853 to version 854.
...
Database 'WideWorldImporters' running the upgrade step from version 902 to version 903.
Database 'WideWorldImporters' running the upgrade step from version 903 to version 904.
RESTORE DATABASE successfully processed 58455 pages in 37.388 seconds (12.214 MB/sec).
----

When loaded, project ten table names from the `WideWorldImporters` database to test it out:

[source,sql]
----
sqlcmd -S localhost \
    -U sa \
    -P Suselove12 \
    -Q "SELECT TOP(10) table_name FROM \
        WideWorldImporters.information_schema.tables \
        WHERE table_type = 'BASE TABLE'"

table_name
--------------------------------------------------------------------------------------------------------------------------------

Colors
Colors_Archive
OrderLines
PackageTypes
PackageTypes_Archive
StockGroups
StockItemStockGroups
StockGroups_Archive
StateProvinces
CustomerTransactions

(10 rows affected)
----

== Summary

Businesses around the world look to SUSE to help them simplify and optimize their IT environments, 
modernize their applications and infrastructure, and accelerate innovation on-premises, in the cloud, and at the edge. 
With {sles} support for Microsoft SQL Server, businesses can streamline their IT landscape and operations 
without changing their preferred enterprise database management system.

At this point, you should have a rudimentary understanding of how to install SQL Server on {sles}, 
install SQL Server tools, query SQL Server and perform basic administration. 
To stay up to date on the latest SQL Server on Linux features bookmark https://docs.microsoft.com/en-us/sql/linux/sql-server-linux-release-notes-2019?view=sql-server-ver15[Release notes for SQL Server 2019 on Linux].


== Appendix

[id="password_requirements"]
=== SQL Server password requirements

SQL Server passwords must be between 8 and 128 (inclusive), cannot contain Unicode control characters `[Ll, Lu, Nd, Cc]` 
and must contain at least three of the following:

* Uppercase letters
* Lowercase letters
* Numbers
* Symbols from the set ``(`~!@#$%^&*_-+=|\\{}[]:;\"'<>,.?)/``

=== References

* https://documentation.suse.com/sles/12-SP5/[SUSE Linux Enterprise Server 12 SP5]
* https://documentation.suse.com/external-tree/en-us/suma/4.1/suse-manager/index.html[SUSE Manager 4.1 Documentation]
* https://documentation.suse.com/sles/12-SP5/single-html/SLES-smt/#book-smt[Subscription Management Tool Guide]
* https://documentation.suse.com/sles/15-SP2/single-html/SLES-rmt/#book-rmt[Repository Mirroring Tool Guide]
* https://www.suse.com/support/kb/doc/?id=000019401[How to register a SLE system against a SMT server]
* https://www.suse.com/campaign/sql-server-on-linux/[The Power of SQL Server on Linux]
* https://docs.microsoft.com/en-us/sql/linux/sql-server-linux-setup?view=sql-server-ver15[Installation guidance for SQL Server on Linux]
* https://docs.microsoft.com/en-us/sql/linux/quickstart-install-connect-suse?view=sql-server-ver15[Quickstart: Install SQL Server and create a database on SUSE Linux Enterprise Server]
* https://docs.microsoft.com/en-us/sql/linux/sql-server-linux-configure-mssql-conf?view=sql-server-ver15[Configure SQL Server on Linux with the mssql-conf tool]
* https://docs.microsoft.com/en-us/sql/tools/sqlcmd-utility?view=sql-server-ver15[sqlcmd Utility]
* https://www.suse.com/lp/geek-guide-sql-server-on-suse[Modernizing with SQL Server on Linux for a Cloud Native World]
* https://github.com/microsoft/sql-server-samples[sql-server-samples] 


:leveloffset: 0
// Standard SUSE Best Practices includes
== Legal notice
include::common_sbp_legal_notice.adoc[]

++++
<?pdfpagebreak?>
++++

// Standard SUSE Best Practices includes
// include::common_gfdl1.2_i.adoc[]

:leveloffset: 0
include::common_gfdl1.2_i.adoc[]
